(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.g_txt03AD123 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmZBTIAAgNIAKAAQAMAAADgKIAEgMIgFAAIgahNIgBgBIgIgBIAAgIIAlAAIAAAIIgMABIgBABIAVA9IABAAIAVg9IgBgBIgLgBIAAgIIAfAAIAAAIIgIABIgBABIgiBgQgDAKgFADQgFAEgJAAQgGAAgEgBgAJvAEIAAhEIgBgCIgLAAIAAgIIAnAAIAAAIIgLAAIgBACIAABGQAAAhAeAAQATAAAHgLQAGgIAAgRIAAhDIgCgCIgLAAIAAgIIAiAAIAAAIIgKAAIgBACIAABEQAAAtgrAAQgsAAAAgtgAEaAkIgBAAQgKANgUAAQgKAAgGgGQgHgGABgMQAAgZAfAAIAWAAIAAgNQAAgSgQAAQgSAAABAWIgPAAIAAgEQAAgKAGgHQAIgJATAAQAdAAAAAbIAAAtQAAAGAGAAIADgBIACAFQgFAGgHAAQgNAAAAgNgAD1AYQAAAOAPAAQAKAAAGgHQAGgHAAgLIAAgHIgPAAQgWAAAAASgAGiAkIAAghIAHAAQABARAJAKQAJAKAOAAQANAAAHgHQAHgHAAgLQAAgJgEgGQgGgFgNgCQgZgGgHgFQgLgHAAgQQAAgMAIgJQAKgNAVAAQAXAAANAKIAAAcIgIAAQgCgOgIgIQgIgHgLAAQgKAAgGAGQgGAGAAAJQAAAJAGAFQAGAFARADQAVAEAJAKQAIAIAAAOQAAANgIAJQgMAOgYAAQgYAAgQgNgAFFAYIAAg2IgOAAIAAgHQAMgBAFgGQAFgHABgNIAHAAIAAAaIAZAAIAAAIIgZAAIAAAwQAAALABAEQADAFAHAAQAIAAAHgHIAEAFQgJANgNAAQgYAAAAgZgAACAHQAAgYANgNQAIgJAPAAQARAAAJAJQAJAKAAATIAAAGIg2AAIAAACQAAAfAZAAQAMAAALgKIAFAFQgFAHgIAFQgKAEgJAAQgmAAAAgqgAA5gCQAAgdgTAAQgSAAgBAdIAmAAIAAAAgAhLAnIAAgXIAGAAQABALAIAHQAGAHAKAAQAJAAAFgFQAFgEgBgHQAAgNgRgDQgSgDgGgEQgIgFABgLQAAgKAGgGQAJgJAPAAQARAAALAHIAAAVIgFAAQgEgJgGgGQgHgGgHAAQgGAAgFAFQgEAEAAAFQAAAHAFADQAEADAMACQARADAGAGQAGAGAAALQAAAJgGAHQgJAKgTAAQgSAAgNgKgAivAxIAAgQIgCAAQgIAPgSAAQgbAAAAgaIAAgsQAAgEgDgBIgJgCIAAgGIAZgEIABAAIAAA1QABALACAFQAEAHALAAQAKAAAGgIQAGgHgBgLIAAghQAAgEgCgBIgJgCIAAgGIAZgEIABAAIAABIQAAAFADABIAJACIAAAGIgYACgAlGAEQAAgSAIgLQAKgOAUAAQAkAAAAArQAAAVgIALQgJANgVAAQgkAAAAgtgAkygTQgEAIAAAQQABAkAUAAQANAAAFgNQADgIgBgTQABgggVAAQgMAAgFAMgAoaAHQAAgYAMgNQAJgJAPAAQAQAAAJAJQAKAKgBATIAAAGIg2AAIAAACQABAfAYAAQANAAAKgKIAGAFQgFAHgJAFQgJAEgKAAQglAAAAgqgAnkgCQABgdgUAAQgRAAgCAdIAmAAIAAAAgApuAHQAAgYAMgNQAJgJAPAAQARAAAJAJQAIAKABATIAAAGIg2AAIAAACQgBAfAZAAQAMAAALgKIAGAFQgFAHgJAFQgJAEgKAAQglAAAAgqgAo4gCQAAgdgSAAQgSAAgBAdIAlAAIAAAAgArQAkIAAghIAHAAQACARAIAKQAJAKAOAAQANAAAHgHQAHgHAAgLQAAgJgFgGQgFgFgNgCQgYgGgIgFQgLgHAAgQQAAgMAIgJQAKgNAVAAQAXAAANAKIAAAcIgHAAQgEgOgIgIQgHgHgLAAQgKAAgGAGQgGAGAAAJQAAAJAGAFQAGAFAQADQAWAEAJAKQAIAIAAAOQAAANgIAJQgLAOgZAAQgYAAgQgNgAIEAwIAAgIIAMAAIABgCIAAhmIgBgBIgMgBIAAgIIBXAAIAAAdIgHAAQgEgOgEgDQgEgDgNAAIgbAAIAAAxIASAAQALAAADgCQADgDACgLIAGAAIAAApIgGAAQgCgKgDgDQgDgDgLAAIgSAAIAAAtIACACIALAAIAAAIgACEAwIAAgIIALAAIABgCIAAhEIgMAAIAAgJIAMAAIAAgRQAAgNAHgHQAGgHANAAQAXAAAAAXIAAACIgPAAQgBgJgBgDQgCgFgGAAQgJAAAAANIAAAXIAVAAIAAAJIgVAAIAABEIABACIANAAIAAAIgABVAwIAAgIIAKAAIACgCIAAhoQgBgFgCAAIgJgCIAAgGIAYgEIACAAIAAB5IACACIAJAAIAAAIgAiOAwIAAgIIAKAAIADgCIAAg7QAAgFgEgBIgJgBIAAgGIAZgFIABAAIgBATIABAAQAJgTATAAIAJABIgDAPQgFgCgGAAQgKAAgGAIQgGAJAAANIAAAhIABACIAKAAIAAAIg");
	this.shape.setTransform(74.85,13.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.7,5.2,144.3,16.900000000000002);


(lib.g_txt02AD1new = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AIeCZIgTg7IgCAAIAAA7IgbAAIAAiJIAbAAIATA9IACAAIAAg9IAbAAIAACJgAGqCZQgPgFAAgRIAAhbQAAgSAPgGIAsAAQAQAGgBASIAABbQABARgQAFgAG5ArIAABUIACACIAKAAIACgCIAAhUIgCgCIgKAAgAFoCZIAAgcIAGAAIAAhQIgGAAIAAgdIAqAAIAAAdIgGAAIAABQIAGAAIAAAcgAEvCZIAAhsIgXAAIAAgdIBLAAIAAAdIgXAAIAABsgAD5CZIgDgaIgOAAIgCAaIgdAAIAAgWIARhzIApAAIASBzIAAAWgADzBiIgDgqIgCAAIgEAqIAJAAgACICZIgRhxIAAgYIAdAAIAJBjIACAAIAIhjIAdAAIAAAYIgSBxgAA0CZQgPgFAAgRIAAhbQAAgSAPgGIAtAAQAPAGAAASIAABbQAAARgPAFgABEArIAABUIACACIAJAAIACgCIAAhUIgCgCIgJAAgAABCZIgSg7IgBAAIAAA7IgbAAIAAiJIAbAAIASA9IABAAIAAg9IAbAAIAACJgAhRCZIgTg7IgBAAIAAA7IgbAAIAAiJIAbAAIATA9IABAAIAAg9IAbAAIAACJgAi0CZIAAgcIAHAAIAAhQIgHAAIAAgdIArAAIAAAdIgGAAIAABQIAGAAIAAAcgAjwCZIgRg0IgEAAIAAA0IgeAAIAAiJIA7AAQAPAGABASIAAAdQAAAQgNAFIAQAsIAAATgAkFBMIAMAAIACgCIAAgfIgCgCIgMAAgAloCZQgPgFAAgRIAAhbQAAgSAPgGIAtAAQAPAGAAASIAABbQAAARgPAFgAlYArIAABUIACACIAJAAIACgCIAAhUIgCgCIgJAAgAm/CZIAAiJIA/AAIAAAdIggAAIAAAbIAeAAIAAAdIgeAAIAAA0gAHugPIAAiKIA8AAQAPAGAAASIAABbQAAARgPAGgAINgoIAMAAIACgCIAAhUIgCgCIgMAAgAGrgPIAAiKIAeAAIAABtIAfAAIAAAdgAGLgPIgSg1IgDAAIAAA1IgfAAIAAiKIA8AAQAPAGAAASIAAAcQAAARgNAGIAQArIAAAUgAF2hdIALAAIACgCIAAgfIgCgCIgLAAgAETgPQgPgGAAgRIAAhbQAAgSAPgGIAtAAQAOAGAAASIAABbQAAARgOAGgAEih+IAABUIADACIAJAAIACgCIAAhUIgCgCIgJAAgADIgPIgFhUIgCAAIgGBUIglAAIgQhxIAAgZIAbAAIAHBSIABAAIAGhSIAmAAIAFBSIADAAIAFhSIAbAAIAAAZIgPBxgAAjgPIAAiKIA/AAIAAAdIghAAIAAAZIAfAAIAAAcIgfAAIAAAbIAiAAIAAAdgAgDgPIAAg1IgOAAIAAA1IgeAAIAAiKIAeAAIAAA4IAOAAIAAg4IAdAAIAACKgAhpgPIAAhtIgWAAIAAgdIBKAAIAAAdIgWAAIAABtgAi8gPIgTg8IgBAAIAAA8IgbAAIAAiKIAbAAIASA8IACAAIAAg8IAbAAIAACKgAkfgPIAAgdIAHAAIAAhQIgHAAIAAgdIArAAIAAAdIgGAAIAABQIAGAAIAAAdgAmAgPQgPgGABgRIAAgSIAcAAIAAAOIACACIALAAIADgCIAAglIgDgCIgLAAIgCACIAAAHIgcAAIAAhRIBIAAIAAAbIgsAAIAAAeIAIgIIAXAAQAPAFAAASIAAArQAAARgPAGgAnbgPIAAgdIARAAIAAhQIgPAAIAAgdIAuAAIAABtIAOAAIAAAdgAoWgPIAGgnIgLAAIgHAnIgUAAIAGgnIgIAAIAAgWIAMAAIADgRIgJAAIAAgXIAMAAIAHglIAUAAIgGAlIAMAAIAGglIAVAAIgGAlIAIAAIAAAXIgMAAIgDARIAJAAIAAAWIgMAAIgHAngAoXhMIALAAIADgRIgLAAg");
	this.shape.setTransform(-62.85,18.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AntC4IAAirIh9AAIAAjEITVAAIAACHIAADog");
	this.shape_1.setTransform(-61.875,18.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Small_Text
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ak5AqIgBgBIAAgJIABgBIAGAAIAEgCIACgFIAAgBIgPgrIAAgBIABgBIALAAIACABIAHAcIAAABIAAgBIAIgcIABgBIAMAAIAAABIAAABIgQAtQgCAHgCADQgCAEgEABQgFACgIAAgAAeApIgCgBIABgJQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAGAAQAGAAADgCQADgDAAgFIAAgBQgEAEgHAAQgFAAgGgDQgEgDgDgGIgBgLQAAgGACgEQACgGAEgDQAFgDAGAAQAGAAAFAEIAAAAIAAAAIAAgCIABgBIAAgBIALAAIAAABIAAApQAAALgGAFQgHAFgLAAgAAjgKIgCAEQgCADAAADIABAIIADADQACACADAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIABgIIgBgGQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBgBQgCgBgCAAQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBAAgAKyAhQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIADgUIABgBIAJAAIABABIgFAVIgBABgAMTATQgGgFAAgKIAAgXQAAgJAGgFQAGgGAJAAQALAAAFAGQAGAFAAAJIAAAXQAAAKgGAFQgFAGgLAAQgJAAgGgGgAMcgaQgCADAAAEIAAAYQAAAEACACQACADAEAAQAEAAADgDQACgCAAgEIAAgYQAAgEgCgDQgDgCgEAAQgEAAgCACgAJXAUQgGgDgBgHIgCgJQAAgFACgEQACgHAFgDQAFgEAHAAQAIAAAGAEQAEADACAHQACAEAAAEIgBAJQgCAHgFAEQgGAEgIAAQgHAAgFgEgAJfgKIgEAFIAAAGIAAAGIAEAFQACACACAAQADAAADgCIACgFIABgGIgBgGIgCgFQgDgBgDAAQgCAAgCABgAIfAWQgEgDAAgHIAAgXIgBAAIgEAAIgCgBIAAAAIAAgIIAAgBIACgBIAFAAIAAgLIABgBIAKAAIABABIAAALIAJAAIABABIAAAJIgBABIgIAAIgBAAIAAASQAAABAAABQAAAAAAABQABAAAAABQAAAAABABQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIAEAAIAAAKIgBABIgFAAQgHAAgEgCgAHpAVQgEgDgBgHQAAgHAGgEQAFgDAIAAIAJAAIABAAIAAgCQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgCgBgDAAIgFABIgCACIgBABIgLgBIgBgBQAAgEADgDQADgDAEgCQAEgBAFAAQAHAAAEACQAEACADADQADAEAAAEIAAAeIAAAAIgBABIgLAAIgBgBIAAgEIgBABQgDAEgIAAQgIAAgEgDgAH0AFQgCACAAADQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAABQACABADAAQAEAAACgCQADgCAAgDIAAgEIgBAAIgGAAQgEAAgCABgAGOAUQgFgDgCgHIgBgJQAAgFABgEQACgHAGgDQAFgEAHAAQAHAAAGAEQAFADACAHQABAEAAAEIgBAJQgCAHgFAEQgGAEgHAAQgIAAgFgEgAGWgKIgDAFIgBAGIABAGIADAFQACACADAAQADAAACgCIADgFIABgGIgBgGIgDgFQgCgBgDAAQgDAAgCABgACvAUQgGgDgBgHIgCgJQAAgFACgEQACgHAFgDQAFgEAHAAQAIAAAGAEQAEADACAHQACAEAAAEIgBAJQgCAHgFAEQgGAEgIAAQgHAAgFgEgAC3gKIgEAFIAAAGIAAAGIAEAFQACACACAAQAEAAACgCIACgFIABgGIgBgGIgCgFQgCgBgEAAQgCAAgCABgABOAXQgFgCgDgDQgCgDAAgEIAAgBIABgBIAAAAIAKAAIABAAIAAABQAAABABAAQAAABAAAAQAAABABAAQAAAAAAABIAGABIAFgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgGgBIgHgCQgFgCgEgDQgDgCAAgGQAAgGAFgEQAFgEAIAAQAGAAAEACQAFACADADQABADAAAEIAAABIgBABIgJAAIAAgBIgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQgCgBgEAAIgFABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAHABIAFACQAGACAEACQAEADgBAFQAAAHgEAEQgGADgJAAQgGAAgEgBgAjBAVQgEgDgBgHQAAgHAGgEQAFgDAIAAIAJAAIABAAIAAgCQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgCgBgDAAIgFABIgCACIgBABIgLgBIgBgBQAAgEADgDQADgDAEgCQAEgBAGAAQAGAAAEACQAFACACADQADAEAAAEIAAAeIAAAAIgBABIgLAAIgBgBIAAgEIgBABQgDAEgJAAQgGAAgFgDgAi2AFQgCACAAADQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAABQACABADAAQADAAADgCQADgCAAgDIAAgEIgBAAIgGAAQgEAAgCABgAlTAWQgDgDgBgHIAAgXIAAAAIgFAAIgBgBIgBAAIAAgIIABgBIABgBIAFAAIAAgLIABgBIAKAAIABABIAAALIAJAAIACABIAAAJIgCABIgIAAIgBAAIAAASQAAABABABQAAAAAAABQAAAAAAABQABAAAAABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAIAEAAIAAAKIgBABIgEAAQgIAAgEgCgAmWAXQgFgCgDgDQgCgDAAgEIAAgBIAAgBIABAAIAKAAIABAAIAAABQAAABABAAQAAABAAAAQAAABABAAQAAAAABABIAFABIAFgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgGgBIgHgCQgGgCgDgDQgDgCgBgGQABgGAFgEQAFgEAIAAQAHAAADACQAFACACADQACADAAAEIAAABIgBABIgJAAIgBgBIAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQgCgBgEAAIgEABQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAQAAABABAAIAGABIAFACQAGACAEACQAEADgBAFQAAAHgEAEQgGADgJAAQgGAAgEgBgAnoAVQgGgEgCgGQgCgEAAgHQgBgFACgDQACgHAGgEQAFgDAGAAQAKAAAFAFQAGAFAAAJIABAGQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgcAAIgBAAIABAEQADAFAHAAQAGAAADgFIABgBIAHAHIAAABIAAABQgCADgGACQgEACgGAAQgHAAgFgDgAnlgGIgBADIABAAIAPAAIABAAIgBgDIgCgEQgCgBgEAAQgFAAgCAFgAqUAWQgGgDgCgFQgDgFAAgGIAAgoIABgBIAKAAIABAAIAAApQAAAFADADQADADAFAAQAFAAACgDQADgDAAgFIAAgoIABgBIALAAIABAAIAAApQAAAGgDAFQgDAFgFADQgFACgHAAQgHAAgFgCgArdAVQgFgEgCgGQgCgEABgHQgBgFACgFQADgFAEgEQAEgDAHAAQAGAAAEAEIAAAAIAAgUIABAAIALAAIABABIAAA8IgBABIgLAAIgBgBIAAgDIAAgBIAAABQgEAEgGAAQgHAAgEgDgArWgIQgCAEgBAFQAAAFACAEQADAEAEAAQAFAAACgEQABgEAAgFQAAgFgBgEQgCgDgFAAQgEAAgCADgAtHAUQgEgDgDgHIgBgJQAAgFABgEQACgHAGgDQAFgEAHAAQAIAAAGAEQAFADACAHQABAEAAAEIgBAJQgCAHgFAEQgGAEgIAAQgHAAgGgEgAs+gKIgDAFIgBAGIABAGIADAFQABACADAAQAEAAABgCIADgFIABgGIgBgGIgDgFQgBgBgEAAQgDAAgBABgAOPAYIgBgBIAAgPIgBAAIgbAAIgBgBIAAgBIAAgGIAAgBIARgkIAAgBIAMAAIABAAIgPAjIAAAAIANAAIABAAIAAgLIAAgBIANAAIAAABIAAALIABAAIADAAIABABIAAAJIgBABIgDAAIgBAAIAAAPIAAAAIgBABgANBAYIgBgBIAAgJIABgBIATgUQAJgJAAgFQAAgDgCgCQgDgCgEAAQgDAAgDACQgCACAAADIAAADIgBABIgKAAIgBgBIAAAAIAAgFQAAgFADgDQADgEAEgCQAFgCAFAAQAHAAAEACQAFADADAEQACAEAAAFQAAAEgCAEIgFAIIgRARIAAABIAYAAIABAAIAAAKIgBABgALcAYIgBgBIAAgJIABgBIAUgUQAHgJABgFQAAgDgDgCQgCgCgDAAQgEAAgDACQgBACAAADIAAADIgBABIgLAAIgBgBIgBAAIAAgFQABgFADgDQADgEAEgCQAFgCAGAAQAGAAAEACQAFADADAEQADAEgBAFQAAAEgBAEIgGAIIgRARIAAABIAYAAIABAAIAAAKIgBABgAKeAYIgBgBIAAgaQgBgEgCgCQgCgCgDAAQgDAAgCACQgCACAAAEIAAAaIgBABIgKAAIgBgBIgBAAIAAgrIABgBIABgBIAKAAIABABIAAABIAAADIABAAQADgFAHAAQAIAAAEAEQAEAFAAAHIAAAdIAAAAIgBABgAI6AYIgBgBIAAgsIABgBIALAAIABABIAAAsIgBABgAHGAYIgBgBIgPgrIAAgBIABgBIALAAIABABIAIAbIAAAAIAIgbIABgBIANABIAAABIgPArIgBABgAFyAYIgBgBIAAgaQAAgEgCgCQgCgCgEAAQgDAAgBACQgCACAAAEIAAAaIgBABIgLAAIgBgBIgBAAIAAgrIABgBIABgBIALAAIAAABIABABIAAADIAAAAQADgFAIAAQAHAAAEAEQAFAFAAAHIAAAdIAAAAIgBABgAFBAYIgBgBIAAgaQAAgEgCgCQgCgCgEAAQgCAAgDACQgCACAAAEIAAAaIgBABIgKAAIgBgBIAAAAIAAgrIAAgBIABgBIAKAAIABABIAAABIAAADIABAAQADgFAIAAQAHAAAFAEQAEAFAAAHIAAAdIgBAAIgBABgAEPAYIgBgBIAAg8IABgBIALAAIABAAIAAA9IgBABgADbAYIgCgBIAAAAIAAgrIAAgBIACgBIAKAAIABABIAAABIAAADIABAAQADgFAGAAQADAAADABIAAABIgCALQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCAAIgCAAQgEAAgCACQgCADAAADIAAAYIgBABgACKAYIgBgBIAAghIgBgBIgEAAIgBAAIAAgKIABgBIAEAAIABAAIAAgCQAAgGACgDQABgDAEgBIALgBIAEAAIABABIAAAHIgBABIgDAAIgFABIgBAFIAAABIAAAAIAJAAIABABIAAAKIgBAAIgJAAIAAABIAAAhIgBABgAAAAYIgBgBIAAgaQAAgEgCgCQgCgCgEAAQgCAAgCACQgCACgBAEIAAAaIgBABIgKAAIgBgBIgBAAIAAgrIABgBIABgBIAKAAIABABIAAABIAAADIABAAQAEgFAHAAQAGAAAEAEQAFAFAAAHIAAAdIgBAAIgBABgAgxAYIgBgBIAAgsIABgBIAKAAIABABIAAAsIgBABgAhFAYIgBgBIgJgVIgBAAIgFAHIAAABIAAANIgBABIgLAAIgBgBIgBAAIAAg8IABgBIABAAIALAAIABABIAAAeIAAAAIAMgOIABgBIANAAIABABIgBABIgMAOIAAABIAOAbIAAABIgBABgAh3AYIgBgBIAAgaQAAgEgCgCQgCgCgEAAQgCAAgDACQgCACAAAEIAAAaIgBABIgKAAIgBgBIAAAAIAAgrIAAgBIABgBIAKAAIABABIAAABIAAADIABAAQADgFAIAAQAHAAAFAEQAEAFAAAHIAAAdIgBAAIgBABgAjXAYIgBgBIgLgYIgJAAIAAAAIAAAYIgBABIgLAAIgBgBIAAg8IABgBIAaAAQAFAAAFACQAEACACAFQADAEAAAGQAAAGgDAEQgDAFgGABIAAABIANAYIAAABIgBABgAjsgbIAAAPIAAABIAMAAQADAAADgCQADgDgBgDQABgEgDgCQgDgCgDAAIgMAAIAAAAgAlwAYIgBgBIAAgsIABgBIAKAAIACABIAAAsIgCABgAm/AYIgBgBIgBAAIAAgrIABgBIABgBIALAAIAAABIABABIAAADIAAAAQAEgFAGAAQADAAACABIABABIgDALQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgDAAIgCAAQgDAAgDACQgBADAAADIAAAYIgBABgAoTAYIgBgBIgPgrIAAgBIACgBIALAAIABABIAIAbIAAAAIAIgbIABgBIAMABIAAABIgOArIgBABgAo1AYIgBgBIAAgsIABgBIALAAIABABIAAAsIgBABgApLAYIgBgBIAAgaQAAgEgCgCQgCgCgEAAQgCAAgDACQgCACAAAEIAAAaIgBABIgKAAIgBgBIAAAAIAAgrIAAgBIABgBIAKAAIABABIAAABIAAADIABAAQADgFAIAAQAHAAAFAEQAEAFAAAHIAAAdIgBAAIgBABgAr4AYIgBgBIgBAAIAAg8IABgBIABAAIAKAAIABABIAAA8IgBABgAsaAYIgBgBIgBAAIAAgrIABgBIABgBIAKAAIAAABIABABIAAADIAAAAQAEgFAGAAQAEAAACABIAAABIgCALQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAIgEAAIgCAAQgCAAgDACQgCADAAADIAAAYIgBABgAtvAYIgBgBIgKgmIAAAAIgJAmIgBABIgKAAIgBgBIgQg8IABgBIAMAAIABABIAIAkIABABIAAgBIAIgkIABgBIALAAIABABIAJAkIAAABIAAgBIAJgkIABgBIALAAIABABIgPA8IgBABgAI7gdQgCgCgBgDQABgDACgCQACgCACAAQADAAADACQABACAAADQAAADgBACQgDACgDAAQgCAAgCgCgAgxgdQgCgCAAgDQAAgDACgCQACgCADAAQADAAACACQACACAAADQAAADgCACQgCACgDAAQgDAAgCgCgAlwgdQgCgCAAgDQAAgDACgCQACgCAEAAQACAAACACQADACAAADQAAADgDACQgCACgCAAQgEAAgCgCgAo1gdQgCgCAAgDQAAgDACgCQADgCACAAQADAAADACQACACAAADQAAADgCACQgDACgDAAQgCAAgDgCg");
	this.shape_2.setTransform(-99.2,43.425);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-192,0,192,47.6);


(lib.g_txt01AD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJFDRIAAi8IBWAAIAAAoIgtAAIAAAhIArAAIAAAnIgrAAIAAAlIAuAAIAAAngAHnDRQgUgIAAgXIAAh9QAAgYAUgIIA9AAQAVAIgBAYIAAAfIgpAAIAAgaIgDgDIgNAAIgDADIAAByIADADIANAAIADgDIAAghIgLAAIAAgnIA0AAIAABOQABAXgVAIgAGiDRIgahSIgDAAIAABSIgkAAIAAi8IAkAAIAaBSIADAAIAAhSIAkAAIAAC8gAEwDRIgDglIgUAAIgDAlIgnAAIAAggIAXicIA5AAIAYCcIAAAggAEqCFIgGg7IgCAAIgGA7IAOAAgAC8DRIAAhJIgTAAIAABJIgqAAIAAi8IAqAAIAABMIATAAIAAhMIApAAIAAC8gAAiDRQgUgIgBgXIAAh9QABgYAUgIIA8AAQAVAIAAAYIAAAtIgqAAIAAgoIgCgDIgOAAIgCADIAAByIACADIAOAAIACgDIAAgnIAqAAIAAAtQAAAXgVAIgAh8DRIAAi8IBVAAIAAAoIgsAAIAAAhIAqAAIAAAnIgqAAIAAAlIAuAAIAAAngAjMDRIAAiUIgdAAIAAgoIBkAAIAAAoIgdAAIAACUgAkVDRIgDglIgVAAIgDAlIgmAAIAAggIAXicIA5AAIAXCcIAAAggAkcCFIgFg7IgDAAIgFA7IANAAgAm4DRIAAi8IBWAAIAAAoIgtAAIAAAhIAqAAIAAAnIgqAAIAAAlIAuAAIAAAngAnkDRIgYhJIgEAAIAABJIgqAAIAAi8IBRAAQAVAIAAAYIAAAoQAAAWgRAIIAWA7IAAAbgAoABmIAQAAIADgCIAAgqIgDgDIgQAAgAqHDRQgUgIAAgXIAAh9QAAgYAUgIIA9AAQAUAIAAAYIAAAtIgqAAIAAgoIgCgDIgOAAIgCADIAAByIACADIAOAAIACgDIAAgnIAqAAIAAAtQAAAXgUAIgAJHgUIAAi8IBVAAIAAAoIgsAAIAAAkIAqAAIAAAnIgqAAIAABJgAHpgUIAAi8IAqAAIAACVIArAAIAAAngAGFgUIAAi8IBWAAIAAAoIgsAAIAAAhIApAAIAAAnIgpAAIAAAlIAtAAIAAAngAEpgUQgVgIAAgXIAAglIAqAAIAAAfIACADIAOAAIACgDIAAgcIgCgEIgrgTQgJgEgDgHQgDgGAAgMIAAgnQAAgYAVgIIA9AAQATAIABAYIAAAjIgqAAIAAgeIgCgDIgOAAIgCADIAAAbIADAEIAqARQAJAEADAHQACAGABAMIAAArQgBAXgTAIgADqgUIgYhJIgEAAIAABJIgqAAIAAi8IBRAAQAUAIAAAYIAAAoQAAAWgRAIIAXA7IAAAbgADOh/IAPAAIADgCIAAgqIgDgDIgPAAgABJgUQgUgIAAgXIAAidIApAAIAACXIADADIAKAAIADgDIAAiXIApAAIAACdQAAAXgUAIgAgogUQgVgIABgXIAAh9QgBgYAVgIIA8AAQAUAIAAAYIAAB9QAAAXgUAIgAgTirIAAByIADADIAMAAIAEgDIAAhyIgEgDIgMAAgAiPgUIAAhKIgghSIAAggIAoAAIALBBIADAAIAMhBIAnAAIAAAgIggBSIAABKgAk3gUIAAi8IBWAAIAAAoIgsAAIAAAhIApAAIAAAnIgpAAIAAAlIAtAAIAAAngAmbgUIAAi8IBWAAIAAAoIgsAAIAAAhIApAAIAAAnIgpAAIAAAlIAtAAIAAAngAn3gUQgVgIAAgXIAAglIAqAAIAAAfIACADIAOAAIACgDIAAgcIgCgEIgrgTQgJgEgDgHQgDgGAAgMIAAgnQAAgYAVgIIA9AAQATAIABAYIAAAjIgqAAIAAgeIgCgDIgOAAIgCADIAAAbIADAEIAqARQAJAEADAHQACAGABAMIAAArQgBAXgTAIg");
	this.shape.setTransform(-69.45,24.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-136.3,4.1,133.70000000000002,41.699999999999996);


(lib.g_SFULogo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// icon
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiWBIQgLgCgNgGQAEgIACgNQAIAHAHADQAKAFAMAAQANAAAHgGQAIgHAAgLQAAgKgLgIQgFgEgOgGQgOgGgGgDQgOgKAAgTQAAgRALgLQAMgMAVAAQAJAAAMADIANAEIgDAIIgDALQgKgHgJgCQgHgDgHAAQgJAAgGAGQgGAFAAAJQAAAKAIAHIAbAPQATAIAGAJQAFAIAAAKQAAAOgKAMQgNASgdAAgABMA/QgIgGgFgHQgDgGgBgFIgBgVIgChYIANABIAMgBIgCATIgBA/IABAWQABAFADAEQAJANAZAAQAQAAAKgGIAIgHQAEgEAAgHIABgYIAAggIgBgeIgBgQIALABIAKgBIgBBPQAAAZgDALQgEAKgLAIQgOAJgaAAQgbAAgNgJgAgqBGIgLABIACgUIgBh5IA8ABIAQgBIgBAKIAAAKIgJgBIgsgBIAAAqIAZAAQANAAALgCIgBALIABAJIgxgCIAAASQAAAcABATg");
	this.shape.setTransform(51.8777,26.2994,1.0947,1.0963);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#992932").s().p("AlRCpIAAlRIKjAAIAAFRg");
	this.shape_1.setTransform(37.0174,18.5429,1.0947,1.0963);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,74,37.1);


(lib.btn_CTA_AD_123 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgvBDIBChDIhChCIAOgPIBRBRIhRBRg");
	this.shape.setTransform(14,12.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AB/AoQgGgEgEgHQgFgHAAgJIAAgaQAAgIAFgHQAEgHAGgEQAIgEAKAAQAJAAAHAEQAIAEADAHQAEAHABAIIAAAaQgBAJgEAHQgDAHgIAEQgHAEgJAAQgKAAgIgEgACGgYQgFAFAAAGIAAAaQAAAIAFAEQADAEAIAAQAGAAAEgEQAFgEAAgIIAAgaQAAgGgFgFQgEgEgGAAQgIAAgDAEgAkHAoQgHgEgFgHQgEgHAAgJIAAgaQAAgIAEgHQAFgHAHgEQAHgEAJAAQAKAAAHAEQAHAEAFAHQAEAHAAAIIAAAaQAAAJgEAHQgFAHgHAEQgHAEgKAAQgJAAgHgEgAkCgYQgDAFAAAGIAAAaQAAAIADAEQAFAEAGAAQAHAAAEgEQAEgEAAgIIAAgaQAAgGgEgFQgEgEgHAAQgGAAgFAEgAIHAoQgHgCgEgHQgEgFAAgIIAAgDIAAgBIABAAIAPAAIABAAIAAADQgBAFAFAEQAFADAIAAQAGgBADgCQADgDAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAgBQgCgCgEgBIgLgFIgNgFQgGgCgEgFQgEgGAAgGQAAgIAEgGQADgFAIgDQAGgDAJAAQAJAAAHADQAIADAEAGQAEAHAAAIIAAABIAAABIgBAAIgPAAIgBAAIAAgBIAAgBQAAgFgEgDQgFgEgHAAQgGAAgDADQgDACAAAEQAAADACACIAGAEIALAFIAOAFQAEACAFAEQAEAFAAAIQgBALgIAHQgJAHgOAAQgJgBgIgDgADLAnQgHgDgFgHQgDgGAAgKIAAgaQAAgJADgHQAFgGAHgEQAHgEAJAAQAJAAAIAEQAHAEAEAFQAEAHAAAIIAAAAIAAABIgBABIgPAAIgBgBIAAgBIAAAAQgBgGgDgDQgEgEgHAAQgGAAgEAEQgEAEAAAGIAAAcQAAAGAEAEQAEAFAHAAQAGAAAEgDQAEgEAAgGIAAgFIAAgBIgPAAIgBAAIAAgBIAAgLIAAgBIAhAAIAAABIAAAPQAAAJgEAHQgEAHgHAEQgHAEgKAAQgJgBgHgEgAHdAqIgBAAIgBgBIAAg2IAAABIgOAUIgCABIgHAAIgBgBIgNgUIAAAAIgBAAIAAA1IgBABIgBAAIgNAAIgBAAIgBgBIAAhSIABAAIABgBIANAAIADABIASAcIABAAIASgcIACgBIAOAAIABABIABAAIAABSIgBABIgBAAgAGJAqIgCgBIgDgMIgBAAIgeAAIAAAAIgFAMQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgQAAIgBAAIAAgBIAbhSQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIATAAIACABIAaBSIAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAgAFzgVIgKAkIAAAAIAVAAQACAAgBAAIgLgkIgBAAgAE3AqIgCgBIgPghIgBgBIgLAAIgBABIAAAhIgBABIAAAAIgPAAIgBAAIAAgBIAAhSIAAAAIABgBIAjAAQAIAAAGADQAGAEADAFQAEAGgBAIQAAAIgDAGQgFAFgIACIAAABIARAjIAAAAIgBABgAEZgaIAAAVIABAAIAQAAQAFAAADgDQAEgDgBgFQABgFgEgDQgDgDgFAAIgQAAIgBABgABXAqIgDgBIgOghIgBgBIgMAAIgBABIAAAhIAAABIgBAAIgOAAIgBAAIgBgBIAAhSIABAAIABgBIAjAAQAHAAAHADQAFAEAEAFQADAGAAAIQAAAIgEAGQgEAFgIACIAAABIAQAjIAAAAIgBABgAA4gaIAAAVIABAAIAQAAQAGAAADgDQADgDAAgFQAAgFgDgDQgDgDgGAAIgQAAIgBABgAgfAqIgBAAIgBgBIAAhSIABAAIABgBIAhAAQAIAAAHADQAFAEAEAFQADAHAAAIQAAAHgDAGQgEAFgGADQgGADgJABIgQAAIgBAAIAAAfIAAABIgBAAgAgQgaIAAAWIABAAIAPAAQAFAAAEgCQADgEAAgFQAAgFgDgEQgEgDgFAAIgPAAIgBABgAh9AqIgBAAIgBgBIAAhSIABAAIABgBIA4AAIABABIAAAOIgBAAIgoAAIgBABIAAATIABAAIAaAAIABABIABABIAAAKIgBABIgBABIgaAAIgBABIAAATIABABIAoAAIABAAIAAAOIgBAAgAiaAqIgDgBIgOghIgBgBIgMAAIgBABIAAAhIAAABIgBAAIgOAAIgBAAIgBgBIAAhSIABAAIABgBIAjAAQAIAAAFADQAGAEAEAFQADAGAAAIQAAAIgEAGQgEAFgIACIAAABIAQAjIAAAAIgBABgAi5gaIAAAVIABAAIAQAAQAFAAADgDQAEgDAAgFQAAgFgEgDQgDgDgFAAIgQAAIgBABgAlZAqIgBAAIgBgBIAAhSIABAAIABgBIAOAAIABABIAAAAIAABEIABABIAoAAIABAAIABABIAAAMIgBABIgBAAgAmiAqIgBAAIgBgBIAAhSIABAAIABgBIAiAAQAIAAAHADQAFAEAEAFQADAHAAAIQAAAHgDAGQgEAFgGADQgGADgJABIgRAAIgBAAIAAAfIAAABIgBAAgAmTgaIAAAWIABAAIAQAAQAFAAAEgCQADgEAAgFQAAgFgDgEQgEgDgFAAIgQAAIgBABgAm/AqIgBgBIgQgcIgBAAIgQAcIgCABIgPAAIgBAAIAAgBIAYgpIAAAAIgZgpQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAPAAIACABIAQAcIABAAIAQgcIABgBIAQAAIABABIAAABIgYAoIAAAAIAYApIAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAgAo1AqIgBAAIAAgBIAAhSIAAAAIABgBIA4AAIABABIAAAOIgBAAIgnAAIgBABIAAATIABAAIAaAAIABABIAAABIAAAKIAAABIgBABIgaAAIgBABIAAATIABABIAnAAIABAAIAAAOIgBAAg");
	this.shape_1.setTransform(82.75,12.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgvBDIBChDIhChCIAOgPIBRBRIhRBRg");
	this.shape_2.setTransform(14,12.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AB/AoQgGgEgEgHQgFgHAAgJIAAgaQAAgIAFgHQAEgHAGgEQAIgEAKAAQAJAAAHAEQAIAEADAHQAEAHABAIIAAAaQgBAJgEAHQgDAHgIAEQgHAEgJAAQgKAAgIgEgACGgYQgFAFAAAGIAAAaQAAAIAFAEQADAEAIAAQAGAAAEgEQAFgEAAgIIAAgaQAAgGgFgFQgEgEgGAAQgIAAgDAEgAkHAoQgHgEgFgHQgEgHAAgJIAAgaQAAgIAEgHQAFgHAHgEQAHgEAJAAQAKAAAHAEQAHAEAFAHQAEAHAAAIIAAAaQAAAJgEAHQgFAHgHAEQgHAEgKAAQgJAAgHgEgAkCgYQgDAFAAAGIAAAaQAAAIADAEQAFAEAGAAQAHAAAEgEQAEgEAAgIIAAgaQAAgGgEgFQgEgEgHAAQgGAAgFAEgAIHAoQgHgCgEgHQgEgFAAgIIAAgDIAAgBIABAAIAPAAIABAAIAAADQgBAFAFAEQAFADAIAAQAGgBADgCQADgDAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAgBQgCgCgEgBIgLgFIgNgFQgGgCgEgFQgEgGAAgGQAAgIAEgGQADgFAIgDQAGgDAJAAQAJAAAHADQAIADAEAGQAEAHAAAIIAAABIAAABIgBAAIgPAAIgBAAIAAgBIAAgBQAAgFgEgDQgFgEgHAAQgGAAgDADQgDACAAAEQAAADACACIAGAEIALAFIAOAFQAEACAFAEQAEAFAAAIQgBALgIAHQgJAHgOAAQgJgBgIgDgADLAnQgHgDgFgHQgDgGAAgKIAAgaQAAgJADgHQAFgGAHgEQAHgEAJAAQAJAAAIAEQAHAEAEAFQAEAHAAAIIAAAAIAAABIgBABIgPAAIgBgBIAAgBIAAAAQgBgGgDgDQgEgEgHAAQgGAAgEAEQgEAEAAAGIAAAcQAAAGAEAEQAEAFAHAAQAGAAAEgDQAEgEAAgGIAAgFIAAgBIgPAAIgBAAIAAgBIAAgLIAAgBIAhAAIAAABIAAAPQAAAJgEAHQgEAHgHAEQgHAEgKAAQgJgBgHgEgAHdAqIgBAAIgBgBIAAg2IAAABIgOAUIgCABIgHAAIgBgBIgNgUIAAAAIgBAAIAAA1IgBABIgBAAIgNAAIgBAAIgBgBIAAhSIABAAIABgBIANAAIADABIASAcIABAAIASgcIACgBIAOAAIABABIABAAIAABSIgBABIgBAAgAGJAqIgCgBIgDgMIgBAAIgeAAIAAAAIgFAMQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgQAAIgBAAIAAgBIAbhSQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIATAAIACABIAaBSIAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAgAFzgVIgKAkIAAAAIAVAAQACAAgBAAIgLgkIgBAAgAE3AqIgCgBIgPghIgBgBIgLAAIgBABIAAAhIgBABIAAAAIgPAAIgBAAIAAgBIAAhSIAAAAIABgBIAjAAQAIAAAGADQAGAEADAFQAEAGgBAIQAAAIgDAGQgFAFgIACIAAABIARAjIAAAAIgBABgAEZgaIAAAVIABAAIAQAAQAFAAADgDQAEgDgBgFQABgFgEgDQgDgDgFAAIgQAAIgBABgABXAqIgDgBIgOghIgBgBIgMAAIgBABIAAAhIAAABIgBAAIgOAAIgBAAIgBgBIAAhSIABAAIABgBIAjAAQAHAAAHADQAFAEAEAFQADAGAAAIQAAAIgEAGQgEAFgIACIAAABIAQAjIAAAAIgBABgAA4gaIAAAVIABAAIAQAAQAGAAADgDQADgDAAgFQAAgFgDgDQgDgDgGAAIgQAAIgBABgAgfAqIgBAAIgBgBIAAhSIABAAIABgBIAhAAQAIAAAHADQAFAEAEAFQADAHAAAIQAAAHgDAGQgEAFgGADQgGADgJABIgQAAIgBAAIAAAfIAAABIgBAAgAgQgaIAAAWIABAAIAPAAQAFAAAEgCQADgEAAgFQAAgFgDgEQgEgDgFAAIgPAAIgBABgAh9AqIgBAAIgBgBIAAhSIABAAIABgBIA4AAIABABIAAAOIgBAAIgoAAIgBABIAAATIABAAIAaAAIABABIABABIAAAKIgBABIgBABIgaAAIgBABIAAATIABABIAoAAIABAAIAAAOIgBAAgAiaAqIgDgBIgOghIgBgBIgMAAIgBABIAAAhIAAABIgBAAIgOAAIgBAAIgBgBIAAhSIABAAIABgBIAjAAQAIAAAFADQAGAEAEAFQADAGAAAIQAAAIgEAGQgEAFgIACIAAABIAQAjIAAAAIgBABgAi5gaIAAAVIABAAIAQAAQAFAAADgDQAEgDAAgFQAAgFgEgDQgDgDgFAAIgQAAIgBABgAlZAqIgBAAIgBgBIAAhSIABAAIABgBIAOAAIABABIAAAAIAABEIABABIAoAAIABAAIABABIAAAMIgBABIgBAAgAmiAqIgBAAIgBgBIAAhSIABAAIABgBIAiAAQAIAAAHADQAFAEAEAFQADAHAAAIQAAAHgDAGQgEAFgGADQgGADgJABIgRAAIgBAAIAAAfIAAABIgBAAgAmTgaIAAAWIABAAIAQAAQAFAAAEgCQADgEAAgFQAAgFgDgEQgEgDgFAAIgQAAIgBABgAm/AqIgBgBIgQgcIgBAAIgQAcIgCABIgPAAIgBAAIAAgBIAYgpIAAAAIgZgpQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAPAAIACABIAQAcIABAAIAQgcIABgBIAQAAIABABIAAABIgYAoIAAAAIAYApIAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAgAo1AqIgBAAIAAgBIAAhSIAAAAIABgBIA4AAIABABIAAAOIgBAAIgnAAIgBABIAAATIABAAIAaAAIABABIAAABIAAAKIAAABIgBABIgaAAIgBABIAAATIABABIAnAAIABAAIAAAOIgBAAg");
	this.shape_3.setTransform(82.75,12.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Bg
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ArtB4IAAjvIXbAAIAADvg");
	this.shape_4.setTransform(75,12);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFFFF").ss(1,1,1).p("ALuB4I3bAAIAAjvIXbAAg");
	this.shape_5.setTransform(75,12);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ap6CMIAAkXIT1AAIAAEXg");
	this.shape_6.setTransform(75.0206,11.9905,1.1815,0.8556);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4}]}).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,152,26);


// stage content:
(lib.banner_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Logo
	this.instance = new lib.g_SFULogo("synched",0);
	this.instance.setTransform(18.85,0.1,1,1,0,0,0,0.1,0.1);
	var instanceFilter_1 = new cjs.ColorFilter(0,0,0,1,214,0,42,0);
	this.instance.filters = [instanceFilter_1];
	this.instance.cache(-2,-2,78,41);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({startPosition:0},20).wait(354));
	this.timeline.addTween(cjs.Tween.get(instanceFilter_1).to(new cjs.ColorFilter(1,1,1,1,0,0,0,0), 20).wait(354));

	// Red_Bg_as_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_85 = new cjs.Graphics().p("AgxD6IAAnzIBjAAIAAHzg");
	var mask_graphics_86 = new cjs.Graphics().p("Ai1D6IAAnzIFrAAIAAHzg");
	var mask_graphics_87 = new cjs.Graphics().p("AkzD6IAAnzIJnAAIAAHzg");
	var mask_graphics_88 = new cjs.Graphics().p("AmrD6IAAnzINXAAIAAHzg");
	var mask_graphics_89 = new cjs.Graphics().p("AodD6IAAnzIQ7AAIAAHzg");
	var mask_graphics_90 = new cjs.Graphics().p("AqJD6IAAnzIUTAAIAAHzg");
	var mask_graphics_91 = new cjs.Graphics().p("ArwD6IAAnzIXhAAIAAHzg");
	var mask_graphics_92 = new cjs.Graphics().p("AtRD6IAAnzIajAAIAAHzg");
	var mask_graphics_93 = new cjs.Graphics().p("AusD6IAAnzIdZAAIAAHzg");
	var mask_graphics_94 = new cjs.Graphics().p("AwBD6IAAnzMAgDAAAIAAHzg");
	var mask_graphics_95 = new cjs.Graphics().p("AxQD6IAAnzMAihAAAIAAHzg");
	var mask_graphics_96 = new cjs.Graphics().p("AyZD6IAAnzMAkzAAAIAAHzg");
	var mask_graphics_97 = new cjs.Graphics().p("AzdD6IAAnzMAm6AAAIAAHzg");
	var mask_graphics_98 = new cjs.Graphics().p("A0aD6IAAnzMAo1AAAIAAHzg");
	var mask_graphics_99 = new cjs.Graphics().p("A1SD6IAAnzMAqlAAAIAAHzg");
	var mask_graphics_100 = new cjs.Graphics().p("A2DD6IAAnzMAsIAAAIAAHzg");
	var mask_graphics_101 = new cjs.Graphics().p("A2wD6IAAnzMAtgAAAIAAHzg");
	var mask_graphics_102 = new cjs.Graphics().p("A3WD6IAAnzMAusAAAIAAHzg");
	var mask_graphics_103 = new cjs.Graphics().p("A32D6IAAnzMAvtAAAIAAHzg");
	var mask_graphics_104 = new cjs.Graphics().p("A4QD6IAAnzMAwhAAAIAAHzg");
	var mask_graphics_105 = new cjs.Graphics().p("A4kD6IAAnzMAxJAAAIAAHzg");
	var mask_graphics_106 = new cjs.Graphics().p("A4zD6IAAnzMAxoAAAIAAHzg");
	var mask_graphics_107 = new cjs.Graphics().p("A48D6IAAnzMAx5AAAIAAHzg");
	var mask_graphics_108 = new cjs.Graphics().p("A4/D6IAAnzMAx/AAAIAAHzg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(85).to({graphics:mask_graphics_85,x:325,y:25}).wait(1).to({graphics:mask_graphics_86,x:310.975,y:25}).wait(1).to({graphics:mask_graphics_87,x:297.55,y:25}).wait(1).to({graphics:mask_graphics_88,x:284.75,y:25}).wait(1).to({graphics:mask_graphics_89,x:272.575,y:25}).wait(1).to({graphics:mask_graphics_90,x:261.05,y:25}).wait(1).to({graphics:mask_graphics_91,x:250.125,y:25}).wait(1).to({graphics:mask_graphics_92,x:239.85,y:25}).wait(1).to({graphics:mask_graphics_93,x:230.175,y:25}).wait(1).to({graphics:mask_graphics_94,x:221.125,y:25}).wait(1).to({graphics:mask_graphics_95,x:212.725,y:25}).wait(1).to({graphics:mask_graphics_96,x:204.9,y:25}).wait(1).to({graphics:mask_graphics_97,x:197.75,y:25}).wait(1).to({graphics:mask_graphics_98,x:191.2,y:25}).wait(1).to({graphics:mask_graphics_99,x:185.275,y:25}).wait(1).to({graphics:mask_graphics_100,x:179.95,y:25}).wait(1).to({graphics:mask_graphics_101,x:175.3,y:25}).wait(1).to({graphics:mask_graphics_102,x:171.25,y:25}).wait(1).to({graphics:mask_graphics_103,x:167.775,y:25}).wait(1).to({graphics:mask_graphics_104,x:165,y:25}).wait(1).to({graphics:mask_graphics_105,x:162.8,y:25}).wait(1).to({graphics:mask_graphics_106,x:161.25,y:25}).wait(1).to({graphics:mask_graphics_107,x:160.3,y:25}).wait(1).to({graphics:mask_graphics_108,x:160,y:25}).wait(266));

	// Btn_AD_123
	this.instance_1 = new lib.btn_CTA_AD_123();
	this.instance_1.setTransform(211.55,38.5,1,1,0,0,0,83,25.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn_CTA_AD_123(), 3);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(278).to({_off:false},0).to({x:221.55,alpha:1},22,cjs.Ease.get(0.9)).wait(74));

	// text_03_AD123
	this.instance_2 = new lib.g_txt03AD123("synched",0);
	this.instance_2.setTransform(131.25,12.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(208).to({_off:false},0).to({alpha:1},28,cjs.Ease.get(1)).wait(25).to({startPosition:0},0).to({alpha:0},25,cjs.Ease.get(1)).to({_off:true},2).wait(86));

	// text_02__Ad01
	this.instance_3 = new lib.g_txt02AD1new("synched",0);
	this.instance_3.setTransform(517.5,0.05);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(85).to({_off:false},0).to({x:320},25,cjs.Ease.get(1)).wait(79).to({startPosition:0},0).to({x:517.5},21,cjs.Ease.get(1)).to({_off:true},1).wait(163));

	// Text_01___AD_1_3
	this.instance_4 = new lib.g_txt01AD1("single",0);
	this.instance_4.setTransform(459.15,0);
	var instance_4Filter_2 = new cjs.ColorFilter(0,0,0,1,214,0,42,0);
	this.instance_4.filters = [instance_4Filter_2];
	this.instance_4.cache(-138,2,138,46);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:320},20,cjs.Ease.get(1)).wait(51).to({startPosition:0},0).to({x:460},25,cjs.Ease.get(1)).to({_off:true},1).wait(277));
	this.timeline.addTween(cjs.Tween.get(instance_4Filter_2).to(new cjs.ColorFilter(1,1,1,1,0,0,0,0), 20,cjs.Ease.get(1)).wait(51).to(new cjs.ColorFilter(0,0,0,1,208,0,37,0), 25,cjs.Ease.get(1)).wait(277));

	// Red
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D00025").s().p("A4/D6IAAnzMAx/AAAIAAHzg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(374));

	this.filterCacheList = [];
	this.filterCacheList.push({instance: this.instance, startFrame:1, endFrame:20, x:-2, y:-2, w:78, h:41});
	this.filterCacheList.push({instance: this.instance, startFrame:0, endFrame:0, x:-2, y:-2, w:78, h:41});
	this.filterCacheList.push({instance: this.instance_4, startFrame:1, endFrame:20, x:-138, y:2, w:138, h:46});
	this.filterCacheList.push({instance: this.instance_4, startFrame:0, endFrame:0, x:-138, y:2, w:138, h:46});
	this.filterCacheList.push({instance: this.instance_4, startFrame:71, endFrame:71, x:-138, y:2, w:138, h:46});
	this.filterCacheList.push({instance: this.instance_4, startFrame:72, endFrame:96, x:-138, y:2, w:138, h:46});
	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(160,25,357.5,25);
// library properties:
lib.properties = {
	id: 'C38F8E925B074A239B4A15BB5DD6BAC8',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C38F8E925B074A239B4A15BB5DD6BAC8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;