(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,300,250]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Pic3new = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.g_txt03AD123 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap2B/IAAgTIAQAAQASgBAGgQIAFgSIgHAAIgoh1IgCgCIgMgBIAAgNIA5AAIAAANIgRAAIgCADIAfBcIABAAIAghcIgBgDIgQAAIAAgNIAvAAIAAANIgMABIgDACIgyCTQgFAOgJAHQgHAFgNAAQgKAAgHgCgAGzA4IgCAAQgRATgdAAQgPABgJgKQgLgKAAgRQAAgnAyAAIAhAAIAAgVQAAgbgaAAQgbgBABAjIgWAAIgBgGQABgPAIgLQANgPAdAAQAuAAAAArIgBBFQAAAJAIAAIAHgBIADAIQgJAJgLAAQgTAAAAgUgAF5AkQABAXAXAAQAPAAAJgLQAKgKAAgTIAAgJIgYAAQghAAgBAagAO/AHIAAhpIgCgDIgRgBIAAgMIA8AAIAAAMIgQABIgCADIAABsQABAyAtABQAdAAAMgSQAHgMAAgZIAAhoIgBgDIgSgBIAAgMIA1AAIAAAMIgQABIgCADIAABoQAABFhCAAQhDAAAAhEgAKEA3IAAgyIALAAQACAbANAOQANAQAXAAQATAAALgLQALgLgBgQQABgPgIgIQgHgIgVgEQgkgJgMgHQgRgMAAgYQAAgTALgOQAQgTAhAAQAiAAAVAQIAAAqIgLAAQgFgWgMgLQgMgMgSAAQgPAAgJAKQgIAIAAAOQAAAPAIAIQAKAHAZAFQAhAFAOAPQAMAOAAAUQAAAVgNAOQgSAWgkgBQglAAgZgUgAAEAKQAAglASgSQAOgQAXAAQAaAAANAQQAOAPAAAcIAAAKIhTAAIAAADQAAAwAmAAQATAAARgPIAIAHQgIALgOAHQgNAHgQgBQg4AAAAhBgABYgEQAAgsgdAAQgcAAgBAsIA6AAIAAAAgAh1A8IAAgjIAKAAQACASAMAKQAKAKAOAAQAPAAAHgIQAHgGAAgLQAAgTgbgEQgcgFgJgHQgMgHAAgSQAAgOAKgLQANgOAZAAQAbAAAPAMIAAAgIgJAAQgDgOgLgKQgKgHgLAAQgLgBgGAHQgFAGAAAIQAAAKAGAFQAGAEASADQAbAFAKALQAIAIAAARQAAANgJAMQgOAPgdAAQgaAAgWgPgAs8AKQAAglASgSQAOgQAXAAQAaAAANAQQAOAPAAAcIAAAKIhTAAIAAADQAAAwAmAAQATAAARgPIAIAHQgIALgNAHQgOAHgQgBQg4AAAAhBgArpgEQAAgsgdAAQgcAAgBAsIA6AAIAAAAgAu9AKQgBglATgSQANgQAYAAQAZAAANAQQAOAPABAcIAAAKIhTAAIAAADQAAAwAmAAQATAAARgPIAHAHQgHALgOAHQgOAHgPgBQg4AAAAhBgAtqgEQAAgsgdAAQgcAAgBAsIA6AAIAAAAgAxVA3IAAgyIALAAQADAbANAOQANAQAWAAQAUAAALgLQAKgLAAgQQAAgPgHgIQgHgIgVgEQglgJgMgHQgRgMAAgYQAAgTALgOQARgTAgAAQAjAAAVAQIAAAqIgMAAQgEgWgNgLQgMgMgRAAQgPAAgJAKQgJAIAAAOQAAAPAJAIQAJAHAZAFQAhAFAOAPQAMAOAAAUQAAAVgMAOQgSAWglgBQglAAgZgUgAH2AlIAAhUIgXAAIAAgJQARgCAJgLQAHgJACgUIAKAAIAAAnIAoAAIAAAMIgoAAIAABLQAAARAEAGQADAIAKAAQANAAALgLIAHAHQgPAUgUAAQgkAAABgmgAkPBLIAAgXIgBAAQgOAWgbAAQgpAAAAgoIAAhEQgBgGgEgCIgNgCIAAgKIAlgHIADAAIAABUQAAAQAEAGQAFAMARAAQAQAAAJgMQAJgMAAgQIAAgzQAAgGgFgCIgMgCIAAgKIAkgHIADAAIAABxQAAAHAFABIANADIAAAIIgkAEgAn3AHQAAgcAOgSQAPgWAfAAQA3AAAABDQAAAhgMAQQgOAUggAAQg5AAAAhEgAnXgeQgGANAAAZQAAA3AgAAQAUAAAHgUQAEgMAAgdQAAgygfAAQgTAAgHASgAMbBJIAAgLIASgBIABgCIAAidIgBgCIgSgBIAAgMICFAAIAAArIgLAAQgGgVgGgFQgGgEgVAAIgoAAIAABMIAaAAQATAAAFgEQADgFAEgRIAKAAIAABAIgKAAQgEgQgEgEQgFgFgSAAIgaAAIAABGIACACIARABIAAALgADKBJIAAgLIASgBIACgCIAAhqIgUAAIAAgNIAUAAIAAgbQAAgSAKgLQAKgMASAAQAkAAgBAkIAAADIgVAAQAAgOgDgFQgDgIgKAAQgOAAAAAUIAAAkIAhAAIAAANIghAAIAABqIADACIAUABIAAALgACDBJIAAgLIAQgBIACgCIAAigQAAgIgFAAIgNgEIAAgJIAlgGIADAAIAAC7IACACIAPABIAAALgAjbBJIAAgLIAQgBIADgCIAAhcQAAgHgFgBIgNgDIAAgJIAkgIIADAAIgCAdIABAAQAOgdAeAAQAHAAAIACIgGAXQgIgDgJAAQgPAAgKANQgIANgBAVIAAAzIADACIAOABIAAALg");
	this.shape.setTransform(114.1,19.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.1,7,222,25.799999999999997);


(lib.g_txt02AD3_new = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjlIXIgriHIgEAAIAACHIg8AAIAAk2IA8AAIArCHIAEAAIAAiHIA9AAIAAE2gAnrIXQgjgMABgoIAAjOQgBgoAjgMIBkAAQAiAMAAAoIAADOQAAAogiAMgAnIEdIAAC9IAEAFIAVAAIAFgFIAAi9IgFgEIgVAAgAqBIXIAAhBIAMAAIAAi0IgMAAIAAhBIBfAAIAABBIgOAAIAAC0IAOAAIAABBgAsFIXIAAj1IgxAAIAAhBICoAAIAABBIgyAAIAAD1gAvIIXQgjgMABgoIAAjOQgBgoAjgMIBkAAQAiAMAAAoIAABLIhFAAIAAhDIgFgEIgVAAIgEAEIAAC9IAEAFIAVAAIAFgFIAAhBIBFAAIAABKQAAAogiAMgAw7IXIgGg9IggAAIgGA9IhAAAIAAg0IAnkCIBeAAIAnECIAAA0gAxGGaIgJhiIgEAAIgJBiIAWAAgAHiCbIAAk1ICOAAIAABBIhJAAIAAA4IBEAAIAAA/IhEAAIAAA8IBLAAIAABBgAFeCbIAAj0IgxAAIAAhBICoAAIAABBIgxAAIAAD0gADlCbIgGg9IggAAIgFA9IhBAAIAAg0IAnkBIBeAAIAnEBIAAA0gADaAeIgJhhIgEAAIgJBhIAWAAgAAoCbIAAiwIgCAAIgWBEIgzAAIgVhEIgCAAIAACwIhBAAIAAk1IBLAAIAlBsIAFAAIAjhsIBLAAIAAE1gAjvCbIAAhBIANAAIAAizIgNAAIAAhBIBfAAIAABBIgNAAIAACzIANAAIAABBgAmJCbIAAk1IBEAAIAAD0IBHAAIAABBgAolCbQghgMAAgoIAAjNQAAgoAhgMIBlAAQAhAMAAAoIAABLIhEAAIAAhDIgFgEIgVAAIgFAEIAAC8IAFAFIAVAAIAFgFIAAhBIBEAAIAABKQAAAoghAMgArPCbIgnh5IgIAAIAAB5IhFAAIAAk1ICGAAQAiAMAAAoIAABCQAAAkgdAMIAlBjIAAAsgAr+gVIAaAAIAEgEIAAhFIgEgEIgaAAgAveCbQgigMAAgoIAAjNQAAgoAigMIBkAAQAiAMAAAoIAADNQAAAogiAMgAu7heIAAC8IAFAFIAVAAIAEgFIAAi8IgEgEIgVAAgAyjCbIAAk1ICOAAIAABBIhJAAIAAA8IBFAAIAAA/IhFAAIAAB5gAQCjgIAAk2ICHAAQAhAMAAAoIAADOQAAAoghAMgARHkYIAbAAIADgFIAAi9IgDgEIgbAAgANojgIAAk2IBFAAIAAD1IBHAAIAABBgAMgjgIgnh5IgIAAIAAB5IhFAAIAAk2ICGAAQAiAMAAAoIAABCQAAAlgdAMIAlBjIAAAsgALxmRIAaAAIAEgEIAAhFIgEgEIgaAAgAIRjgQgigMAAgoIAAjOQAAgoAigMIBkAAQAiAMAAAoIAADOQAAAogiAMgAI0naIAAC9IAFAFIAVAAIAEgFIAAi9IgEgEIgVAAgAFojgIgNi8IgFAAIgNC8IhUAAIgikAIAAg2IA9AAIANC4IAEAAIANi4IBUAAIAOC4IAEAAIAOi4IA9AAIAAA2IgiEAgAgOjgIAAk2ICNAAIAABBIhJAAIAAA4IBFAAIAABAIhFAAIAAA8IBLAAIAABBgAhojgIAAh5IgeAAIAAB5IhFAAIAAk2IBFAAIAAB9IAeAAIAAh9IBFAAIAAE2gAlOjgIAAj1IgxAAIAAhBICnAAIAABBIgxAAIAAD1gAoJjgIgriHIgEAAIAACHIg9AAIAAk2IA9AAIArCHIAEAAIAAiHIA8AAIAAE2gArojgIAAhBIANAAIAAi0IgNAAIAAhBIBeAAIAABBIgMAAIAAC0IAMAAIAABBgAvEjgQgigMAAgoIAAgpIBFAAIAAAgIAFAFIAVAAIAEgFIAAhCIgEgEIgnAAIAAg0IAnAAIAEgEIAAg/IgEgEIgVAAIgFAEIAAAhIhFAAIAAgpQAAgoAigMIBkAAQAiAMAAAoIAAA1QAAAhgYAPQAYAOAAAhIAAA6QAAAogiAMgAxcjgIAPhWIgbAAIgOBWIgvAAIAPhWIgTAAIAAg0IAbAAIAGgnIgVAAIAAgzIAeAAIAOhSIAvAAIgOBSIAaAAIAOhSIAvAAIgNBSIASAAIAAAzIgbAAIgHAnIAUAAIAAA0IgdAAIgNBWgAxflqIAaAAIAHgnIgaAAg");
	this.shape.setTransform(121.85,84.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A1QJeIABs6IgBAAIAAmBMAqhAAAIAAG8IoxAAIAAGLIsbAAIAAF0g");
	this.shape_1.setTransform(112.125,83.825);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Small_Text
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ANVA6QAAgBAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIABgNQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAJABQAHABAFgEQAEgEAAgHIAAgBIAAABQgGAEgJAAQgIAAgHgDQgGgFgEgJQgCgFAAgJQABgJACgGQACgIAHgEQAGgGAJAAQAJAAAGAHIAAAAIAAgEIABgBIABgBIAPAAIABABIAAABIAAA5QAAAQgJAHQgKAIgPgBgANdgOQgDACgBAEQgCAEAAAFQABAHABADQABADADACQADADAEAAQAEAAACgDQADgCABgDIABgKIAAgGIgBgDQgBgEgDgCQgDgCgEAAQgDAAgDACgAsrA6QgBgBAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgNQAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIAIABQAIABAEgEQAFgEAAgHIAAgBIgBABQgFAEgJAAQgJAAgGgDQgHgFgDgJQgCgFAAgJQAAgJACgGQADgIAGgEQAHgGAIAAQAKAAAFAHIABAAIAAgEIAAgBIABgBIAPAAIABABIABABIAAA5QAAAQgKAHQgKAIgOgBgAsjgOQgDACgBAEQgCAEAAAFQAAAHABADQABADAEACQADADADAAQAEAAADgDQACgCACgDIABgKIAAgGIgBgDQgCgEgDgCQgCgCgEAAQgDAAgDACgAC4A5IgBAAIgBgBIAAhVIABgBIABgBIAPAAIABABIAAABIAAAFIABAAQAFgIAKAAQAIAAAHAGQAGAEADAJQACAGAAAJQAAAIgCAHQgDAIgGAFQgHAFgJgBQgJABgFgHIgBAAIAAAcIAAABIgBAAgADLgLQgDAFAAAHQAAAIADAFQADAFAGABQAGAAADgGQADgEAAgJQgBgHgCgFQgDgFgGAAQgGAAgDAFgAPMAuQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAEgdQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIANAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIgIAeQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgARUAbQgHgHgBgOIAAggQABgOAHgHQAJgIAOAAQANAAAIAIQAJAHAAAOIAAAgQAAAOgJAHQgIAIgNAAQgOAAgJgIgARigkQgEADAAAHIAAAhQAAAGAEADQACADAHABQAFgBAEgDQADgDAAgGIAAghQAAgHgDgDQgEgDgFgBQgHABgCADgAOYAgQgFgDgEgEQgDgEAAgGIAAgBIAAgBIABAAIAOAAIABAAIABABQAAADACACQADACAFAAQAFAAACgBQADgCAAgDQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQgCgCgGAAIgJgEQgIgCgFgEQgFgEAAgHQAAgJAIgFQAGgGANAAQAHAAAGACQAHADADAEQADAFABAGIgBABIgBABIgOAAIgBgBIAAgBQAAgDgDgBQgDgCgEAAQgEAAgDABQgDABAAADQAAABAAABQAAAAABABQAAAAAAAAQABABAAAAIAJADIAIABQAJAEAEADQAGAEAAAHQgBAKgHAFQgHAGgMgBQgJAAgHgCgAIbAeQgFgFgBgKQABgJAGgFQAHgFANAAIANAAIABgBIAAgCQgBgEgCgCQgCgDgGAAQgDAAgDACQgDABAAACIgCABIgPgCIgCgBQABgFADgEQAEgFAGgCQAHgCAHgBQAIAAAGADQAHAEADAEQAEAFAAAGIAAAqIAAABIgBAAIgPAAIgBAAIAAgBIAAgEIgBAAIAAAAQgGAGgLAAQgKAAgHgEgAIrAIQgEACAAAEQAAAEADACQACACAEAAQAGAAADgDQAFgEAAgEIAAgFIgBAAIgJAAQgGAAgDACgAFLAeQgHgFgDgKQgCgFgBgJQABgHACgHQADgJAHgEQAIgGAKAAQAKABAHAFQAIAFADAIIABAEIAAABQgBAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAIgPACIgBgBIgBgCQAAgEgDgCQgEgCgDAAQgFAAgDACQgCACgBAEIgCAJIACAKQABAEACACQADACAFABQADgBAEgCQACgCABgDIAAgBQABgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAPADIABABIAAADQgDAJgIAFQgHAEgKAAQgKAAgIgEgAEAAeQgGgFAAgKQAAgJAHgFQAHgFANAAIAMAAIABgBIAAgCQAAgEgCgCQgDgDgGAAQgDAAgDACQgCABgBACIgBABIgQgCIgCgBQABgFAEgEQADgFAHgCQAGgCAHgBQAJAAAGADQAHAEADAEQAEAFgBAGIAAAqIAAABIgBAAIgPAAIgBAAIAAgBIAAgEIgBAAIAAAAQgFAGgMAAQgKAAgGgEgAEPAIQgDACAAAEQAAAEACACQADACAEAAQAGAAADgDQAEgEAAgEIAAgFIgBAAIgJAAQgGAAgDACgAhsAdQgHgGgDgJQgCgGAAgHQAAgGACgHQADgIAHgGQAHgFALgBQALABAHAFQAHAFADAJQACAHAAAGQAAAHgCAFQgCALgIAFQgHAGgLgBQgKABgIgGgAhhgNQgDACgBAEIgBAIIABAJQABAEADADQADACAEABQAFgBACgCQADgDABgEIABgJIgBgIQgBgEgDgCQgDgDgEAAQgEAAgDADgAkGAeQgGgFAAgKQAAgJAHgFQAHgFAMAAIANAAIABgBIAAgCQAAgEgDgCQgCgDgGAAQgDAAgCACQgDABgBACIgCABIgPgCIgCgBQABgFAEgEQAEgFAGgCQAGgCAHgBQAIAAAHADQAGAEAEAEQAEAFAAAGIAAAqIgBABIgBAAIgOAAIgBAAIgBgBIAAgEIAAAAIgBAAQgFAGgMAAQgKAAgGgEgAj3AIQgDACAAAEQAAAEACACQADACAEAAQAFAAAEgDQAEgEAAgEIAAgFIgBAAIgJAAQgFAAgEACgAlBAeQgIgFgDgKQgBgFAAgJQAAgHABgHQADgJAIgEQAHgGAKAAQAKABAIAFQAIAFACAIIABAEIAAABQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAIgOACIgCgBIgBgCQgBgEgCgCQgDgCgFAAQgDAAgEACQgCACgCAEIAAAJIAAAKQABAEADACQAEACADABQAFgBADgCQACgCABgDIAAgBQABgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAOADIABABIgBADQgDAJgHAFQgIAEgKAAQgKAAgHgEgAmLAdQgGgGAAgKIAAgqIAAgBIACgBIAOAAIABABIAAAmQAAAFAEADQACADAFABQAEAAADgEQADgCABgEIAAgnIAAgBIABgBIAOAAIACABIAAABIAAA9IAAABIgCAAIgOAAIgBAAIAAgBIAAgEIgBAAQgGAGgKAAQgJAAgHgFgAnNAeQgHgFgDgJQgCgHAAgIQAAgIADgGQACgJAHgEQAFgGAKAAQAJABAFAGIABABIAAgBIAAgcIABAAIAPAAIABAAIAAABIAABUIAAABIgBAAIgPAAIgBAAIAAgFIAAAAIgBAAQgFAGgKAAQgIAAgGgEgAnDgLQgDAFgBAIQAAAHADAFQADAFAHABQAFgBADgFQACgFABgIQgBgHgCgFQgDgFgFAAQgHAAgCAFgAqjAeQgHgFgDgJQgDgHAAgJQAAgHACgFQADgJAHgFQAIgFAKgBQAMABAHAHQAIAHACAMIAAAKIgBABIgnAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAAAABAAIABAGQADAHAKAAQAIgBAFgGIABgBIABABIAJAJIABAAIgBABQgEAGgGACQgIADgHAAQgLAAgIgEgAqdgIIgBADIABABIAWAAQABAAgBgBIAAgDQgBgEgDgCQgEgCgDAAQgJAAgCAIgAv1AgQgGgDgEgEQgDgEAAgGIAAgBIABgBIAAAAIAPAAIABAAIAAABQAAADADACQADACAFAAQAEAAADgBQACgCAAgDQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQgCgCgFAAIgJgEQgJgCgEgEQgGgEABgHQAAgJAHgFQAHgGAMAAQAIAAAGACQAGADAEAEQADAFAAAGIAAABIgBABIgOAAIgBgBIgBgBQAAgDgCgBQgDgCgFAAQgEAAgDABQgCABAAADQAAABAAABQAAAAAAABQAAAAABAAQAAABABAAIAJADIAHABQAJAEAFADQAFAEAAAHQAAAKgIAFQgHAGgMgBQgJAAgGgCgAw4AeQgIgFgDgJQgDgHAAgJQAAgHACgFQADgJAHgFQAIgFAKgBQAMABAIAHQAHAHACAMIAAAKIgBABIgnAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAAAAAAAIACAGQADAHAKAAQAIgBAFgGIABgBIABABIAJAJIABAAIgBABQgEAGgGACQgIADgHAAQgLAAgHgEgAwzgIIgBADIABABIAWAAQAAAAAAgBIAAgDQgBgEgEgCQgDgCgDAAQgJAAgCAIgAGOAfQgEgEAAgJIAAghIgBgBIgHAAIgBAAIgBgBIAAgMIABgBIABgBIAHAAIABAAIAAgPIAAgBIABgBIAOAAIABABIABABIAAAPIAAAAIAMAAIABABIAAAOIgBAAIgMAAIAAABIAAAaQAAADABACQACADADAAIAFAAIABAAIAAABIAAAMQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgIABQgKAAgGgDgAi7AfQgFgEAAgJIAAghIgBgBIgHAAIgBAAIAAgBIAAgMIAAgBIABgBIAHAAIABAAIAAgPIABgBIABgBIANAAIABABIABABIAAAPIABAAIAMAAIABABIAAAOIgBAAIgMAAIgBABIAAAaQAAADACACQACADADAAIAFAAIABAAIAAABIAAAMQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAAAAAIgIABQgKAAgGgDgAUDAhIgBAAIgBgBIAAgUIAAgBIgnAAIgBAAIAAgBIAAgKIAAgCIAWgyIADgBIAPAAIACAAIAAABIgWAvIAAABIAUAAIAAgBIAAgPIABgBIABgBIAOAAIACABIAAABIAAAPIABABIAFAAIABAAIABABIAAANIgBABIgBAAIgFAAIgBABIAAAUIAAABIgCAAgASVAhIgBAAIgBgBIAAgLIABgCIAcgeQAMgMAAgHQAAgEgEgDQgCgDgGAAQgFAAgDADQgDADAAAFIAAADIgBABIAAABIgQAAIgBgBIAAgBIAAgGQAAgGAFgGQAEgFAGgDQAHgDAHAAQAJABAHADQAHADADAGQAEAGAAAGQAAAFgDAGQgDAGgFAGIgXAZIgBAAIAjAAIABABIABABIAAAMIgBABIgBAAgAQHAhIgBAAIgBgBIAAgLIACgCIAcgeQAKgMABgHQAAgEgDgDQgEgDgEAAQgGAAgDADQgDADAAAFIAAADIgBABIgBABIgOAAIgCgBIAAgBIAAgGQABgGAEgGQADgFAHgDQAGgDAJAAQAIABAHADQAGADAEAGQADAGABAGQgBAFgCAGQgCAGgGAGIgYAZIAAAAIAjAAIABABIAAABIAAAMIAAABIgBAAgAMrAhIgBAAIgBgBIAAglQAAgEgCgEQgDgDgFAAQgFAAgCADQgDAEAAAEIAAAlIAAABIgBAAIgPAAIgBAAIgBgBIAAg9IABgBIABgBIAPAAIABABIAAABIAAAFIABAAQAEgHALgBQAKABAGAGQAGAGABALIAAAoIgBABIgBAAgALlAhIgBAAIgBgBIAAg9IABgBIABgBIAPAAIABABIAAABIAAA9IAAABIgBAAgALJAhIgCgBIgMgdIAAAAIgBAAIgIAKIAAATIAAABIgBAAIgPAAIgBAAIgBgBIAAhUIABgBIABAAIAPAAIABAAIAAABIAAAqIABAAIARgUIACgBIARAAIABABIAAABIgRAVIAAABIATAmIAAABQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAgAKEAhIgCAAIAAgBIAAglQAAgEgDgEQgDgDgFAAQgEAAgDADQgCAEgBAEIAAAlIAAABIgBAAIgPAAIgBAAIgBgBIAAg9IABgBIABgBIAPAAIABABIAAABIAAAFIABAAQAFgHALgBQAKABAGAGQAGAGAAALIAAAoIgBABIgBAAgAH+AhIgCgBIgQgiIAAAAIgNAAIAAAAIAAAiIgBABIgBAAIgPAAIgBAAIAAgBIAAhUIAAgBIABAAIAkAAQAJAAAGADQAGADADAGQADAGAAAIQAAAJgEAFQgEAGgHADIgBABIARAiIABABQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAgAHfgmIAAAWIAAABIARAAQAFgBADgDQAEgDAAgFQAAgFgEgDQgDgEgFAAIgRAAIAAABgACZAhIAAAAIgBgBIAAglQAAgFgCgDQgEgDgDAAQgFAAgDADQgDADABAFIAAAlIgBABIgBAAIgPAAIgBAAIAAgBIAAglQgBgFgCgDQgDgDgEAAQgEAAgDADQgDACAAAEIAAAnIAAABIgCAAIgOAAIgBAAIgBgBIAAg9IABgBIABgBIAOAAIACABIAAABIAAAGIABAAQAFgJAKAAQAHAAAFADQAFADACAFIABAAQADgFAEgDQAFgDAGAAQAKAAAFAHQAGAFAAAMIAAAoIAAABIgBAAgAAuAhIgBAAIAAgBIAAhUIAAgBIABAAIAQAAIABAAIAAABIAABUIAAABIgBAAgAgIAhIgBAAIgBgBIAAglQAAgEgDgEQgCgDgFAAQgFAAgDADQgCAEAAAEIAAAlIgBABIgBAAIgPAAIgBAAIAAgBIAAg9IAAgBIABgBIAPAAIABABIABABIAAAFIAAAAQAFgHAKgBQALABAEAGQAHAGAAALIAAAoIAAABIgCAAgAiVAhIgBAAIAAgBIAAg9IAAgBIABgBIAPAAIABABIABABIAAA9IgBABIgBAAgAoeAhIgBAAIgBgBIAAhUIABgBIABAAIA6AAIABAAIAAABIAAAMIAAABIgBAAIgpAAIgBABIAAATIABACIAbAAIABAAIAAAOIgBAAIgbAAIgBABIAAAUIABAAIApAAIABABIAAABIAAAMIAAABIgBAAgAppAhIgBAAIAAgBIAAg9IAAgBIABgBIAPAAIABABIABABIAAAGIAAAAQAGgIAJAAQAEAAADABIABACIgEAPQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAgBIgEAAIgEAAQgEAAgDADQgDAEAAAEIAAAiIgBABIgBAAgArLAhIgBAAIgBgBIAAglQAAgEgDgEQgCgDgFAAQgEAAgEADQgCAEAAAEIAAAlIAAABIgBAAIgQAAIgBAAIAAgBIAAhUIAAgBIABAAIAQAAIABAAIAAABIAAAcIAAAAQAGgHAKgBQAKABAGAGQAHAGgBALIAAAoIAAABIgCAAgAtXAhIgBAAIAAgBIAAg9IAAgBIABgBIAPAAIABABIABABIAAA9IgBABIgBAAgAt3AhIgBAAIAAgBIAAgiIgBgBIgcAAIAAABIAAAiIAAABIgBAAIgQAAIgBAAIAAgBIAAhUIAAgBIABAAIAQAAIABAAIAAABIAAAhIAAACIAcAAIABgCIAAghIAAgBIABAAIAPAAIABAAIABABIAABUIgBABIgBAAgAxhAhIgBAAIgBgBIAAglQABgFgDgDQgDgDgEAAQgEAAgEADQgCADAAAFIAAAlIAAABIgBAAIgQAAIgBAAIAAgBIAAglQAAgFgCgDQgDgDgFAAQgEAAgDADQgCACAAAEIAAAnIgBABIgBAAIgPAAIgBAAIAAgBIAAg9IAAgBIABgBIAPAAIABABIABABIAAAGIAAAAQAFgJALAAQAHAAAEADQAFADADAFIAAAAQADgFAFgDQAEgDAHAAQAJAAAGAHQAGAFgBAMIAAAoIAAABIgBAAgAzLAhIgCAAIAAgBIAAg9IAAgBIACgBIAOAAIABABIABABIAAA9IgBABIgBAAgA0AAhIgBAAIgBgBIAAhGIgBgBIgWAAIAAAAIgBgBIAAgMIABgBIAAAAIBAAAIABAAIAAABIAAAMIAAABIgBAAIgWAAIgBABIAABGIgBABIgBAAgALlgoQgDgDAAgFQAAgEADgDQADgDAEAAQAFAAADADQACADAAAEQAAAFgCADQgDACgFAAQgDAAgEgCgAiUgoQgDgDAAgFQAAgEADgDQACgDAFAAQAEAAADADQADADAAAEQAAAFgDADQgDACgEAAQgEAAgDgCgAtXgoQgCgDAAgFQAAgEACgDQADgDAFAAQAEAAADADQACADABAEQgBAFgCADQgDACgEAAQgFAAgDgCgAzLgoQgDgDAAgFQAAgEADgDQADgDAEAAQAEAAADADQADADAAAEQAAAFgDADQgDACgEAAQgEAAgDgCg");
	this.shape_2.setTransform(135.05,178.75);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24,23.3,289.8,161.29999999999998);


(lib.g_txt01AD13_new = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AQdF7IAAlSICcAAIAABGIhQAAIAAA9IBLAAIAABHIhLAAIAABCIBSAAIAABGgANzF7QgkgNgBgrIAAjiQABgrAkgNIBvAAQAkANAAArIAAA5IhLAAIAAgvIgFgFIgYAAIgEAFIAADOIAEAFIAYAAIAFgFIAAg9IgTAAIAAhGIBeAAIAACNQAAArgkANgAL1F7IgviTIgEAAIAACTIhCAAIAAlSIBCAAIAvCUIAEAAIAAiUIBDAAIAAFSgAInF7IgFhCIgkAAIgGBCIhHAAIAAg5IArkZIBnAAIAqEZIAAA5gAIbDzIgJhrIgFAAIgJBrIAXAAgAFUF7IAAiDIghAAIAACDIhLAAIAAlSIBLAAIAACIIAhAAIAAiIIBLAAIAAFSgAA+F7QglgNAAgrIAAjiQAAgrAlgNIBuAAQAlANgBArIAABSIhLAAIAAhIIgEgFIgYAAIgFAFIAADOIAFAFIAYAAIAEgFIAAhHIBLAAIAABRQABArglANgAjhF7IAAlSICbAAIAABGIhPAAIAAA9IBLAAIAABHIhLAAIAABCIBSAAIAABGgAlwF7IAAkMIg2AAIAAhGIC3AAIAABGIg2AAIAAEMgAn2F7IgFhCIgkAAIgGBCIhHAAIAAg5IArkZIBnAAIAqEZIAAA5gAoCDzIgJhrIgFAAIgJBrIAXAAgAsbF7IAAlSICbAAIAABGIhQAAIAAA9IBMAAIAABHIhMAAIAABCIBSAAIAABGgAtqF7IgsiDIgIAAIAACDIhLAAIAAlSICTAAQAkANAAArIAABIQABApggAOIAoBsIAAAvgAueC6IAcAAIAGgEIAAhLIgGgFIgcAAgAyTF7QglgNABgrIAAjiQgBgrAlgNIBuAAQAlANAAArIAABSIhLAAIAAhIIgFgFIgXAAIgFAFIAADOIAFAFIAXAAIAFgFIAAhHIBLAAIAABRQAAArglANgAMYgoIAAlSICcAAIAABGIhQAAIAABCIBLAAIAABHIhLAAIAACDgAJwgoIAAlSIBLAAIAAEMIBOAAIAABGgAG7goIAAlSICcAAIAABGIhQAAIAAA9IBLAAIAABHIhLAAIAABCIBSAAIAABGgAEUgoQglgNAAgrIAAhDIBLAAIAAA5IAFAFIAXAAIAFgFIAAgzIgEgHIhNgjQgRgHgGgNQgEgKAAgVIAAhIQAAgrAlgNIBtAAQAmANgBArIAAA/IhLAAIAAg1IgFgFIgXAAIgFAFIAAAxIAGAIIBMAeQAQAHAGANQAEAKAAAWIAABNQABArgmANgACigoIgriDIgIAAIAACDIhMAAIAAlSICUAAQAkANAAArIAABIQAAApggAOIApBsIAAAvgABvjpIAcAAIAFgEIAAhLIgFgFIgcAAgAiAgoQgmgNABgrIAAkaIBLAAIAAEQIAFAFIATAAIAEgFIAAkQIBKAAIAAEaQAAArgjANgAlPgoQglgNAAgrIAAjiQAAgrAlgNIBuAAQAkANAAArIAADiQAAArgkANgAkpk4IAADOIAFAFIAXAAIAGgFIAAjOIgGgFIgXAAgAoKgoIAAiFIg4iUIAAg5IBGAAIAVB0IAFAAIAVh0IBHAAIAAA5Ig5CUIAACFgAs5goIAAlSICcAAIAABGIhQAAIAAA9IBLAAIAABHIhLAAIAABCIBSAAIAABGgAvugoIAAlSICcAAIAABGIhQAAIAAA9IBLAAIAABHIhLAAIAABCIBSAAIAABGgAyVgoQgkgNAAgrIAAhDIBKAAIAAA5IAGAFIAXAAIAFgFIAAgzIgFgHIhNgjQgRgHgFgNQgFgKABgVIAAhIQAAgrAkgNIBuAAQAlANAAArIAAA/IhLAAIAAg1IgFgFIgXAAIgGAFIAAAxIAHAIIBLAeQARAHAFANQAFAKAAAWIAABNQAAArglANg");
	this.shape.setTransform(124,43.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3,5.8,242.1,75.8);


(lib.g_SFULogo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// icon
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiWBIQgLgCgNgGQAEgIACgNQAIAHAHADQAKAFAMAAQANAAAHgGQAIgHAAgLQAAgKgLgIQgFgEgOgGQgOgGgGgDQgOgKAAgTQAAgRALgLQAMgMAVAAQAJAAAMADIANAEIgDAIIgDALQgKgHgJgCQgHgDgHAAQgJAAgGAGQgGAFAAAJQAAAKAIAHIAbAPQATAIAGAJQAFAIAAAKQAAAOgKAMQgNASgdAAgABMA/QgIgGgFgHQgDgGgBgFIgBgVIgChYIANABIAMgBIgCATIgBA/IABAWQABAFADAEQAJANAZAAQAQAAAKgGIAIgHQAEgEAAgHIABgYIAAggIgBgeIgBgQIALABIAKgBIgBBPQAAAZgDALQgEAKgLAIQgOAJgaAAQgbAAgNgJgAgqBGIgLABIACgUIgBh5IA8ABIAQgBIgBAKIAAAKIgJgBIgsgBIAAAqIAZAAQANAAALgCIgBALIABAJIgxgCIAAASQAAAcABATg");
	this.shape.setTransform(56.0483,28.3567,1.1828,1.1827);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#992932").s().p("AlRCpIAAlRIKjAAIAAFRg");
	this.shape_1.setTransform(39.9916,19.9893,1.1828,1.1827);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,80,40);


(lib.g_arrow = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C92539").s().p("ABAC+IAAj9Ij9AAIAAh+IF7AAIAAF7g");
	this.shape.setTransform(19,19);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,38,38);


(lib.btn_CTA_AD_123 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgXA7QgLgEgGgJQgFgIAAgMIAAgDIAAgCIACgBIAUAAIACABIAAACIAAACQAAAHAHAFQAGAFALAAQAJAAAFgEQAEgEAAgGQAAgEgDgDQgCgDgFgCIgPgGQgMgEgIgFQgIgDgGgHQgGgIAAgKQAAgLAGgIQAFgIAKgFQAKgEANAAQAMAAALAFQALAFAGAIQAFAJAAALIAAADIAAACIgCAAIgUAAIgCAAIAAgCIAAgBQAAgIgGgFQgHgFgJAAQgJAAgEADQgFAEAAAGQAAAFADADQACADAGACIAQAHIAUAIQAHACAGAHQAFAHAAAMQAAAQgMAKQgMAKgVAAQgNAAgLgFg");
	this.shape.setTransform(199.175,21.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AAeA+IgCAAIAAgCIAAhNIgBgBIgBAAIgSAdQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgJAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBAAIgTgdIAAAAIgBABIAABNIAAACIgCAAIgVAAIgBAAIgBgCIAAh3IABgCIABAAIAVAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIAaAqQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAbgqQAAAAABAAQAAgBAAAAQABAAAAAAQAAAAABAAIAVAAIABAAIABACIAAB3IgBACIgBAAg");
	this.shape_1.setTransform(187.575,21.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AAeA+QAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgFgSIgBgBIgrAAIgBABIgFASQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgXAAIgCAAIAAgCIAnh4QAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAbAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAnB4IAAABQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAgAAAgeIgPA0QAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAfAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIgQg0IAAgBg");
	this.shape_2.setTransform(175.275,21.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AAWA+QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgVgyIgCAAIgQAAIgBAAIAAAxIgBACIgBAAIgVAAIgBAAIgBgCIAAh3IABgCIABAAIAyAAQAMAAAIAEQAJAFAEAIQAFAJAAALQAAAMgGAJQgGAIgLADIgBABIAZAzIAAABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAgUgnIAAAfIABAAIAWAAQAHAAAGgEQAEgFAAgHQAAgHgEgEQgGgFgHAAIgWAAIgBABg");
	this.shape_3.setTransform(164.1,21.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("AgXA6QgKgFgHgKQgFgKAAgNIAAgnQAAgNAFgKQAHgKAKgFQALgGAMAAQAOAAAKAGQAKAFAHAJQAFAJAAALIAAACIAAABIgCABIgVAAIgBgBIgBgBIAAgBQAAgIgGgGQgFgFgKAAQgIAAgGAGQgGAGAAAJIAAApQAAAJAGAGQAGAGAJAAQAJAAAGgFQAFgFABgIIAAgIIgBgBIgUAAIgBgBIgBgBIAAgQIABgBIABgBIArAAIACABIAAABIAAAXQAAANgFAKQgHAKgKAFQgKAGgOAAQgMAAgLgGg");
	this.shape_4.setTransform(153,21.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AgYA6QgKgGgGgJQgGgLAAgOIAAgkQAAgNAGgLQAGgKAKgGQALgFANAAQAOAAALAFQAKAGAGAKQAGALAAANIAAAkQAAAOgGALQgGAJgKAGQgLAGgOAAQgNAAgLgGgAgPgjQgGAGAAALIAAAlQAAALAGAGQAGAHAJAAQAKAAAGgHQAGgGAAgLIAAglQAAgLgGgGQgGgGgKgBQgJABgGAGg");
	this.shape_5.setTransform(142.025,21.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AAWA+QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgWgyIgBAAIgQAAIgBAAIAAAxIAAACIgCAAIgVAAIgCAAIAAgCIAAh3IAAgCIACAAIAyAAQAMAAAIAEQAJAFAFAIQAEAJAAALQAAAMgGAJQgGAIgLADIAAABIAXAzIABABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgAgUgnIAAAfIABAAIAWAAQAIAAAEgEQAFgFAAgHQAAgHgFgEQgEgFgIAAIgWAAIgBABg");
	this.shape_6.setTransform(131.3,21.525);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AgrA+IgBAAIgBgCIAAh3IABgBIABgCIAyAAQALABAJAEQAJAFAFAJQAFAJAAAMQAAALgFAIQgFAIgJAEQgKAFgLAAIgZAAIgBABIAAAtIAAACIgCAAgAgUgmIAAAgIABABIAWAAQAIAAAFgFQAFgFAAgHQAAgIgFgFQgFgEgIAAIgWAAIgBABg");
	this.shape_7.setTransform(120.575,21.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgoA+IgCAAIAAgCIAAh3IAAgCIACAAIBRAAIABAAIABACIAAARIgBACIgBAAIg5AAIgBABIAAAcIABABIAlAAIABAAIABACIAAAQIgBABIgBABIglAAIgBABIAAAdIABABIA5AAIABAAIABACIAAARIgBACIgBAAg");
	this.shape_8.setTransform(106.525,21.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAWA+QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAIgUgyIgBAAIgRAAIgBAAIAAAxIAAACIgCAAIgVAAIgCAAIAAgCIAAh3IAAgCIACAAIAyAAQALAAAJAEQAIAFAGAIQAEAJAAALQAAAMgGAJQgGAIgLADIgBABIAYAzIABABQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAgAgUgnIAAAfIABAAIAWAAQAHAAAGgEQAEgFAAgHQAAgHgEgEQgGgFgHAAIgWAAIgBABg");
	this.shape_9.setTransform(95.9,21.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AgYA6QgKgGgGgJQgGgLAAgOIAAgkQAAgNAGgLQAGgKAKgGQALgFANAAQAOAAALAFQAKAGAGAKQAGALAAANIAAAkQAAAOgGALQgGAJgKAGQgLAGgOAAQgNAAgLgGgAgPgjQgGAGAAALIAAAlQAAALAGAGQAGAHAJAAQAKAAAGgHQAGgGAAgLIAAglQAAgLgGgGQgGgGgKgBQgJABgGAGg");
	this.shape_10.setTransform(84.675,21.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AgoA+IgCAAIAAgCIAAh3IAAgCIACAAIAVAAIABAAIABACIAABjIABABIA5AAIACAAIAAACIAAARIAAACIgCAAg");
	this.shape_11.setTransform(74.4,21.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("AgrA+IgBAAIgBgCIAAh3IABgBIABgCIAyAAQALABAJAEQAJAFAFAJQAFAJAAAMQAAALgFAIQgFAIgJAEQgKAFgLAAIgZAAIgBABIAAAtIAAACIgCAAgAgUgmIAAAgIABABIAWAAQAIAAAFgFQAFgFAAgHQAAgIgFgFQgFgEgIAAIgWAAIgBABg");
	this.shape_12.setTransform(63.975,21.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AAaA+QAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgXgpQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIgXApQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgWAAIgCAAIAAgCIAjg8IAAAAIgjg7IAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAXAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAXApQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIAXgpQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAXAAIACAAIgBACIgiA7IAAAAIAiA8IABABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_13.setTransform(52.8208,21.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AgoA+IgCAAIAAgCIAAh3IAAgCIACAAIBRAAIABAAIABACIAAARIgBACIgBAAIg5AAIgBABIAAAcIABABIAlAAIABAAIABACIAAAQIgBABIgBABIglAAIgBABIAAAdIABABIA5AAIABAAIABACIAAARIgBACIgBAAg");
	this.shape_14.setTransform(42.275,21.525);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AhFBiIBhhiIhhhhIAVgVIB2B2Ih2B3g");
	this.shape_15.setTransform(20.475,20.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhFBiIBhhiIhhhhIAVgVIB2B2Ih2B3g");
	this.shape_16.setTransform(20.475,20.475);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AC7A6QgLgGgFgJQgGgLAAgOIAAgkQAAgNAGgLQAFgKALgGQALgFANAAQAPAAAKAFQALAGAGAKQAFALAAANIAAAkQAAAOgFALQgGAJgLAGQgKAGgPAAQgNAAgLgGgADEgjQgGAGAAALIAAAlQAAALAGAGQAGAHAJAAQAKAAAGgHQAGgGAAgLIAAglQAAgLgGgGQgGgGgKgBQgJABgGAGgAmCA6QgKgGgGgJQgGgLAAgOIAAgkQAAgNAGgLQAGgKAKgGQALgFAOAAQAOAAALAFQAKAGAGAKQAGALAAANIAAAkQAAAOgGALQgGAJgKAGQgLAGgOAAQgOAAgLgGgAl5gjQgGAGAAALIAAAlQAAALAGAGQAGAHAKAAQAKAAAGgHQAGgGAAgLIAAglQAAgLgGgGQgGgGgKgBQgKABgGAGgAL3A7QgLgEgGgJQgFgJAAgLIAAgEIAAgBIACgBIAUAAIACABIAAABIAAADQAAAHAHAFQAGAFAMAAQAJAAAFgEQAEgEAAgGQAAgEgDgDQgCgDgFgCIgQgHQgMgDgIgFQgIgDgGgHQgGgIAAgKQAAgMAGgHQAFgJAKgEQAKgEANAAQANAAALAFQALAFAGAIQAFAJAAALIAAADIAAACIgCAAIgUAAIgCAAIAAgCIAAgCQAAgHgGgFQgHgGgKAAQgJABgEADQgFAEAAAGQAAAFADADQACACAGADIARAHIAUAIQAHACAGAHQAFAHAAAMQAAAQgMAKQgMAKgVAAQgOgBgLgEgAEpA6QgKgGgGgJQgGgLAAgNIAAgmQAAgOAGgJQAGgKAKgGQALgFANAAQAOAAAKAFQALAGAGAJQAFAJAAALIAAABIAAACIgCABIgVAAIgBgBIgBgCIAAAAQAAgIgFgGQgGgFgKgBQgJAAgGAHQgGAFAAAKIAAAoQAAAKAGAGQAHAGAJAAQAKAAAFgFQAGgFAAgIIAAgIIgBgBIgUAAIgCgBIAAgCIAAgPIAAgCIACAAIArAAIACAAIAAACIAAAWQAAAOgFAKQgGAKgLAFQgKAFgOABQgNgBgLgFgAK5A+IgCAAIAAgCIAAhNIgBgBIgBAAIgSAcQAAABgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBgBIgTgcIAAAAIgBABIAABNIAAACIgCAAIgVAAIgBAAIgBgCIAAh4IABgBIABAAIAVAAQABAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAIAaAqQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAIAbgqQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAABAAIAVAAIABAAIABABIAAB4IgBACIgBAAgAI+A+QAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgFgSIgBgBIgsAAIgBABIgFASQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXAAIgCAAIAAgCIAnh4QAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAcAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAnB4IAAABQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAgAIfgfIgPA0QAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAgAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIgQg0IAAAAgAHGA+QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgWgyIgBgBIgRAAIgBABIAAAxIAAACIgCAAIgVAAIgBAAIgBgCIAAh4IABgBIABAAIAzAAQAMAAAIAEQAJAEAFAJQAEAJAAALQAAAMgGAIQgGAJgLADIAAABIAYAzIAAABQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAGbgnIAAAfIABAAIAXAAQAIAAAFgFQAEgEAAgHQAAgHgEgEQgFgFgIAAIgXAAIgBABgAB+A+QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgWgyIgBgBIgRAAIgBABIAAAxIAAACIgCAAIgVAAIgBAAIgBgCIAAh4IABgBIABAAIAzAAQAMAAAIAEQAJAEAFAJQAEAJAAALQAAAMgGAIQgGAJgLADIAAABIAYAzIAAABQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgABTgnIAAAfIABAAIAXAAQAIAAAFgFQAEgEAAgHQAAgHgEgEQgFgFgIAAIgXAAIgBABgAguA+IgBAAIgBgCIAAh4IABgBIABgBIAyAAQALAAAJAFQAJAFAFAJQAFAJAAALQAAALgFAIQgFAIgJAFQgKAFgLgBIgZAAIgBACIAAAtIAAACIgCAAgAgXgnIAAAgIABABIAWAAQAIAAAFgEQAFgFAAgIQAAgHgFgFQgFgFgIAAIgWAAIgBABgAi4A+IgBAAIgBgCIAAh4IABgBIABAAIBTAAIABAAIABABIAAASIgBABIgBABIg7AAIgBABIAAAcIABABIAmAAIACAAIABACIAAAQIgBABIgCABIgmAAIgBAAIAAAdIABABIA7AAIABABIABACIAAARIgBACIgBAAgAjjA+QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgWgyIgBgBIgRAAIgBABIAAAxIAAACIgCAAIgVAAIgBAAIgBgCIAAh4IABgBIABAAIAzAAQAMAAAIAEQAJAEAFAJQAEAJAAALQAAAMgGAIQgGAJgLADIAAABIAYAzIAAABQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAkOgnIAAAfIABAAIAXAAQAIAAAFgFQAEgEAAgHQAAgHgEgEQgFgFgIAAIgXAAIgBABgAn5A+IgBAAIgBgCIAAh4IABgBIABAAIAVAAIACAAIAAABIAABjIABABIA6AAIACABIAAACIAAARIAAACIgCAAgApkA+IgBAAIgBgCIAAh4IABgBIABgBIAzAAQALAAAJAFQAJAFAFAJQAFAJAAALQAAALgFAIQgFAIgJAFQgKAFgLgBIgaAAIgBACIAAAtIAAACIgCAAgApNgnIAAAgIABABIAXAAQAIAAAFgEQAFgFAAgIQAAgHgFgFQgFgFgIAAIgXAAIgBABgAqNA+QgBAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgXgpQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIgXApQAAAAgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgWAAIgCAAIAAgCIAig8IAAAAIgig7IAAgBQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAWAAQABAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAIAXApQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAXgpQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAABAAIAWAAIACAAIAAACIgjA7IAAAAIAjA9QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAs6A+IgCAAIAAgCIAAh4IAAgBIACAAIBSAAIABAAIABABIAAASIgBABIgBABIg6AAIgBABIAAAcIABABIAmAAIABAAIABACIAAAQIgBABIgBABIgmAAIgBAAIAAAdIABABIA6AAIABABIABACIAAARIgBACIgBAAg");
	this.shape_17.setTransform(120.875,21.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Bg
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AueDNIAAmZIc9AAIAAGZg");
	this.shape_18.setTransform(110.0113,20.475,1.1863,1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FFFFFF").ss(1,1,1).p("ARMDNMgiXAAAIAAmZMAiXAAAg");
	this.shape_19.setTransform(110,20.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18,p:{x:110.0113}}]}).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_18,p:{x:109.976}}]},1).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,222,43);


(lib.gpic3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Arrow
	this.instance = new lib.g_arrow("synched",0);
	this.instance.setTransform(69,76.45,1,1,0,180,0,26,26);

	this.instance_1 = new lib.g_arrow("synched",0);
	this.instance_1.setTransform(271,190.05,1,1,0,0,180,26,26);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	mask.setTransform(150,125);

	// Gradient_Top
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0.6)","rgba(0,0,0,0)"],[0.125,0.953],0,-0.1,0,0,-0.1,112.9).s().p("AtdNeQlmlkAAn6QAAn5FmllQFlllH4AAQH6AAFlFlQFlFlAAH5QAAH6llFkQllFmn6AAQn4AAlllmg");
	this.shape.setTransform(65.525,2.675);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Gradient
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.rf(["rgba(0,0,0,0.498)","rgba(0,0,0,0)"],[0,0.882],0,0,0,0,0,110.6).s().p("At6NNQlxldAAnwQAAnvFxleQFxldIJAAQIKAAFxFdQFxFeAAHvQAAHwlxFdQlxFeoKAAQoJAAlxleg");
	this.shape_1.setTransform(207,220.55);

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Gradient
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.rf(["rgba(0,0,0,0.498)","rgba(0,0,0,0)"],[0,0.882],0,0,0,0,0,110.6).s().p("At6NNQlxldAAnwQAAnvFxleQFxldIJAAQIKAAFxFdQFxFeAAHvQAAHwlxFdQlxFeoKAAQoJAAlxleg");
	this.shape_2.setTransform(117,220.55);

	var maskedShapeInstanceList = [this.shape_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Gradient
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.rf(["rgba(0,0,0,0.498)","rgba(0,0,0,0)"],[0,0.882],0,0,0,0,0,110.6).s().p("At6NNQlxldAAnwQAAnvFxleQFxldIJAAQIKAAFxFdQFxFeAAHvQAAHwlxFdQlxFeoKAAQoJAAlxleg");
	this.shape_3.setTransform(37,220.55);

	var maskedShapeInstanceList = [this.shape_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

	// Photo_new
	this.instance_2 = new lib.Pic3new();

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


// stage content:
(lib.banner_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Logo
	this.instance = new lib.g_SFULogo("synched",0);
	this.instance.setTransform(26.1,0.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(354));

	// Red_Bg_as_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_79 = new cjs.Graphics().p("AgxTiMAAAgnDIBjAAMAAAAnDg");
	var mask_graphics_80 = new cjs.Graphics().p("AisTiMAAAgnDIFZAAMAAAAnDg");
	var mask_graphics_81 = new cjs.Graphics().p("AkiTiMAAAgnDIJFAAMAAAAnDg");
	var mask_graphics_82 = new cjs.Graphics().p("AmSTiMAAAgnDIMlAAMAAAAnDg");
	var mask_graphics_83 = new cjs.Graphics().p("An+TiMAAAgnDIP9AAMAAAAnDg");
	var mask_graphics_84 = new cjs.Graphics().p("ApjTiMAAAgnDITHAAMAAAAnDg");
	var mask_graphics_85 = new cjs.Graphics().p("ArDTiMAAAgnDIWHAAMAAAAnDg");
	var mask_graphics_86 = new cjs.Graphics().p("AsdTiMAAAgnDIY7AAMAAAAnDg");
	var mask_graphics_87 = new cjs.Graphics().p("AtyTiMAAAgnDIblAAMAAAAnDg");
	var mask_graphics_88 = new cjs.Graphics().p("AvCTiMAAAgnDIeFAAMAAAAnDg");
	var mask_graphics_89 = new cjs.Graphics().p("AwMTiMAAAgnDMAgZAAAMAAAAnDg");
	var mask_graphics_90 = new cjs.Graphics().p("AxQTiMAAAgnDMAihAAAMAAAAnDg");
	var mask_graphics_91 = new cjs.Graphics().p("AyQTiMAAAgnDMAkhAAAMAAAAnDg");
	var mask_graphics_92 = new cjs.Graphics().p("AzJTiMAAAgnDMAmTAAAMAAAAnDg");
	var mask_graphics_93 = new cjs.Graphics().p("Az9TiMAAAgnDMAn7AAAMAAAAnDg");
	var mask_graphics_94 = new cjs.Graphics().p("A0sTiMAAAgnDMApZAAAMAAAAnDg");
	var mask_graphics_95 = new cjs.Graphics().p("A1VTiMAAAgnDMAqrAAAMAAAAnDg");
	var mask_graphics_96 = new cjs.Graphics().p("A14TiMAAAgnDMArxAAAMAAAAnDg");
	var mask_graphics_97 = new cjs.Graphics().p("A2WTiMAAAgnDMAstAAAMAAAAnDg");
	var mask_graphics_98 = new cjs.Graphics().p("A2vTiMAAAgnDMAtfAAAMAAAAnDg");
	var mask_graphics_99 = new cjs.Graphics().p("A3CTiMAAAgnDMAuFAAAMAAAAnDg");
	var mask_graphics_100 = new cjs.Graphics().p("A3QTiMAAAgnDMAuhAAAMAAAAnDg");
	var mask_graphics_101 = new cjs.Graphics().p("A3YTiMAAAgnDMAuxAAAMAAAAnDg");
	var mask_graphics_102 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(79).to({graphics:mask_graphics_79,x:305,y:125}).wait(1).to({graphics:mask_graphics_80,x:291.825,y:125}).wait(1).to({graphics:mask_graphics_81,x:279.225,y:125}).wait(1).to({graphics:mask_graphics_82,x:267.2,y:125}).wait(1).to({graphics:mask_graphics_83,x:255.75,y:125}).wait(1).to({graphics:mask_graphics_84,x:244.925,y:125}).wait(1).to({graphics:mask_graphics_85,x:234.675,y:125}).wait(1).to({graphics:mask_graphics_86,x:225.025,y:125}).wait(1).to({graphics:mask_graphics_87,x:215.925,y:125}).wait(1).to({graphics:mask_graphics_88,x:207.425,y:125}).wait(1).to({graphics:mask_graphics_89,x:199.525,y:125}).wait(1).to({graphics:mask_graphics_90,x:192.175,y:125}).wait(1).to({graphics:mask_graphics_91,x:185.45,y:125}).wait(1).to({graphics:mask_graphics_92,x:179.3,y:125}).wait(1).to({graphics:mask_graphics_93,x:173.75,y:125}).wait(1).to({graphics:mask_graphics_94,x:168.75,y:125}).wait(1).to({graphics:mask_graphics_95,x:164.375,y:125}).wait(1).to({graphics:mask_graphics_96,x:160.55,y:125}).wait(1).to({graphics:mask_graphics_97,x:157.325,y:125}).wait(1).to({graphics:mask_graphics_98,x:154.675,y:125}).wait(1).to({graphics:mask_graphics_99,x:152.625,y:125}).wait(1).to({graphics:mask_graphics_100,x:151.175,y:125}).wait(1).to({graphics:mask_graphics_101,x:150.275,y:125}).wait(1).to({graphics:mask_graphics_102,x:150,y:125}).wait(252));

	// Btn__1_2_3
	this.instance_1 = new lib.btn_CTA_AD_123();
	this.instance_1.setTransform(97.5,158.3,1,1,0,0,0,83,25.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn_CTA_AD_123(), 3);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(258).to({_off:false},0).to({x:118.5,alpha:1},22,cjs.Ease.get(0.9)).wait(74));

	// text_03_new_AD_1_2_3_4
	this.instance_2 = new lib.g_txt03AD123("synched",0);
	this.instance_2.setTransform(32.05,80.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(210).to({_off:false},0).to({alpha:1},28,cjs.Ease.get(1)).wait(116));

	// text_02_new_Ad03
	this.instance_3 = new lib.g_txt02AD3_new("synched",0);
	this.instance_3.setTransform(-313.45,68.5,1,1,0,0,0,-66.5,28);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(79).to({_off:false},0).to({x:-42.5},25,cjs.Ease.get(1)).wait(79).to({startPosition:0},0).to({x:-338.45},21,cjs.Ease.get(1)).to({_off:true},3).wait(147));

	// Red_Bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC0633").s().p("AgxTiMAAAgnDIBjAAMAAAAnDg");
	this.shape.setTransform(305,125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC0633").s().p("AisTiMAAAgnDIFZAAMAAAAnDg");
	this.shape_1.setTransform(291.825,125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CC0633").s().p("AkiTiMAAAgnDIJFAAMAAAAnDg");
	this.shape_2.setTransform(279.225,125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC0633").s().p("AmSTiMAAAgnDIMlAAMAAAAnDg");
	this.shape_3.setTransform(267.2,125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC0633").s().p("An+TiMAAAgnDIP9AAMAAAAnDg");
	this.shape_4.setTransform(255.75,125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC0633").s().p("ApjTiMAAAgnDITHAAMAAAAnDg");
	this.shape_5.setTransform(244.925,125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CC0633").s().p("ArDTiMAAAgnDIWHAAMAAAAnDg");
	this.shape_6.setTransform(234.675,125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC0633").s().p("AsdTiMAAAgnDIY7AAMAAAAnDg");
	this.shape_7.setTransform(225.025,125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CC0633").s().p("AtyTiMAAAgnDIblAAMAAAAnDg");
	this.shape_8.setTransform(215.925,125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CC0633").s().p("AvCTiMAAAgnDIeFAAMAAAAnDg");
	this.shape_9.setTransform(207.425,125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#CC0633").s().p("AwMTiMAAAgnDMAgZAAAMAAAAnDg");
	this.shape_10.setTransform(199.525,125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CC0633").s().p("AxQTiMAAAgnDMAihAAAMAAAAnDg");
	this.shape_11.setTransform(192.175,125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CC0633").s().p("AyQTiMAAAgnDMAkhAAAMAAAAnDg");
	this.shape_12.setTransform(185.45,125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#CC0633").s().p("AzJTiMAAAgnDMAmTAAAMAAAAnDg");
	this.shape_13.setTransform(179.3,125);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#CC0633").s().p("Az9TiMAAAgnDMAn7AAAMAAAAnDg");
	this.shape_14.setTransform(173.75,125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#CC0633").s().p("A0sTiMAAAgnDMApZAAAMAAAAnDg");
	this.shape_15.setTransform(168.75,125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#CC0633").s().p("A1VTiMAAAgnDMAqrAAAMAAAAnDg");
	this.shape_16.setTransform(164.375,125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#CC0633").s().p("A14TiMAAAgnDMArxAAAMAAAAnDg");
	this.shape_17.setTransform(160.55,125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CC0633").s().p("A2WTiMAAAgnDMAstAAAMAAAAnDg");
	this.shape_18.setTransform(157.325,125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#CC0633").s().p("A2vTiMAAAgnDMAtfAAAMAAAAnDg");
	this.shape_19.setTransform(154.675,125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#CC0633").s().p("A3CTiMAAAgnDMAuFAAAMAAAAnDg");
	this.shape_20.setTransform(152.625,125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#CC0633").s().p("A3QTiMAAAgnDMAuhAAAMAAAAnDg");
	this.shape_21.setTransform(151.175,125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#CC0633").s().p("A3YTiMAAAgnDMAuxAAAMAAAAnDg");
	this.shape_22.setTransform(150.275,125);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#CC0633").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_23.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},79).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).wait(252));

	// Text_01_new_AD_1_3
	this.instance_4 = new lib.g_txt01AD13_new("synched",0);
	this.instance_4.setTransform(-244.2,186,1,1,0,0,0,-66.5,28);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(11).to({_off:false},0).to({x:-69.45},21,cjs.Ease.get(1)).to({_off:true},72).wait(250));

	// Photo_new_AD03
	this.instance_5 = new lib.gpic3("single",0);
	var instance_5Filter_1 = new cjs.ColorFilter(1,1,1,1,255,255,255,0);
	this.instance_5.filters = [instance_5Filter_1];
	this.instance_5.cache(-2,-2,304,254);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({startPosition:0},18,cjs.Ease.get(1)).to({_off:true},86).wait(250));
	this.timeline.addTween(cjs.Tween.get(instance_5Filter_1).to(new cjs.ColorFilter(1,1,1,1,0,0,0,0), 18,cjs.Ease.get(1)).wait(250));

	this.filterCacheList = [];
	this.filterCacheList.push({instance: this.instance_5, startFrame:1, endFrame:18, x:-2, y:-2, w:304, h:254});
	this.filterCacheList.push({instance: this.instance_5, startFrame:0, endFrame:0, x:-2, y:-2, w:304, h:254});
	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-24.7,125,334.7,125);
// library properties:
lib.properties = {
	id: 'C38F8E925B074A239B4A15BB5DD6BAC8',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png?1726691735553", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C38F8E925B074A239B4A15BB5DD6BAC8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;