(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.p01 = function() {
	this.initialize(img.p01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p02 = function() {
	this.initialize(img.p02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p03 = function() {
	this.initialize(img.p03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p04 = function() {
	this.initialize(img.p04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p05 = function() {
	this.initialize(img.p05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p06 = function() {
	this.initialize(img.p06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p07 = function() {
	this.initialize(img.p07);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p08 = function() {
	this.initialize(img.p08);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p09 = function() {
	this.initialize(img.p09);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.p12 = function() {
	this.initialize(img.p12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,250);


(lib.Wordmark = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text_Black
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#010101").s().p("AGQEyQgegeAAg0QAAg0AeggQAdgfAwAAQAvAAAbAeQAbAeAAAxIgBAMIidAAQACAfAQASQAQASAZAAQATAAAMgJQAMgIAFgOIAxAAQgHAggYATQgbAVgnAAQgxAAgegggAG6CgQgOAMgEAUIBlAAQgCgUgNgMQgNgLgUAAQgUgBgPAMgADBE+QgagUgEggIAyAAQACAQAOAIQAOAIAVAAQATAAALgHQAKgIAAgLQAAgJgGgGQgHgGgSgEIgmgIQgegGgQgQQgRgQAAgYQAAgeAYgTQAZgTAnAAQAmAAAZATQAYASAEAfIgyAAQgBgOgLgHQgLgJgTAAQgTAAgKAIQgJAGAAAMQAAAJAGAGQAHAGAQADIApAHQAeAGAQARQAQAQAAAYQAAAggYATQgZAUgpAAQgqAAgcgUgAJrE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAKANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQgiAAgTgXgAggE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAJANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQghAAgTgXgARRFMIAAiBQAAgxglgBQgVAAgOASQgRAUAAAeIAABvIgxAAIAAh+QAAgagJgNQgKgOgSAAQgVAAgOASQgQAUAAAeIAABvIgyAAIAAjaIAxAAIAAApQAbguAqAAQAXAAARAOQAPAMAHAXQAMgWAUgNQAWgOAYAAQAhAAARAWQASAXAAApIAACJgAiGFMIAAkLIhaELIgtAAIhakKIAAEKIgyAAIAAkxIBXAAIBMDhIBLjhIBYAAIAAExgAo8FMQg/AAAAg2IAAh9IgrAAIAAgnIArAAIAAg0IAygdIAABRIAxAAIAAAnIgxAAIAAByQAAAMAFAGQAGAGAQAAIAkAAIAAApgAtPFMIAAjaIAxAAIAAA0QAKgaAPgPQASgQAVAAQAXAAAMAVQAKARAAAfIAAAPIgsAAIAAgIQAAgdgVAAQgRgBgNAVQgNAUAAAfIAABpgAuaFMIgXhIIiBAAIgYBIIg4AAIBtkxIBLAAIBqExgAwjDWIBiAAIgwiUgAxOg/QgpgrAAhEQAAhFArgvQAtgvBHAAQAqAAAjATQAjATAUAjIgsAcQgRgagRgMQgXgQghAAQgwABgcAeQgaAeAAA0QAAAzAaAeQAbAeAvAAQAjAAAXgSQAZgUAHglIhIAAIAAguIB3AAIAACiIgpAAIgCg3QgQAegcAQQgbAPgjAAQg+AAgogsgAkWgzQgdggAAgzQAAgzAdggQAeggAvAAQAvAAAeAgQAcAgAAAzQAAAzgcAgQgeAfgvAAQgvAAgegfgAjxi8QgPATAAAjQAAAiAPATQAOAUAagBQAaABAPgUQAOgTAAgiQAAgjgPgTQgOgUgaAAQgZAAgPAUgAnigoQgagVgEgfIAyAAQACAQAOAIQAOAJAVAAQATAAALgIQALgHAAgMQAAgJgHgGQgHgGgRgEIgngIQgegHgQgPQgQgQAAgYQAAgeAXgSQAZgUAmAAQAgAAAVANIALAGQAYATAEAeIgxAAQgCgNgLgIQgMgJgSAAQgTAAgKAIQgJAGAAAMQAAAKAGAFQAHAHAQACIApAHQALACAKAFQAQAGAJALQAQAPAAAZQAAAfgYAUQgIAFgJAFQgUAJgdAAQgqAAgcgUgAqIghQgTgOgOgWIAAAsIgyAAIAAkyIAyAAIAACDQAOgYAUgMQAUgNAWAAQAlAAAWAgQAVAeAAA0QAAA0gWAeQgVAhgmAAQgWAAgUgNgAqVi7QgVAVAAAfQAAAfAVAVQATAUAVgBQAVABAMgTQAMgTAAgiQAAgjgMgSQgLgSgVAAQgWAAgTATgABGgZIAAh6QAAgegJgOQgJgNgVAAQgWAAgQATQgSAUAAAgIAABsIgxAAIAAjbIAxAAIAAAqQANgUARgNQAVgOAWAAQAjAAASAWQATAYAAAoIAACKgAsxgZIAAjbIAyAAIAADbgAs1kTIAAg4IA7AAIAAA4g");
	this.shape.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(7).to({_off:false},0).to({_off:true},1).wait(23));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.5,-33.8,231,67.6);


(lib._Stage = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {"Purple Dark":43,green:81,"Purple Dark":119,White:157,transit_bg:448,"Beige Yellow":0,Forest:62,Pink:100,"Red orange":138};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Size_ref
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(255,255,255,0)").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},442).wait(7));

	// grey_border
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#CCCCCC").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape_1.setTransform(150,300);
	this.shape_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(157).to({_off:false},0).to({_off:true},285).wait(7));

	// Layer_2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,248,239,0)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_2.setTransform(151.525,301.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,248,239,0.039)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_3.setTransform(151.525,301.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,248,239,0.165)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_4.setTransform(151.525,301.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,248,239,0.369)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_5.setTransform(151.525,301.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,248,239,0.631)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_6.setTransform(151.525,301.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,248,239,0.835)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_7.setTransform(151.525,301.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,248,239,0.961)").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_8.setTransform(151.525,301.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFF8EF").s().p("AvEHbIAAu1IeJAAIAAO1g");
	this.shape_9.setTransform(151.525,301.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2}]},441).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).wait(1));

	// Gibson_SFU_Logo
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AigBMQgOgBgMgHQAEgJACgNQALAIAFADQAMAFALAAQAOAAAIgHQAJgHAAgLQAAgMgMgIQgIgFgMgFQgMgFgJgGQgQgKAAgUQAAgRAMgNQANgNAXAAQAHAAAPADIAOAFIgDAJIgEALIAAAAQgKgHgKgEIgOgCQgKAAgHAGQgGAGAAAKQAAAKAIAHQAEAEAaAMQATAJAHAJQAFAJAAALQAAAOgKAOQgPATgeAAQgJAAgGgCgABRBDQgIgFgGgJQgEgHAAgFQgCgGAAgRIgBhdIANABIANgBIgCAUIgBBEQAAASABAEQABAGADAFQAKAOAbAAQAQAAALgGIAJgIQAEgFABgHIABgaIgBhCIgCgRIAMAAIALAAIgCBUQAAAcgDALQgEAKgLAIQgPALgcAAQgdAAgOgKgAgtBLIgLABIAAiXIBAABIARgBIgBALIAAALIgJgBIgvgCIAAAtIAaAAQAOAAANgCQgCAGAAAGIABAKQgTgDgJAAIgYAAIAAAUQAAAeABAUg");
	this.shape_10.setTransform(210.125,294.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#A51D39").s().p("AlnC0IAAlnILPAAIAAFngAgpCQQAMAGANACQAGABAJAAQAeAAAPgTQAKgOAAgOQAAgLgGgJQgGgIgUgLQgZgMgDgDQgJgIAAgKQAAgKAHgFQAGgHAJAAIAPACQAJAEAKAHIABAAIADgLIAEgJIgPgEQgOgCgHAAQgWgBgNAMQgMAOAAAQQAAAUAPALQAKAGALAFQAMAFAIAFQALAIAAAMQAAALgIAHQgIAHgOAAQgKAAgMgFQgGgDgKgIQgDANgDAKgADOBdQAAARABAGQABAGAEAGQAGAJAHAGQAPAJAcAAQAcAAAPgKQAMgIAEgLQADgLAAgcIABhUIgLAAIgMAAIACARIABBCIgBAbQgBAGgDAFIgJAIQgLAGgQAAQgcAAgJgOQgEgFAAgGQgBgEAAgSIABhFIACgTIgNABIgNgBgABxCXQgCgTAAgfIAAgTIAYAAQALgBASADIAAgLQAAgGABgFQgMABgPAAIgbAAIABgsIAwABIAJABIgBgLIACgKIgRABIhBgBIgBCXIAMgBIAOABIAAAAg");
	this.shape_11.setTransform(195.675,286.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#010101").s().p("AGBDHQgMgOAAgZIAAhWIAfAAIAABMQAAATAGAIQAFAIANAAQAPAAAJgLQALgNAAgUIAAhDIAgAAIAACIIgfAAIAAgaQgTAdgcAAQgVAAgLgOgAD4DBQgSgSAAggQAAggASgUQASgUAeAAQAdAAARATQARASAAAeIgBAIIhhAAQABATAKALQAKAMAQAAQAXgBAGgTIAfAAQgEATgQANQgQANgZAAQgeAAgTgUgAETBnQgJAIgCALIA/AAQgCgMgIgIQgJgGgMgBQgMABgJAHgAB4DJQgRgNgCgTIAAgBIAfAAQADAUAdABQAZAAAAgRQAAgMgTgEIgYgEQgngJAAgeQAAgTAPgLQAPgMAYAAQAYAAAQAMQAOAKADAUIgfAAQgCgTgYAAQgYABAAAQQAAALASAEIAaAEQAnAIAAAgQAAATgPAMQgQAMgaAAQgaAAgRgMgAgTDHQgMgOAAgZIAAhWIAfAAIAABMQAAAjAXAAQAOAAAKgLQALgNAAgUIAAhDIAfAAIAACIIgeAAIAAgaQgUAdgaAAQgVAAgLgOgAIDDSIAAiIIAfAAIAAAaQAPgdAcAAQAdAAAJAeQAIgNAMgIQAOgJAPAAQAUAAALAOQALAOAAAZIAABWIgfAAIAAhRQAAgegYAAQgMAAgJALQgLALAAAUIAABFIgeAAIAAhPQAAgggXAAQgNAAgJALQgKALAAAUIAABFgAhUDSIAAinIg3CnIgcAAIg4imIAACmIgfAAIAAi+IA2AAIAwCMIAuiMIA3AAIAAC+gAljDSQgngBAAghIAAhOIgbAAIAAgYIAbAAIAAghIAegRIAAAyIAfAAIAAAYIgfAAIAABHQAAAPARAAIAXAAIAAAagAoPDSIAAiIIAfAAIAAAgQAPgjAZAAQAcAAAAAqIAAAKIgbAAIAAgEQAAgTgNAAQgLAAgIAMQgJAOAAASIAABCgAo9DSIgPgtIhPAAIgPAtIgjAAIBDi+IAvAAIBCC+gAqSCJIA9AAIgehcgAkrgcQgQgMgDgUIAAAAIAfAAQACATAdAAQAaABAAgRQAAgLgUgEIgYgGQgmgHAAgeQAAgUAPgLQAPgMAYAAQAYAAAPAMQAPALADAUIgfAAQgCgUgYABQgYAAAAAQQAAALASAEIAZAFQAnAHAAAgQAAAUgPAMQgPAMgaAAQgaAAgRgNgAqtgqQgZgbAAgqQAAgrAagdQAcgdAsAAQAaAAAWALQAWAMANAVIgcASQgKgQgLgIQgOgJgUAAQgfAAgRATQgRATAAAgQAAAgARATQARASAdABQAuAAAKgvIgtAAIAAgeIBKAAIAABlIgZAAIgBghQgUAlguAAQgnAAgZgbgAitgjQgSgUAAggQAAgfASgUQATgTAdgBQAeABASATQASAUAAAfQAAAggSAUQgSAUgeAAQgdAAgTgUgAiWh4QgJAMAAAVQAAAWAJANQAJALAQAAQARAAAIgLQAJgNAAgWQAAgVgJgMQgJgMgQAAQgQAAgJAMgAmoguIAAAcIgeAAIAAi/IAfAAIAABSQASgeAdgBQAXABANATQANATAAAgIABAAQAAAggNATQgOAVgYAAQgcgBgTgegAmah4QgOAOAAATQAAAUAOANQAMALANAAQAcAAAAgsQAAgVgIgMQgHgLgNAAQgNAAgMALgAAsgTIAAhMQAAgjgZAAQgOAAgKAMQgLAMAAAUIAABDIgeAAIAAiIIAeAAIAAAaQARgdAcAAQAWABAMAOQALANAAAaIAABVgAn7gTIAAiIIAeAAIAACIgAn+ivIAAgiIAkAAIAAAig");
	this.shape_12.setTransform(140.025,310.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10}]},357).to({state:[]},91).wait(1));

	// Msg_Text_2
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2ECC75").s().p("ACBDjQgOgPAAgXIAAjXQAAh5hsAAQg4AAggAkQghAiAAA6IAADQQAAAYgOAOQgOAPgXAAQgXAAgNgPQgQgOABgYIAAl1QgBgYAQgQQANgOAXAAQAXAAAOAOQAOAQAAAYIAAAJQAshCBjAAQBWAAAzAzQA0A1gBBdIAADpQABAXgOAPQgQAPgVAAQgYAAgOgPg");
	this.shape_13.setTransform(198.95,300.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2ECC75").s().p("AigCyQhEhDAAhvQAAhsBBhEQBBhDBmABQBngBA9A+QA9A7AABgQAAA5g2AAIkrAAQAGA2AoAgQAnAgA+AAQBGAAAngvQAXgVAWAAQAoAAAAAqQAAATgPAWQgZAng1AVQgwAUg5gBQhwABhDhCgAB/gzQgFgzgjgdQghgcg1AAQg0AAgiAdQgiAegFAxID7AAIAAAAg");
	this.shape_14.setTransform(146.25,300.65);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2ECC75").s().p("AjhEWQgPgPAAgXIAAnbQAAgYAPgQQAOgOAXAAQAWAAAPAOQAOAQAAAYIAAAMQA2hFBhAAQBiAABABDQBBBEAABtQAABrhBBEQhABDhiAAQhiAAg1hBIAABvQAAAXgOAPQgPAPgWAAQgXAAgOgPgAhmiaQglApAABAQAAA/AlAqQAnArA9AAQA7AAAmgnQAogqAAhCQAAhEgogpQgmgog7AAQg9AAgnArg");
	this.shape_15.setTransform(95.325,305.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#2ECC75").s().p("AiwCxQhFhEAAhtQAAhsBFhEQBEhDBsABQBsgBBFBDQBFBEAABsQAABthFBEQhFBChsAAQhsAAhEhCgAhlhrQgnAqAABBQAABCAnApQAoAqA9AAQA+AAAngqQAngpAAhCQAAhBgngqQgngog+AAQg9AAgoAog");
	this.shape_16.setTransform(38.575,300.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#2ECC75").s().p("ABeCdIhekRIhdERQgdBWg+AAQhAAAgZhWIhqlHIgDgYQAAgVAPgOQAOgNAXAAQApAAAJAoIBnFHIBrkzQAUg8AyAAQAyAAAVA8IBrE1IBnlJQAJgoApAAQAWAAAPANQAPAOAAAVIgEAYIhpFHQgaBWg/AAQg/AAgchWg");
	this.shape_17.setTransform(169.2,236.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#2ECC75").s().p("AiwCxQhFhEAAhtQAAhsBFhEQBEhDBsABQBsgBBFBDQBFBEAABsQAABthFBEQhFBChsAAQhsAAhEhCgAhlhrQgnAqAABBQAABCAnAqQAoApA9AAQA+AAAngpQAngqAAhCQAAhBgngqQgngog+AAQg9AAgoAog");
	this.shape_18.setTransform(103.125,236.75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#2ECC75").s().p("AB3EHIkMmAIAAF5QAAAZgPAPQgOAPgYAAQgZAAgPgPQgOgPAAgZIAAnwQAAggARgTQATgUAdABQAmgBAlA1IEJGDIAAmBQAAgYAPgPQAPgPAYAAQAYAAAQAPQAPAPgBAYIAAHxQABAggTATQgRAUgdgBQgnAAgjgwg");
	this.shape_19.setTransform(44.2,229.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13}]},319).to({state:[]},33).to({state:[]},90).wait(7));

	// Msg_Text_1
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#2ECC75").s().p("AA5BkQgGgHAAgKIAAheQAAg1gwAAQgYAAgPAPQgOAQAAAZIAABbQAAAKgGAHQgHAHgJAAQgKAAgHgHQgGgHAAgKIAAikQAAgLAGgGQAHgHAKAAQAJAAAHAHQAGAGAAALIAAAEQAUgdArAAQAmAAAWAXQAXAWAAAqIAABmQAAAKgGAHQgHAHgKAAQgKAAgGgHg");
	this.shape_20.setTransform(214.675,314.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#2ECC75").s().p("AhNBOQgfgeAAgwQAAgvAfgeQAegdAvAAQAwAAAeAdQAfAeAAAvQAAAwgfAeQgeAdgwAAQgvAAgegdgAgsgvQgRATAAAcQAAAdARATQASARAaABQAbgBASgRQARgTAAgdQAAgcgRgTQgSgRgbgBQgaABgSARg");
	this.shape_21.setTransform(190.375,314.55);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#2ECC75").s().p("AgPCMQgHgHAAgKIAAilQAAgKAHgHQAGgGAJAAQAKAAAGAGQAHAHAAAKIAAClQAAAKgHAHQgGAHgKAAQgJAAgGgHgAgThiQgIgIAAgMQAAgMAIgIQAIgIALAAQANAAAIAIQAHAIAAAMQAAAMgHAIQgIAIgNAAQgLAAgIgIg");
	this.shape_22.setTransform(173.525,310.525);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#2ECC75").s().p("AgTB1QgTgSABgcIAAhpIgcAAQgKAAgFgFQgHgGAAgJQAAgJAHgGQAFgGAKABIAcAAIAAgjQgBgLAHgGQAGgHAKAAQALAAAFAHQAGAGAAALIAAAjIA2AAQAJgBAGAGQAGAGAAAJQAAAJgGAGQgGAFgJAAIg2AAIAABiQAAAbAXgBQALABANgKQAIgIAIAAQAIABAEAFQAFAFABAIQAAANgNALQgTASgfAAQgbAAgRgRg");
	this.shape_23.setTransform(159.25,311.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#2ECC75").s().p("AhEBNQgegeAAgvQAAguAegeQAegeAtAAQAxgBAZAaQASATAAAQQAAAKgGAFQgFAGgJAAQgMAAgKgOQgQgaggAAQgaABgRARQgRATAAAcQAAAdARATQARARAaABQAggBARgcQAIgNANAAQAJABAFAFQAGAGAAAIQAAARgRASQgbAcgwAAQgtAAgegeg");
	this.shape_24.setTransform(140.15,314.55);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#2ECC75").s().p("AhHBOQgdgdAAgxQAAgvAcgeQAdgdAtAAQAtAAAbAaQAbAbAAAqQAAAZgYgBIiEAAQADAZASANQARAPAbAAQAfAAARgVQAKgJAKAAQASAAAAATQAAAHgHALQgLAQgXAKQgWAJgZgBQgxAAgegdgAA4gWQgCgXgPgMQgPgMgYAAQgWAAgPAMQgPANgDAWIBvAAIAAAAg");
	this.shape_25.setTransform(118.175,314.55);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#2ECC75").s().p("AA5BkQgGgHAAgKIAAheQAAg1gwAAQgYAAgPAPQgOAQAAAZIAABbQAAAKgGAHQgHAHgJAAQgKAAgHgHQgGgHAAgKIAAikQAAgLAGgGQAHgHAKAAQAJAAAHAHQAGAGAAALIAAAEQAUgdArAAQAmAAAWAXQAXAWAAAqIAABmQAAAKgGAHQgHAHgKAAQgKAAgGgHg");
	this.shape_26.setTransform(94.875,314.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#2ECC75").s().p("AA5BkQgGgHAAgKIAAheQAAg1gwAAQgYAAgPAPQgOAQAAAZIAABbQAAAKgGAHQgHAHgJAAQgKAAgHgHQgGgHAAgKIAAikQAAgLAGgGQAHgHAKAAQAJAAAHAHQAGAGAAALIAAAEQAUgdArAAQAmAAAWAXQAXAWAAAqIAABmQAAAKgGAHQgHAHgKAAQgKAAgGgHg");
	this.shape_27.setTransform(70.275,314.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#2ECC75").s().p("AhNBOQgfgeAAgwQAAgvAfgeQAegdAvAAQAwAAAeAdQAfAeAAAvQAAAwgfAeQgeAdgwAAQgvAAgegdgAgsgvQgRATAAAcQAAAdARATQASARAaABQAbgBASgRQARgTAAgdQAAgcgRgTQgSgRgbgBQgaABgSARg");
	this.shape_28.setTransform(45.975,314.55);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#2ECC75").s().p("AhEBNQgegeAAgvQAAguAegeQAegeAtAAQAxgBAZAaQARATAAAQQABAKgGAFQgGAGgIAAQgNAAgJgOQgRgaggAAQgZABgRARQgRATAAAcQAAAdARATQARARAZABQAhgBARgcQAJgNAMAAQAIABAGAFQAGAGAAAIQAAARgRASQgcAcgvAAQgtAAgegeg");
	this.shape_29.setTransform(23.3,314.55);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#2ECC75").s().p("AhYB1QgOgLAAgOQAAgJAGgGQAFgGAIAAQAGAAAFAEQAKAMANAAQASAAAMgYIhHiVQgHgOAAgHQAAgKAGgGQAGgFAKAAQAQgBAJAWIA2BzIAzhyQAJgWARAAQAJAAAGAFQAHAGAAAJQAAAJgGAMIhMClQgXA0gugBQgYAAgQgMg");
	this.shape_30.setTransform(221.625,276.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#2ECC75").s().p("AgTB1QgSgSAAgdIAAhoIgcAAQgJAAgHgFQgFgGgBgJQABgJAFgGQAHgGAJABIAcAAIAAgjQAAgLAGgGQAHgHAJAAQALAAAEAHQAHAGAAALIAAAjIA2AAQAJgBAGAGQAGAGAAAJQAAAJgGAGQgGAFgJAAIg2AAIAABiQAAAbAXgBQALABAMgLQAJgGAIgBQAIAAAEAGQAGAFAAAIQgBANgLAKQgVATgeAAQgbAAgRgRg");
	this.shape_31.setTransform(201.3,271.95);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#2ECC75").s().p("AgPCMQgHgHAAgKIAAilQAAgKAHgHQAGgGAJAAQAKAAAGAGQAHAHAAAKIAAClQAAAKgHAHQgGAHgKAAQgJAAgGgHgAgThiQgIgIAAgMQAAgMAIgIQAIgIALAAQANAAAIAIQAHAIAAAMQAAAMgHAIQgIAIgNAAQgLAAgIgIg");
	this.shape_32.setTransform(188.025,270.575);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#2ECC75").s().p("AA5BkQgGgGAAgLIAAheQAAg2gwABQgYAAgPAPQgOAQAAAZIAABbQAAALgGAGQgHAHgJAAQgKAAgHgHQgGgGAAgLIAAikQAAgKAGgHQAHgHAKAAQAJAAAHAHQAGAHAAAKIAAAEQAUgdArAAQAmAAAWAXQAXAWAAAqIAABmQAAALgGAGQgHAHgKAAQgKAAgGgHg");
	this.shape_33.setTransform(170.875,274.55);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#2ECC75").s().p("AhJBVQgWgYAAgqIAAhlQAAgLAGgGQAGgHAKAAQALAAAGAHQAGAGAAALIAABeQAAA1AwAAQAYAAAOgPQAPgPAAgbIAAhaQAAgKAGgHQAHgHAJAAQAKAAAGAHQAHAGAAALIAACkQAAALgHAGQgGAHgKAAQgJAAgHgHQgGgGAAgLIAAgEQgTAdgsAAQgmAAgXgWg");
	this.shape_34.setTransform(146.05,274.65);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#2ECC75").s().p("AB9BkQgHgGAAgLIAAheQAAg2gtABQgXAAgNAPQgOAQAAAZIAABbQAAALgGAGQgHAHgKAAQgJAAgGgHQgGgGgBgLIAAheQABg2guABQgWAAgOAPQgNAQAAAZIAABbQAAALgHAGQgHAHgJAAQgKAAgHgHQgGgGAAgLIAAikQAAgKAGgHQAHgHAKAAQAJAAAHAHQAHAHAAAKIAAADQASgcAqAAQAuAAAUAjQAVgjAzAAQAlAAAWAXQAWAXAAApIAABmQAAALgGAGQgHAHgKAAQgJAAgGgHg");
	this.shape_35.setTransform(114.95,274.55);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#2ECC75").s().p("AB8BkQgGgGAAgLIAAheQAAg2gtABQgXAAgNAPQgOAQAAAZIAABbQAAALgHAGQgGAHgKAAQgJAAgGgHQgGgGAAgLIAAheQgBg2gsABQgYAAgNAPQgOAQAAAZIAABbQABALgHAGQgGAHgKAAQgKAAgHgHQgGgGAAgLIAAikQAAgKAGgHQAHgHAKAAQAKAAAGAHQAHAHgBAKIAAADQAUgcApAAQAvAAATAjQAVgjAzAAQAlAAAWAXQAWAXAAApIAABmQAAALgGAGQgGAHgLAAQgKAAgGgHg");
	this.shape_36.setTransform(76.95,274.55);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#2ECC75").s().p("AhNBOQgfgeAAgwQAAgvAfgeQAegdAvAAQAwAAAeAdQAfAeAAAvQAAAwgfAeQgeAegwAAQgvAAgegegAgsgvQgRATAAAcQAAAeARASQASARAaABQAbgBASgRQARgSAAgeQAAgcgRgTQgSgSgbAAQgaAAgSASg");
	this.shape_37.setTransform(45.975,274.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#2ECC75").s().p("AhEBNQgegeAAgvQAAguAegeQAegeAtAAQAxAAAZAaQARARAAARQABAJgGAGQgGAGgIAAQgNAAgJgOQgRgaggAAQgZAAgRASQgRATAAAcQAAAdARATQARARAZABQAhgBARgcQAJgNAMAAQAIAAAGAGQAGAGAAAJQAAAQgRASQgcAdgvAAQgtgBgegeg");
	this.shape_38.setTransform(23.3,274.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#2ECC75").s().p("AhNBtQgcgeAAgwQAAgvAcgeQAcgeAsABQAqgBAYAeIAAhEQAAgKAGgHQAHgGAKAAQAJAAAHAGQAGAHAAAKIAADkQAAAKgGAHQgHAGgJABQgKgBgHgGQgGgHAAgKIAAgEQgXAdgrAAQgsAAgcgegAgpgQQgSARAAAeQAAAdASATQARASAZAAQAbgBARgSQARgTAAgcQAAgcgRgRQgRgUgbAAQgZABgRARg");
	this.shape_39.setTransform(260.625,231.55);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#2ECC75").s().p("AA5BkQgGgHAAgKIAAheQAAg2gwABQgYAAgPAPQgOAPAAAaIAABbQAAAKgGAHQgHAHgJAAQgKAAgHgHQgGgHAAgKIAAikQAAgKAGgIQAHgGAKAAQAJAAAHAGQAGAIAAAKIAAAEQAUgdArAAQAmAAAWAXQAXAWAAAqIAABmQAAAKgGAHQgHAHgKAAQgKAAgGgHg");
	this.shape_40.setTransform(236.825,234.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#2ECC75").s().p("AhYBbQgSgQgBgbQABgvA6gMIAugKQALgDAEgEQAFgEAAgIQAAgbgjAAQgdAAgUAXQgNAMgJAAQgTAAAAgSQAAgLAKgLQAbgiA1AAQAmAAAVASQAVASAAAiIAABVQAAAOALAAQAGAAAFgFQAEgFAGAAQANAAgBAPQABALgJAKQgNASgVAAQgeAAgLgaQgXAaglAAQggAAgUgQgAgDAMIgYAFQgfAHAAAVQAAALAJAHQAIAGAPAAQAUAAALgLQANgNAAgRIAAgZQgHAGgOADg");
	this.shape_41.setTransform(214.35,234.625);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#2ECC75").s().p("AhGBSQgPgOgBgPQABgTASABQALAAALAMQAUAWAeAAQAjAAgBgXQAAgVgagFIgfgHQg8gMgBgtQABgdAVgRQAWgQAjAAQApgBAYATQASANAAASQAAAHgEAGQgGAFgIAAQgJAAgOgNQgRgRgZAAQggAAAAAVQAAATAdAFIAgAHQA6ALAAAvQgBAfgWASQgWASgnAAQgxAAgYgag");
	this.shape_42.setTransform(182.3,234.65);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#2ECC75").s().p("AhYBbQgSgQAAgbQAAgvA6gMIAtgKQALgDAFgEQAFgEAAgIQAAgbgjAAQgdAAgUAXQgMAMgKAAQgSAAAAgSQAAgLAJgLQAbgiA2AAQAlAAAVASQAVASAAAiIAABVQAAAOALAAQAGAAAEgFQAFgFAFAAQANAAABAPQgBALgHAKQgOASgVAAQgeAAgMgaQgVAagmAAQghAAgTgQgAgDAMIgXAFQghAHAAAVQABALAIAHQAKAGAPAAQASAAAMgLQANgNAAgRIAAgZQgHAGgOADg");
	this.shape_43.setTransform(162.3,234.625);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#2ECC75").s().p("AhHBOQgdgeAAgwQAAgwAcgdQAdgeAtABQAtgBAbAbQAbAbAAAqQAAAZgYgBIiEAAQADAYASAOQARAPAbAAQAfAAARgVQAKgJAKAAQASAAAAATQAAAHgHALQgLARgXAJQgWAJgZAAQgxAAgegegAA4gWQgCgWgPgNQgPgMgYAAQgWAAgPAMQgPANgDAWIBvAAIAAAAg");
	this.shape_44.setTransform(138.775,234.65);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#2ECC75").s().p("AhNBtQgcgeAAgwQAAgvAcgeQAcgeAsABQAqgBAYAeIAAhEQAAgKAGgHQAHgGAKAAQAJAAAHAGQAGAHAAAKIAADkQAAAKgGAHQgHAGgJABQgKgBgHgGQgGgHAAgKIAAgEQgXAdgrAAQgsAAgcgegAgpgQQgSARAAAeQAAAdASATQARASAZAAQAbgBARgSQARgTAAgcQAAgcgRgRQgRgUgbAAQgZABgRARg");
	this.shape_45.setTransform(114.225,231.55);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#2ECC75").s().p("AgPCMQgHgHAAgKIAAilQAAgKAHgHQAGgGAJAAQAKAAAGAGQAHAHAAAKIAAClQAAAKgHAHQgGAHgKAAQgJAAgGgHgAgThiQgIgIAAgMQAAgMAIgIQAIgIALAAQANAAAIAIQAHAIAAAMQAAAMgHAIQgIAIgNAAQgLAAgIgIg");
	this.shape_46.setTransform(97.625,230.625);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#2ECC75").s().p("AghAoQAAgJALgFQARgGAEgMQgOgBgIgHQgIgIAAgMQAAgOAJgJQAJgIAOAAQAPAAAJALQAJALAAATQAAAZgQATQgQASgTAAQgQAAAAgMg");
	this.shape_47.setTransform(78.7,244.325);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#2ECC75").s().p("AgTB1QgTgSABgdIAAhoIgcAAQgKAAgFgFQgHgGAAgJQAAgJAHgGQAFgFAKAAIAcAAIAAgjQgBgLAHgHQAGgGAKAAQALAAAEAGQAHAHAAALIAAAjIA2AAQAJAAAGAFQAGAGAAAJQAAAJgGAGQgGAFgJAAIg2AAIAABiQAAAaAXAAQALAAANgKQAIgGAIgBQAIAAAEAGQAFAFABAIQAAANgNAKQgTATgfAAQgbAAgRgRg");
	this.shape_48.setTransform(65.2,232);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#2ECC75").s().p("AhDBkQgHgHAAgKIAAikQAAgKAHgIQAGgGALAAQAJAAAHAGQAGAIAAAKIAAACQASgbAiAAQAYAAAPANQAMAMAAAPQAAAZgYAAQgJAAgJgKQgKgMgNAAQgQABgLAPQgLAQAAAZIAABZQAAAKgGAHQgHAHgJAAQgLAAgGgHg");
	this.shape_49.setTransform(48.8,234.6);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#2ECC75").s().p("ABVB8IgUg0IiBAAIgVA0QgFAPgSAAQgJAAgHgHQgHgHAAgJQAAgHADgJIBTjIQAIgUAKgIQALgKAQAAQARAAALAKQAKAIAIAUIBSDIQAEAJAAAHQAAAJgHAHQgHAHgJAAQgSAAgGgPgAAvAaIgvh2IguB2IBdAAg");
	this.shape_50.setTransform(25.5,231.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20}]},262).to({state:[]},57).to({state:[]},33).wait(97));

	// Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A3bRMMAAAgiXMAu3AAAMAAAAiXg");
	mask.setTransform(150,277);

	// Photo
	this.instance = new lib.p02();
	this.instance.setTransform(15,137);

	this.instance_1 = new lib.p04();
	this.instance_1.setTransform(15,147);

	this.instance_2 = new lib.p06();
	this.instance_2.setTransform(15,137);

	this.instance_3 = new lib.p08();
	this.instance_3.setTransform(15,164);

	this.instance_4 = new lib.p12();
	this.instance_4.setTransform(15,156);

	var maskedShapeInstanceList = [this.instance,this.instance_1,this.instance_2,this.instance_3,this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},196).to({state:[]},5).to({state:[{t:this.instance_1}]},5).to({state:[]},5).to({state:[{t:this.instance_2}]},5).to({state:[]},5).to({state:[{t:this.instance_3}]},5).to({state:[]},5).to({state:[{t:this.instance_4}]},5).to({state:[]},5).to({state:[]},201).wait(7));

	// Photo
	this.instance_5 = new lib.p01();
	this.instance_5.setTransform(15,137);

	this.instance_6 = new lib.p03();
	this.instance_6.setTransform(15,137);

	this.instance_7 = new lib.p05();
	this.instance_7.setTransform(15,137);

	this.instance_8 = new lib.p07();
	this.instance_8.setTransform(15,137);

	this.instance_9 = new lib.p09();
	this.instance_9.setTransform(15,165);

	var maskedShapeInstanceList = [this.instance_5,this.instance_6,this.instance_7,this.instance_8,this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_5}]},191).to({state:[]},5).to({state:[{t:this.instance_6}]},5).to({state:[]},5).to({state:[{t:this.instance_7}]},5).to({state:[]},5).to({state:[{t:this.instance_8}]},5).to({state:[]},5).to({state:[{t:this.instance_9}]},5).to({state:[]},5).to({state:[]},116).wait(97));

	// Layer_3
	this.instance_10 = new lib.p01();
	this.instance_10.setTransform(15,137);
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(191).to({_off:false},0).to({_off:true},50).wait(208));

	// GAM_Text
	this.instance_11 = new lib.Wordmark("single",0);
	this.instance_11.setTransform(150.05,300,0.7041,0.7041);
	var instance_11Filter_1 = new cjs.ColorFilter(0,0,0,1,255,248,239,0);
	this.instance_11.filters = [instance_11Filter_1];
	this.instance_11.cache(-117,-36,235,72);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#010101").s().p("AGQEyQgegeAAg0QAAg0AeggQAdgfAwAAQAvAAAbAeQAbAeAAAxIgBAMIidAAQACAfAQASQAQASAZAAQATAAAMgJQAMgIAFgOIAxAAQgHAggYATQgbAVgnAAQgxAAgegggAG6CgQgOAMgEAUIBlAAQgCgUgNgMQgNgLgUAAQgUgBgPAMgADBE+QgagUgEggIAyAAQACAQAOAIQAOAIAVAAQATAAALgHQAKgIAAgLQAAgJgGgGQgHgGgSgEIgmgIQgegGgQgQQgRgQAAgYQAAgeAYgTQAZgTAnAAQAmAAAZATQAYASAEAfIgyAAQgBgOgLgHQgLgJgTAAQgTAAgKAIQgJAGAAAMQAAAJAGAGQAHAGAQADIApAHQAeAGAQARQAQAQAAAYQAAAggYATQgZAUgpAAQgqAAgcgUgAJrE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAKANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQgiAAgTgXgAggE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAJANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQghAAgTgXgARRFMIAAiBQAAgxglgBQgVAAgOASQgRAUAAAeIAABvIgxAAIAAh+QAAgagJgNQgKgOgSAAQgVAAgOASQgQAUAAAeIAABvIgyAAIAAjaIAxAAIAAApQAbguAqAAQAXAAARAOQAPAMAHAXQAMgWAUgNQAWgOAYAAQAhAAARAWQASAXAAApIAACJgAiGFMIAAkLIhaELIgtAAIhakKIAAEKIgyAAIAAkxIBXAAIBMDhIBLjhIBYAAIAAExgAo8FMQg/AAAAg2IAAh9IgrAAIAAgnIArAAIAAg0IAygdIAABRIAxAAIAAAnIgxAAIAAByQAAAMAFAGQAGAGAQAAIAkAAIAAApgAtPFMIAAjaIAxAAIAAA0QAKgaAPgPQASgQAVAAQAXAAAMAVQAKARAAAfIAAAPIgsAAIAAgIQAAgdgVAAQgRgBgNAVQgNAUAAAfIAABpgAuaFMIgXhIIiBAAIgYBIIg4AAIBtkxIBLAAIBqExgAwjDWIBiAAIgwiUgAxOg/QgpgrAAhEQAAhFArgvQAtgvBHAAQAqAAAjATQAjATAUAjIgsAcQgRgagRgMQgXgQghAAQgwABgcAeQgaAeAAA0QAAAzAaAeQAbAeAvAAQAjAAAXgSQAZgUAHglIhIAAIAAguIB3AAIAACiIgpAAIgCg3QgQAegcAQQgbAPgjAAQg+AAgogsgAkWgzQgdggAAgzQAAgzAdggQAeggAvAAQAvAAAeAgQAcAgAAAzQAAAzgcAgQgeAfgvAAQgvAAgegfgAjxi8QgPATAAAjQAAAiAPATQAOAUAagBQAaABAPgUQAOgTAAgiQAAgjgPgTQgOgUgaAAQgZAAgPAUgAnigoQgagVgEgfIAyAAQACAQAOAIQAOAJAVAAQATAAALgIQALgHAAgMQAAgJgHgGQgHgGgRgEIgngIQgegHgQgPQgQgQAAgYQAAgeAXgSQAZgUAmAAQAgAAAVANIALAGQAYATAEAeIgxAAQgCgNgLgIQgMgJgSAAQgTAAgKAIQgJAGAAAMQAAAKAGAFQAHAHAQACIApAHQALACAKAFQAQAGAJALQAQAPAAAZQAAAfgYAUQgIAFgJAFQgUAJgdAAQgqAAgcgUgAqIghQgTgOgOgWIAAAsIgyAAIAAkyIAyAAIAACDQAOgYAUgMQAUgNAWAAQAlAAAWAgQAVAeAAA0QAAA0gWAeQgVAhgmAAQgWAAgUgNgAqVi7QgVAVAAAfQAAAfAVAVQATAUAVgBQAVABAMgTQAMgTAAgiQAAgjgMgSQgLgSgVAAQgWAAgTATgABGgZIAAh6QAAgegJgOQgJgNgVAAQgWAAgQATQgSAUAAAgIAABsIgxAAIAAjbIAxAAIAAAqQANgUARgNQAVgOAWAAQAjAAASAWQATAYAAAoIAACKgAsxgZIAAjbIAyAAIAADbgAs1kTIAAg4IA7AAIAAA4g");
	this.shape_51.setTransform(149.985,299.9613,0.7041,0.7041);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("ANmKbQhBhEAAhwQAAhwBAhFQBAhFBnAAQBnAAA7BBQA6BAAABsIgBAZIlVAAQAEBFAiAnQAiAnA4AAQAoAAAbgTQAagSALggIBqAAQgOBGg2ArQg5AthXAAQhqAAhAhEgAPBFdQgfAagIAqIDcAAQgFgsgcgZQgdgZgsAAQgrAAggAagAGkKyQg6grgHhEIAAgBIBrAAQAFAiAfATQAdASAuAAQArAAAXgRQAXgPAAgaQAAgUgOgMQgPgOgngIIhUgRQhBgOgjgiQgjgjAAgzQAAhCA0gpQA0gqBVAAQBUAAA1ApQA0AoAKBEIhsAAQgEgegXgRQgZgTgpAAQgoAAgWAQQgUAPAAAZQAAAVAOAMQAPANAiAGIBZARQBCAMAjAlQAiAkAAA0QAABEg0AqQg2ArhaAAQhbAAg8gtgAVBKtQgogxAAhZIAAkrIBsAAIAAEKQAABBAVAdQAUAdAsAAQAxAAAkgoQAmgtAAhGIAAjqIBtAAIAAHcIhrAAIAAhcQgdAtgnAbQgtAegxAAQhLAAgpgxgAhHKtQgogxAAhZIAAkrIBsAAIAAEKQAABBAUAdQAUAdAsAAQAxAAAkgoQAmgtAAhGIAAjqIBsAAIAAHcIhqAAIAAhcQgdAtgoAbQgsAegyAAQhJAAgpgxgEAliALUIAAkbQAAhrhRAAQgsAAggAnQgkAqAABDIAADyIhqAAIAAkTQAAg4gVgdQgVgegnAAQgtAAggAnQgjAqAABDIAADyIhsAAIAAncIBrAAIAABYQA6hjBbAAQA0AAAjAeQAhAcAPAxQAbgwAsgcQAugfA1AAQBHAAAnAxQAmAwAABZIAAEtgAkmLUIAApIIjDJIIhiAAIjCpGIAAJGIhtAAIAAqZIC8AAICnHqICinqIDAAAIAAKZgAzeLUQiIAAAAh2IAAkRIhdAAIAAhVIBdAAIAAhxIBsg+IAACvIBrAAIAABVIhrAAIAAD4QAAAbAMAMQANAMAiAAIBQAAIAABcgA8zLUIAAncIBrAAIAABwQAWg3AhgfQAlglAuAAQA0AAAZAtQAVAmAABDIAAAhIheAAIAAgSQAAg/guAAQgmAAgcArQgdAtAABCIAADngA/VLUIg0ieIkXAAIg1CeIh5AAIDsqZICkAAIDmKZgEgj/AHSIDVAAIhplCgEglegCJQhYhfAAiTQAAiXBehkQBhhoCaAAQBbAABMApQBNAqAsBLIhgA+Qgkg4gngbQgyghhGAAQhpAAg8BCQg7BCAABwQAABwA6BBQA6BBBmAAQBMAAAzgoQA3grAPhQIieAAIAAhlIEEAAIAAFhIhZAAIgFh3QgjBBg8AiQg7AhhMAAQiIAAhXhfgAwYhZQg6grgIhFIBsAAQAEAiAfATQAeASAtAAQArAAAYgRQAWgPAAgaQAAgUgNgMQgQgOgmgIIhVgSQhBgNgjgiQgjgjAAgzQAAhCA0gpQA1gqBUAAQBEAAAvAbQAMAGALAIQA0AoAJBEIhrAAQgEgegYgRQgZgTgoAAQgpAAgWAQQgUAPAAAZQAAAVAOAMQAPANAiAGIBZAQQAaAFAVAJQAhAOAWAWQAiAkAAA0QAABEg1AqQgQANgUAKQgtAUg/AAQhaAAg8gtgApdhxQg/hFAAhuQAAhvA/hFQBAhGBnAAQBnAAA/BGQA/BFAABvQAABvg/BEQg/BFhnAAQhnAAhAhFgAoOmZQggAqAABLQAABLAgApQAgAqA4AAQA4AAAggqQAfgqAAhKQAAhLgggqQgfgrg4AAQg4AAggArgA2ChKQgqgcgegyIAABhIhsAAIAAqZIBtAAIAAEcQAegzArgbQArgcAvAAQBSAAAvBGQAtBCAABvQAABwguBEQgvBFhTAAQgvAAgrgcgA2emYQguAvAABDQAABDAuAvQApApAuAAQAtAAAagnQAbgpAAhMQAAhKgagpQgZgngsAAQgwAAgqApgACZg3IAAkKQAAhBgVgeQgUgdgsAAQgxAAgjApQgnAsAABGIAADrIhsAAIAAncIBrAAIAABbQAdgtAmgbQAtgeAwAAQBLAAApAxQApAxAABZIAAEsgA7xg3IAAncIBtAAIAAHcgA75pYIAAh4IB/AAIAAB4g");
	this.shape_52.setTransform(150.1,300,0.3239,0.3239,0,0,0,0.3,0.1);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FF5427").s().p("AG0DeQgNgQAAgdIAAhhIAjAAIAABXQAAAUAHAKQAGAJAOAAQAQABAMgNQAMgPAAgXIAAhMIAjAAIAACaIgiAAIAAgeQgKAPgMAKQgPAJgQAAQgYAAgNgQgAEaDYQgVgWAAgkQAAglAVgWQAUgWAiAAQAhAAATAVQATAVAAAiIAAAIIhvAAQABAXAMAMQALANASAAQANAAAIgFQAJgHADgKIAjAAQgFAWgRAOQgTAPgcAAQgiAAgVgWgAE4BxQgLAJgCANIBHAAQgBgOgKgIQgJgIgOAAQgOAAgKAIgACIDfQgSgNgDgXIAjAAQABAMALAFQAJAGAPAAQAOAAAHgGQAHgEAAgIQAAgHgEgEQgFgEgMgDIgcgFQgVgFgLgLQgMgMAAgQQAAgWARgNQASgNAbAAQAbAAARANQARANADAWIgjAAQgBgKgIgGQgHgFgOAAQgNgBgHAGQgGAFAAAIQAAAHAEAEQAFADALADIAdAFQAVAEAMAMQALALAAARQAAAXgRANQgSAOgdAAQgdAAgUgPgAgWDeQgNgQAAgdIAAhhIAjAAIAABXQAAAUAGAKQAGAJAOAAQAQABAMgNQAMgPAAgXIAAhMIAjAAIAACaIgiAAIAAgeQgKAPgMAKQgPAJgQAAQgXAAgNgQgAMKDqIAAhbQAAgjgaAAQgOAAgLANQgLAOAAAVIAABOIgjAAIAAhZQAAgSgHgKQgGgJgNAAQgPAAgKANQgLAOAAAVIAABOIgjAAIAAiaIAjAAIAAAdQASggAeAAQAQAAAMAKQALAIAEARQAJgQAOgJQAPgKASAAQAXAAAMAQQAMAPAAAdIAABhgAheDqIAAi9IhAC9IgfAAIg/i8IAAC8IgjAAIAAjXIA8AAIA2CfIA1ifIA+AAIAADXgAmTDqQgsAAAAgmIAAhYIgeAAIAAgcIAeAAIAAgkIAjgUIAAA4IAjAAIAAAcIgjAAIAABQQAAAJAEAEQAEADALAAIAaAAIAAAegApUDqIAAiaIAjAAIAAAkQAHgRAKgLQANgLAOAAQARAAAIAOQAHANAAAVIAAALIgfAAIAAgFQAAgWgOAAQgNAAgIAPQgKAOAAAVIAABLgAqJDqIgQgzIhbAAIgRAzIgnAAIBMjXIA2AAIBKDXgArpCXIBFAAIgihpgAsIgsQgcgeAAgwQAAgxAeggQAfgiAyAAQAeAAAZANQAYAOAPAYIgfAUQgMgSgNgIQgQgLgXAAQgiAAgTAVQgTAVAAAkQAAAlATAVQASAVAiAAQAYAAARgMQARgPAFgaIgzAAIAAggIBUAAIAAByIgdAAIgBgnQgLAWgUALQgTAKgZAAQgsAAgcgfgAjDgkQgVgWAAgkQAAgkAVgXQAVgWAhAAQAhAAAVAWQAUAXAAAkQAAAkgUAWQgVAWghABQghgBgVgWgAipiEQgLAOAAAYQAAAZALANQAKANASAAQASAAALgNQAJgOAAgYQAAgYgKgOQgKgNgSAAQgSAAgKANgAlTgcQgSgOgDgXIAjAAQABALALAHQAJAFAPABQAOAAAHgGQAIgFAAgIQAAgHgFgEQgFgEgMgDIgcgFQgVgFgLgLQgLgLAAgRQAAgVAQgNQASgOAbAAQAWAAAPAJIAHAEQARANADAWIgiAAQgCgJgIgGQgIgGgNAAQgNAAgHAFQgGAFAAAIQAAAHAEAEQAFAFALABIAdAFQAIABAHAEQALAEAHAIQALALAAARQAAAWgRANQgGAFgGADQgOAHgVAAQgdAAgUgPgAnIgXQgNgKgKgPIAAAfIgjAAIAAjYIAjAAIAABcQAKgQAOgJQAOgJAPAAQAbAAAPAWQAPAWAAAlQAAAjgQAWQgPAXgaAAQgQAAgOgJgAnRiDQgPAPAAAWQAAAVAPAQQANANAPgBQAPAAAIgMQAJgOAAgXQAAgZgIgNQgJgNgOAAQgPABgOANgAAygRIAAhWQAAgWgHgJQgGgJgPAAQgQAAgKANQgNAOAAAXIAABMIgjAAIAAibIAjAAIAAAeQAJgOAMgJQAOgKAQAAQAYAAANAQQAOAQAAAcIAABigAo/gRIAAibIAjAAIAACbgApCjBIAAgoIAqAAIAAAog");
	this.shape_53.setTransform(149.975,299.95);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFB1EB").s().p("AGQEyQgegeAAg0QAAg0AeggQAdgfAwAAQAvAAAbAeQAbAeAAAxIgBAMIidAAQACAfAQASQAQASAZAAQATAAAMgJQAMgIAFgOIAxAAQgHAggYATQgbAVgnAAQgxAAgegggAG6CgQgOAMgEAUIBlAAQgCgUgNgMQgNgLgUAAQgUgBgPAMgADBE+QgagUgEggIAyAAQACAQAOAIQAOAIAVAAQATAAALgHQAKgIAAgLQAAgJgGgGQgHgGgSgEIgmgIQgegGgQgQQgRgQAAgYQAAgeAYgTQAZgTAnAAQAmAAAZATQAYASAEAfIgyAAQgBgOgLgHQgLgJgTAAQgTAAgKAIQgJAGAAAMQAAAJAGAGQAHAGAQADIApAHQAeAGAQARQAQAQAAAYQAAAggYATQgZAUgpAAQgqAAgcgUgAJrE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAKANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQgiAAgTgXgAggE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAJANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQghAAgTgXgARRFMIAAiBQAAgxglgBQgVAAgOASQgRAUAAAeIAABvIgxAAIAAh+QAAgagJgNQgKgOgSAAQgVAAgOASQgQAUAAAeIAABvIgyAAIAAjaIAxAAIAAApQAbguAqAAQAXAAARAOQAPAMAHAXQAMgWAUgNQAWgOAYAAQAhAAARAWQASAXAAApIAACJgAiGFMIAAkLIhaELIgtAAIhakKIAAEKIgyAAIAAkxIBXAAIBMDhIBLjhIBYAAIAAExgAo8FMQg/AAAAg2IAAh9IgrAAIAAgnIArAAIAAg0IAygdIAABRIAxAAIAAAnIgxAAIAAByQAAAMAFAGQAGAGAQAAIAkAAIAAApgAtPFMIAAjaIAxAAIAAA0QAKgaAPgPQASgQAVAAQAXAAAMAVQAKARAAAfIAAAPIgsAAIAAgIQAAgdgVAAQgRgBgNAVQgNAUAAAfIAABpgAuaFMIgXhIIiBAAIgYBIIg4AAIBtkxIBLAAIBqExgAwjDWIBiAAIgwiUgAxOg/QgpgrAAhEQAAhFArgvQAtgvBHAAQAqAAAjATQAjATAUAjIgsAcQgRgagRgMQgXgQghAAQgwABgcAeQgaAeAAA0QAAAzAaAeQAbAeAvAAQAjAAAXgSQAZgUAHglIhIAAIAAguIB3AAIAACiIgpAAIgCg3QgQAegcAQQgbAPgjAAQg+AAgogsgAkWgzQgdggAAgzQAAgzAdggQAeggAvAAQAvAAAeAgQAcAgAAAzQAAAzgcAgQgeAfgvAAQgvAAgegfgAjxi8QgPATAAAjQAAAiAPATQAOAUAagBQAaABAPgUQAOgTAAgiQAAgjgPgTQgOgUgaAAQgZAAgPAUgAnigoQgagVgEgfIAyAAQACAQAOAIQAOAJAVAAQATAAALgIQALgHAAgMQAAgJgHgGQgHgGgRgEIgngIQgegHgQgPQgQgQAAgYQAAgeAXgSQAZgUAmAAQAgAAAVANIALAGQAYATAEAeIgxAAQgCgNgLgIQgMgJgSAAQgTAAgKAIQgJAGAAAMQAAAKAGAFQAHAHAQACIApAHQALACAKAFQAQAGAJALQAQAPAAAZQAAAfgYAUQgIAFgJAFQgUAJgdAAQgqAAgcgUgAqIghQgTgOgOgWIAAAsIgyAAIAAkyIAyAAIAACDQAOgYAUgMQAUgNAWAAQAlAAAWAgQAVAeAAA0QAAA0gWAeQgVAhgmAAQgWAAgUgNgAqVi7QgVAVAAAfQAAAfAVAVQATAUAVgBQAVABAMgTQAMgTAAgiQAAgjgMgSQgLgSgVAAQgWAAgTATgABGgZIAAh6QAAgegJgOQgJgNgVAAQgWAAgQATQgSAUAAAgIAABsIgxAAIAAjbIAxAAIAAAqQANgUARgNQAVgOAWAAQAjAAASAWQATAYAAAoIAACKgAsxgZIAAjbIAyAAIAADbgAs1kTIAAg4IA7AAIAAA4g");
	this.shape_54.setTransform(149.985,299.9613,0.7041,0.7041);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#F8FF90").s().p("AGQEyQgegeAAg0QAAg0AeggQAdgfAwAAQAvAAAbAeQAbAeAAAxIgBAMIidAAQACAfAQASQAQASAZAAQATAAAMgJQAMgIAFgOIAxAAQgHAggYATQgbAVgnAAQgxAAgegggAG6CgQgOAMgEAUIBlAAQgCgUgNgMQgNgLgUAAQgUgBgPAMgADBE+QgagUgEggIAyAAQACAQAOAIQAOAIAVAAQATAAALgHQAKgIAAgLQAAgJgGgGQgHgGgSgEIgmgIQgegGgQgQQgRgQAAgYQAAgeAYgTQAZgTAnAAQAmAAAZATQAYASAEAfIgyAAQgBgOgLgHQgLgJgTAAQgTAAgKAIQgJAGAAAMQAAAJAGAGQAHAGAQADIApAHQAeAGAQARQAQAQAAAYQAAAggYATQgZAUgpAAQgqAAgcgUgAJrE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAKANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQgiAAgTgXgAggE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAJANQAJAOAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUAOgXAAQghAAgTgXgARRFMIAAiBQAAgxglgBQgVAAgOASQgRAUAAAeIAABvIgxAAIAAh+QAAgagJgNQgKgOgSAAQgVAAgOASQgQAUAAAeIAABvIgyAAIAAjaIAxAAIAAApQAbguAqAAQAXAAARAOQAPAMAHAXQAMgWAUgNQAWgOAYAAQAhAAARAWQASAXAAApIAACJgAiGFMIAAkLIhaELIgtAAIhakKIAAEKIgyAAIAAkxIBXAAIBMDhIBLjhIBYAAIAAExgAo8FMQg/AAAAg2IAAh9IgrAAIAAgnIArAAIAAg0IAygdIAABRIAxAAIAAAnIgxAAIAAByQAAAMAFAGQAGAGAQAAIAkAAIAAApgAtPFMIAAjaIAxAAIAAA0QAKgaAPgPQASgQAVAAQAXAAAMAVQAKARAAAfIAAAPIgsAAIAAgIQAAgdgVAAQgRgBgNAVQgNAUAAAfIAABpgAuaFMIgXhIIiBAAIgYBIIg4AAIBtkxIBLAAIBqExgAwjDWIBiAAIgwiUgAxOg/QgpgrAAhEQAAhFArgvQAtgvBHAAQAqAAAjATQAjATAUAjIgsAcQgRgagRgMQgXgQghAAQgwABgcAeQgaAeAAA0QAAAzAaAeQAbAeAvAAQAjAAAXgSQAZgUAHglIhIAAIAAguIB3AAIAACiIgpAAIgCg3QgQAegcAQQgbAPgjAAQg+AAgogsgAkWgzQgdggAAgzQAAgzAdggQAeggAvAAQAvAAAeAgQAcAgAAAzQAAAzgcAgQgeAfgvAAQgvAAgegfgAjxi8QgPATAAAjQAAAiAPATQAOAUAagBQAaABAPgUQAOgTAAgiQAAgjgPgTQgOgUgaAAQgZAAgPAUgAnigoQgagVgEgfIAyAAQACAQAOAIQAOAJAVAAQATAAALgIQALgHAAgMQAAgJgHgGQgHgGgRgEIgngIQgegHgQgPQgQgQAAgYQAAgeAXgSQAZgUAmAAQAgAAAVANIALAGQAYATAEAeIgxAAQgCgNgLgIQgMgJgSAAQgTAAgKAIQgJAGAAAMQAAAKAGAFQAHAHAQACIApAHQALACAKAFQAQAGAJALQAQAPAAAZQAAAfgYAUQgIAFgJAFQgUAJgdAAQgqAAgcgUgAqIghQgTgOgOgWIAAAsIgyAAIAAkyIAyAAIAACDQAOgYAUgMQAUgNAWAAQAlAAAWAgQAVAeAAA0QAAA0gWAeQgVAhgmAAQgWAAgUgNgAqVi7QgVAVAAAfQAAAfAVAVQATAUAVgBQAVABAMgTQAMgTAAgiQAAgjgMgSQgLgSgVAAQgWAAgTATgABGgZIAAh6QAAgegJgOQgJgNgVAAQgWAAgQATQgSAUAAAgIAABsIgxAAIAAjbIAxAAIAAAqQANgUARgNQAVgOAWAAQAjAAASAWQATAYAAAoIAACKgAsxgZIAAjbIAyAAIAADbgAs1kTIAAg4IA7AAIAAA4g");
	this.shape_55.setTransform(149.985,299.9613,0.7041,0.7041);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#4F0049").s().p("AGQEzQgeggAAgzQAAg0AeggQAdgfAwAAQAvAAAbAeQAbAeAAAxIgBAMIidAAQACAfAQASQAQASAZAAQATAAAMgIQAMgJAFgOIAxAAQgHAfgYAUQgbAVgnAAQgxAAgegfgAG6CgQgOAMgEAUIBlAAQgCgVgNgLQgNgLgUAAQgUgBgPAMgADBE+QgagVgEgfIAyAAQACAQAOAIQAOAIAVAAQATAAALgHQAKgHAAgMQAAgKgGgFQgHgHgSgDIgmgIQgegHgQgPQgRgQAAgYQAAgeAYgTQAZgTAnAAQAmAAAZATQAYASAEAfIgyAAQgBgOgLgHQgLgJgTAAQgTAAgKAIQgJAGAAAMQAAAJAGAGQAHAGAQADIApAHQAeAGAQARQAQAQAAAYQAAAggYATQgZAUgpAAQgqAAgcgUgAJrE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAKAOQAJANAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUANgXABQgiAAgTgXgAggE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAJAOQAJANAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUANgXABQghAAgTgXgARRFMIAAiBQAAgxglAAQgVgBgOATQgRATAAAeIAABvIgxAAIAAh+QAAgZgJgOQgKgNgSAAQgVgBgOATQgQATAAAeIAABvIgyAAIAAjaIAxAAIAAApQAbguAqAAQAXAAARAOQAPANAHAWQAMgWAUgNQAWgOAYAAQAhAAARAWQASAXAAAoIAACKgAiGFMIAAkLIhaELIgtAAIhakKIAAEKIgyAAIAAkxIBXAAIBMDhIBLjhIBYAAIAAExgAo8FMQg/AAAAg2IAAh9IgrAAIAAgnIArAAIAAg0IAygdIAABRIAxAAIAAAnIgxAAIAAByQAAAMAFAGQAGAFAQABIAkAAIAAApgAtPFMIAAjaIAxAAIAAA0QAKgaAPgPQASgQAVAAQAXAAAMAVQAKARAAAfIAAAPIgsAAIAAgIQAAgegVABQgRAAgNAUQgNAUAAAfIAABpgAuaFMIgXhIIiBAAIgYBIIg4AAIBtkxIBLAAIBqExgAwjDWIBiAAIgwiUgAxOg/QgpgrAAhEQAAhGArguQAtgvBHAAQAqAAAjASQAjAUAUAiIgsAdQgRgagRgMQgXgQghAAQgwABgcAeQgaAeAAA0QAAA0AaAdQAbAeAvAAQAjAAAXgSQAZgUAHglIhIAAIAAguIB3AAIAACiIgpAAIgCg3QgQAegcAQQgbAPgjAAQg+AAgogsgAkWgzQgdggAAgzQAAgzAdggQAeggAvAAQAvAAAeAgQAcAgAAAzQAAAzgcAgQgeAfgvAAQgvAAgegfgAjxi8QgPATAAAjQAAAjAPASQAOAUAaAAQAaAAAPgUQAOgTAAgiQAAgjgPgTQgOgTgagBQgZABgPATgAnigoQgagVgEgfIAyAAQACAQAOAIQAOAJAVAAQATAAALgIQALgHAAgMQAAgJgHgGQgHgGgRgEIgngIQgegHgQgPQgQgQAAgYQAAgeAXgSQAZgUAmAAQAgAAAVAMIALAHQAYATAEAeIgxAAQgCgNgLgIQgMgJgSAAQgTAAgKAIQgJAGAAAMQAAAJAGAHQAHAGAQACIApAHQALACAKAFQAQAGAJALQAQAPAAAZQAAAfgYATQgIAGgJAFQgUAJgdAAQgqAAgcgUgAqIghQgTgOgOgWIAAAsIgyAAIAAkyIAyAAIAACCQAOgXAUgMQAUgNAWAAQAlAAAWAgQAVAeAAA0QAAAzgWAgQgVAfgmAAQgWABgUgNgAqVi7QgVAVAAAfQAAAfAVAVQATAUAVgBQAVABAMgTQAMgTAAgiQAAgjgMgSQgLgSgVAAQgWAAgTATgABGgZIAAh7QAAgdgJgOQgJgNgVAAQgWAAgQATQgSAUAAAgIAABsIgxAAIAAjbIAxAAIAAAqQANgUARgNQAVgOAWAAQAjAAASAWQATAYAAAoIAACKgAsxgZIAAjbIAyAAIAADbgAs1kTIAAg4IA7AAIAAA4g");
	this.shape_56.setTransform(150.0324,300,0.7041,0.7041);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AGQEzQgeggAAgzQAAg0AeggQAdgfAwAAQAvAAAbAeQAbAeAAAxIgBAMIidAAQACAfAQASQAQASAZAAQATAAAMgIQAMgJAFgOIAxAAQgHAfgYAUQgbAVgnAAQgxAAgegfgAG6CgQgOAMgEAUIBlAAQgCgVgNgLQgNgLgUAAQgUgBgPAMgADBE+QgagVgEgfIAyAAQACAQAOAIQAOAIAVAAQATAAALgHQAKgHAAgMQAAgKgGgFQgHgHgSgDIgmgIQgegHgQgPQgRgQAAgYQAAgeAYgTQAZgTAnAAQAmAAAZATQAYASAEAfIgyAAQgBgOgLgHQgLgJgTAAQgTAAgKAIQgJAGAAAMQAAAJAGAGQAHAGAQADIApAHQAeAGAQARQAQAQAAAYQAAAggYATQgZAUgpAAQgqAAgcgUgAJrE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAKAOQAJANAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUANgXABQgiAAgTgXgAggE7QgTgXAAgpIAAiJIAyAAIAAB6QAAAeAJAOQAJANAUAAQAXAAAQgSQASgVAAghIAAhrIAyAAIAADaIgxAAIAAgpQgOAUgSANQgUANgXABQghAAgTgXgARRFMIAAiBQAAgxglAAQgVgBgOATQgRATAAAeIAABvIgxAAIAAh+QAAgZgJgOQgKgNgSAAQgVgBgOATQgQATAAAeIAABvIgyAAIAAjaIAxAAIAAApQAbguAqAAQAXAAARAOQAPANAHAWQAMgWAUgNQAWgOAYAAQAhAAARAWQASAXAAAoIAACKgAiGFMIAAkLIhaELIgtAAIhakKIAAEKIgyAAIAAkxIBXAAIBMDhIBLjhIBYAAIAAExgAo8FMQg/AAAAg2IAAh9IgrAAIAAgnIArAAIAAg0IAygdIAABRIAxAAIAAAnIgxAAIAAByQAAAMAFAGQAGAFAQABIAkAAIAAApgAtPFMIAAjaIAxAAIAAA0QAKgaAPgPQASgQAVAAQAXAAAMAVQAKARAAAfIAAAPIgsAAIAAgIQAAgegVABQgRAAgNAUQgNAUAAAfIAABpgAuaFMIgXhIIiBAAIgYBIIg4AAIBtkxIBLAAIBqExgAwjDWIBiAAIgwiUgAxOg/QgpgrAAhEQAAhGArguQAtgvBHAAQAqAAAjASQAjAUAUAiIgsAdQgRgagRgMQgXgQghAAQgwABgcAeQgaAeAAA0QAAA0AaAdQAbAeAvAAQAjAAAXgSQAZgUAHglIhIAAIAAguIB3AAIAACiIgpAAIgCg3QgQAegcAQQgbAPgjAAQg+AAgogsgAkWgzQgdggAAgzQAAgzAdggQAeggAvAAQAvAAAeAgQAcAgAAAzQAAAzgcAgQgeAfgvAAQgvAAgegfgAjxi8QgPATAAAjQAAAjAPASQAOAUAaAAQAaAAAPgUQAOgTAAgiQAAgjgPgTQgOgTgagBQgZABgPATgAnigoQgagVgEgfIAyAAQACAQAOAIQAOAJAVAAQATAAALgIQALgHAAgMQAAgJgHgGQgHgGgRgEIgngIQgegHgQgPQgQgQAAgYQAAgeAXgSQAZgUAmAAQAgAAAVAMIALAHQAYATAEAeIgxAAQgCgNgLgIQgMgJgSAAQgTAAgKAIQgJAGAAAMQAAAJAGAHQAHAGAQACIApAHQALACAKAFQAQAGAJALQAQAPAAAZQAAAfgYATQgIAGgJAFQgUAJgdAAQgqAAgcgUgAqIghQgTgOgOgWIAAAsIgyAAIAAkyIAyAAIAACCQAOgXAUgMQAUgNAWAAQAlAAAWAgQAVAeAAA0QAAAzgWAgQgVAfgmAAQgWABgUgNgAqVi7QgVAVAAAfQAAAfAVAVQATAUAVgBQAVABAMgTQAMgTAAgiQAAgjgMgSQgLgSgVAAQgWAAgTATgABGgZIAAh7QAAgdgJgOQgJgNgVAAQgWAAgQATQgSAUAAAgIAABsIgxAAIAAjbIAxAAIAAAqQANgUARgNQAVgOAWAAQAjAAASAWQATAYAAAoIAACKgAsxgZIAAjbIAyAAIAADbgAs1kTIAAg4IA7AAIAAA4g");
	this.shape_57.setTransform(150.0324,300,0.7041,0.7041);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_11}]}).to({state:[{t:this.instance_11}]},6).to({state:[{t:this.shape_52},{t:this.shape_51,p:{scaleX:0.7041,scaleY:0.7041,x:149.985,y:299.9613}}]},1).to({state:[{t:this.shape_53}]},17).to({state:[{t:this.shape_54}]},19).to({state:[{t:this.shape_55}]},19).to({state:[{t:this.shape_55}]},19).to({state:[{t:this.shape_56}]},19).to({state:[{t:this.shape_55}]},19).to({state:[{t:this.shape_57}]},19).to({state:[{t:this.shape_51,p:{scaleX:0.7041,scaleY:0.7041,x:149.985,y:299.9613}}]},19).to({state:[{t:this.instance_11}]},13).to({state:[{t:this.instance_11}]},21).to({state:[{t:this.shape_51,p:{scaleX:0.5722,scaleY:0.5722,x:79.7747,y:419.9807}}]},1).to({state:[]},160).wait(97));
	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({startPosition:0},6,cjs.Ease.quadIn).to({_off:true},1).wait(163).to({_off:false,regX:-115.5,regY:33.8,x:68.7,y:323.8,startPosition:8},0).to({scaleX:0.5722,scaleY:0.5722,x:13.7,y:439.35},21,cjs.Ease.quartInOut).to({_off:true},1).wait(257));
	this.timeline.addTween(cjs.Tween.get(instance_11Filter_1).to(new cjs.ColorFilter(1,1,1,1,0,0,0,0), 6,cjs.Ease.quadIn).wait(163).to(new cjs.ColorFilter(1,1,1,1,0,0,0,0), 0).wait(278));

	// BG
	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#590053").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_58.setTransform(150,300);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#2ECC75").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_59.setTransform(150,300);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#4F0049").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_60.setTransform(150,300);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_61.setTransform(150,300);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFE").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_62.setTransform(150,300);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFEFD").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_63.setTransform(150,300);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFDFA").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_64.setTransform(150,300);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFBF6").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_65.setTransform(150,300);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFAF3").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_66.setTransform(150,300);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFF9F2").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_67.setTransform(150,300);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFF9F1").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_68.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_58}]},43).to({state:[]},19).to({state:[{t:this.shape_59}]},19).to({state:[]},19).to({state:[{t:this.shape_60}]},19).to({state:[]},19).to({state:[{t:this.shape_61}]},19).to({state:[{t:this.shape_61}]},284).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).wait(1));

	// BG
	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFF9F1").s().p("EgXlAvCMAAAheDMAvLAAAMAAABeDg");
	this.shape_69.setTransform(150,300);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#304F30").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_70.setTransform(150,300);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFB1EB").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_71.setTransform(150,300);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FF5427").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_72.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_69}]}).to({state:[]},43).to({state:[{t:this.shape_70}]},19).to({state:[]},19).to({state:[{t:this.shape_71}]},19).to({state:[]},19).to({state:[{t:this.shape_72}]},19).to({state:[]},19).to({state:[]},286).wait(6));

	this.filterCacheList = [];
	this.filterCacheList.push({instance: this.instance_11, startFrame:1, endFrame:6, x:-117, y:-36, w:235, h:72});
	this.filterCacheList.push({instance: this.instance_11, startFrame:0, endFrame:0, x:-117, y:-36, w:235, h:72});
	this.filterCacheList.push({instance: this.instance_11, startFrame:7, endFrame:7, x:-117, y:-36, w:235, h:72});
	this.filterCacheList.push({instance: this.instance_11, startFrame:170, endFrame:170, x:-117, y:-36, w:235, h:72});
	this.filterCacheList.push({instance: this.instance_11, startFrame:171, endFrame:191, x:-117, y:-36, w:235, h:72});
	this.filterCacheList.push({instance: this.instance_11, startFrame:192, endFrame:192, x:-117, y:-36, w:235, h:72});
	this.filterCacheList.push({instance: this.instance_11, startFrame:352, endFrame:449, x:-117, y:-36, w:235, h:72});
	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,302,602);


// stage content:
(lib.banner_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Stage
	this.instance = new lib._Stage();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));
	this.instance.addEventListener("tick", AdobeAn.handleFilterCache);

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,152,302);
// library properties:
lib.properties = {
	id: 'C38F8E925B074A239B4A15BB5DD6BAC8',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/p01.jpg?1757436846945", id:"p01"},
		{src:"images/p02.jpg?1757436846945", id:"p02"},
		{src:"images/p03.jpg?1757436846945", id:"p03"},
		{src:"images/p04.jpg?1757436846945", id:"p04"},
		{src:"images/p05.jpg?1757436846945", id:"p05"},
		{src:"images/p06.jpg?1757436846945", id:"p06"},
		{src:"images/p07.jpg?1757436846945", id:"p07"},
		{src:"images/p08.jpg?1757436846945", id:"p08"},
		{src:"images/p09.jpg?1757436846945", id:"p09"},
		{src:"images/p12.jpg?1757436846945", id:"p12"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C38F8E925B074A239B4A15BB5DD6BAC8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;