(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,318,90]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Pic4 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.g_txt03AD123 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AotBxIAAgSIAOAAQAQAAAEgOIAGgQIgHAAIgjhoIgCgCIgLgBIAAgLIAyAAIAAALIgOABIgDACIAdBSIABAAIAchSIgCgCIgOgBIAAgLIAqAAIAAALIgLABIgCACIgtCCQgDANgIAFQgHAFgMAAIgOgBgANQAGIAAhdIgCgDIgOAAIAAgKIA1AAIAAAKIgPAAIgBADIAABfQAAAuAogBQAaAAAKgPQAHgLAAgWIAAhcIgBgDIgQAAIAAgKIAvAAIAAAKIgOAAIgCADIAABdQAAA9g6AAQg8AAAAg9gAGAAyIAAAAQgPARgaAAQgOgBgIgHQgJgJAAgQQAAgjAsAAIAcAAIAAgSQABgYgXAAQgXAAAAAfIgTAAIgBgGQAAgOAIgIQALgNAagBQAoAAAAAmIAAA8QAAAJAGAAIAHgBIADAHQgJAIgJAAQgRAAgBgRgAFPAgQAAAVAUgBQANAAAIgJQAJgKgBgQIAAgIIgUAAQgdAAAAAXgAI5AxIAAgtIAKAAQACAXAMAOQAMANATAAQASAAAKgJQAIgKABgOQAAgNgHgIQgGgGgTgEQgggIgLgGQgPgKAAgVQAAgRALgNQANgQAdAAQAfAAASANIAAAmIgKAAQgEgTgLgLQgKgLgPAAQgOAAgIAJQgIAIAAAMQAAAOAHAGQAJAGAXAFQAdAFAMANQALAMAAASQAAASgMANQgPASghABQggAAgXgSgAG8AhIAAhKIgVAAIAAgJQARgCAHgJQAGgIACgRIAJAAIAAAhIAjAAIAAAMIgjAAIAABBQAAAQACAFQAEAHAKAAQAKAAAKgJIAGAGQgNASgSAAQgggBABghgAAEAJQgBghARgQQANgNATgBQAXABAMANQAMANAAAZIAAAJIhKAAIAAADQAAAqAjAAQAQAAAQgNIAGAFQgGAKgNAHQgMAGgOAAQgxAAAAg6gABOgDQAAgogaAAQgYAAgCAoIA0AAIAAAAgAhnA1IAAgfIAJAAQABAPAKAKQAKAJAMAAQANAAAHgHQAFgGAAgKQAAgQgXgEQgYgEgJgGQgLgHABgQQAAgMAJgJQALgMAWgBQAXABAPAJIAAAdIgIAAQgEgNgJgIQgJgHgKAAQgJAAgFAGQgGAFAAAHQAAAJAGAFQAGADAPAEQAYADAKAJQAGAJABAOQAAAMgJAJQgMAPgZAAQgYAAgTgOgAm8AGQgBgYAMgRQAOgTAbAAQAxAAAAA8QAAAcgLAPQgMASgdAAQgxAAAAg9gAmhgbQgFAMAAAWQAAAxAdgBQASABAFgTQAEgKAAgaQAAgsgbAAQgSAAgGAQgArcAJQgBghARgQQANgNATgBQAXABAMANQAMANAAAZIAAAJIhKAAIAAADQABAqAhAAQARAAAQgNIAGAFQgGAKgNAHQgMAGgOAAQgxAAAAg6gAqTgDQABgogaAAQgZAAgBAoIAzAAIAAAAgAtPAJQAAghAQgQQANgNAUgBQAXABALANQAMANABAZIAAAJIhKAAIAAADQAAAqAiAAQARAAAPgNIAHAFQgHAKgMAHQgMAGgOAAQgyAAAAg6gAsFgDQAAgogZAAQgZAAgBAoIAzAAIAAAAgAvVAxIAAgtIAKAAQACAXAMAOQAMANATAAQASAAAJgJQAJgKAAgOQAAgNgFgIQgIgGgRgEQgigIgKgGQgPgKAAgVQAAgRALgNQAOgQAcAAQAfAAASANIAAAmIgKAAQgEgTgLgLQgLgLgPAAQgNAAgIAJQgIAIAAAMQAAAOAIAGQAIAGAWAFQAdAFANANQALAMAAASQAAASgLANQgQASghABQghAAgWgSgAjwBCIAAgVIgBAAQgMAVgYAAQglAAAAgkIAAg7QAAgHgDgBIgMgCIAAgIIAhgHIADAAIAABKQAAAOADAHQAEAKAQAAQANAAAJgLQAHgLAAgOIAAgsQAAgHgEgBIgLgCIAAgIIAhgHIADAAIAABjQgBAHAEABIAMACIAAAIIggADgAK/BBIAAgLIAPAAIACgCIAAiLIgCgCIgPgBIAAgKIB2AAIAAAmIgJAAQgFgSgHgFQgFgEgSAAIgjAAIAABEIAWAAQARAAAEgFQADgCADgQIAJAAIAAA5IgJAAQgCgPgEgDQgFgFgPAAIgXAAIgBA+IACACIAPAAIAAALgACzBBIAAgLIAQAAIABgCIAAhdIgRAAIAAgMIARAAIAAgXQABgSAIgJQAKgKAQAAQAfAAAAAfIAAACIgUAAQAAgLgCgFQgDgGgHAAQgNgBAAATIAAAfIAdAAIAAAMIgdAAIAABdIACACIASAAIAAALgABzBBIAAgLIAPAAIACgCIAAiOQgBgHgDAAIgMgDIAAgIIAhgFIACAAIAAClIACACIAOAAIAAALgAjBBBIAAgLIANAAIADgCIAAhRQAAgGgEgCIgMgBIAAgJIAggHIADAAIgBAaIABAAQAMgaAaAAQAHAAAFACIgDAUQgIgDgIAAQgNAAgJAMQgHAMAAASIAAAtIABACIANAAIAAALg");
	this.shape.setTransform(101.15,17.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3,6.4,196.4,22.799999999999997);


(lib.g_txt02AD2new = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EAgaACJIAAkRIB3AAQAdALAAAjIAAC1QAAAjgdALgEAhXABXIAXAAIAEgEIAAimIgEgDIgXAAgAeSCJIAAkRIA9AAIAADYIA+AAIAAA5gAdSCJIgjhrIgGAAIAABrIg9AAIAAkRIB2AAQAeALAAAjIAAA6QAAAggZALIAgBXIAAAngAcpgSIAWAAIAEgEIAAg9IgEgDIgWAAgAZiCJQgdgLAAgjIAAi1QAAgjAdgLIBZAAQAeALAAAjIAAC1QAAAjgeALgAaChTIAACmIADAEIATAAIAEgEIAAimIgEgDIgTAAgAXNCJIgLilIgEAAIgMClIhKAAIgfjhIAAgwIA2AAIAMChIAEAAIALihIBLAAIAMChIADAAIAMihIA2AAIAAAwIgeDhgASCCJIAAkRIB+AAIAAA5IhBAAIAAAyIA9AAIAAA4Ig9AAIAAA1IBCAAIAAA5gAQzCJIAAhrIgbAAIAABrIg9AAIAAkRIA9AAIAABuIAbAAIAAhuIA8AAIAAERgANnCJIAAjYIgrAAIAAg5ICUAAIAAA5IgsAAIAADYgALCCJIgmh4IgEAAIAAB4Ig1AAIAAkRIA1AAIAnB4IADAAIAAh4IA1AAIAAERgAH9CJIAAg5IALAAIAAifIgLAAIAAg5IBTAAIAAA5IgLAAIAACfIALAAIAAA5gAE9CJQgegLAAgjIAAg2IA9AAIAAAuIADAEIAUAAIADgEIAAgpIgDgGIg/gcQgNgGgEgJQgEgIAAgRIAAg6QAAgjAegLIBYAAQAeALAAAjIAAAzIg9AAIAAgsIgDgDIgUAAIgDADIAAAoIAFAGIA9AZQANAFAEAKQAEAJAAARIAAA+QAAAjgeALgACPCJIAAkRIB9AAIAAA5IhAAAIAAAyIA8AAIAAA4Ig8AAIAAA1IBCAAIAAA5gAAoCJIAAg5IAMAAIAAifIgMAAIAAg5IBUAAIAAA5IgMAAIAACfIAMAAIAAA5gAhLCJIAAjYIgrAAIAAg5ICTAAIAAA5IgrAAIAADYgAjVCJIAAg5IALAAIAAifIgLAAIAAg5IBTAAIAAA5IgLAAIAACfIALAAIAAA5gAlcCJQgegLAAgjIAAg2IA9AAIAAAuIADAEIAUAAIADgEIAAgpIgDgGIg/gcQgNgGgEgJQgEgIAAgRIAAg6QAAgjAegLIBYAAQAeALAAAjIAAAzIg9AAIAAgsIgDgDIgUAAIgDADIAAAoIAFAGIA9AZQANAFAEAKQAEAJAAARIAAA+QAAAjgeALgAm4CJIgjhrIgGAAIAABrIg9AAIAAkRIB2AAQAeALAAAjIAAA6QAAAggZALIAgBXIAAAngAnhgSIAWAAIAEgEIAAg9IgEgDIgWAAgAqwCJIAAkRIB9AAIAAA5IhAAAIAAAyIA8AAIAAA4Ig8AAIAAA1IBCAAIAAA5gAs0CJIgjjjIAAguIA5AAIARDEIAEAAIARjEIA5AAIAAAuIgjDjgAu6CJIAAg5IAMAAIAAifIgMAAIAAg5IBUAAIAAA5IgMAAIAACfIAMAAIAAA5gAwCCJIgmh4IgEAAIAAB4Ig1AAIAAkRIA1AAIAnB4IADAAIAAh4IA1AAIAAERgAzmCJQgegLAAgjIAAjjIA9AAIAADbIAEAEIAPAAIAEgEIAAjbIA9AAIAADjQAAAjgeALgA3GCJQgegLAAgjIAAi1QAAgjAegLIBZAAQAdALAAAjIAAC1QAAAjgdALgA2nhTIAACmIAEAEIATAAIAEgEIAAimIgEgDIgTAAgA6LCJIAAhcQAAggAWgJIBCgdIAAg6IgEgDIgTAAIgEADIAAAoIg9AAIAAgvQAAgjAegLIBZAAQAdALAAAjIAABFQAAARgDAHQgFALgNAGIhCAdIAAAfIBXAAIAAA5gA9nCJIAAkRIB3AAQAdALAAAjIAABXQAAAigdALIg6AAIAABfgA8qgHIAXAAIAEgEIAAhIIgEgDIgXAAgA/wCJQgegLAAgjIAAi1QAAgjAegLIBZAAQAdALAAAjIAAC1QAAAjgdALgA/RhTIAACmIAEAEIATAAIAEgEIAAimIgEgDIgTAAgEgiCACJIAAjYIgrAAIAAg5ICUAAIAAA5IgsAAIAADYg");
	this.shape.setTransform(312.625,18.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgjtADFIAAmJMBHbAAAIAAGJg");
	this.shape_1.setTransform(313.625,18.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Small_Text
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ALpAzQAAgBAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgLQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAHACQAHAAAEgEQAEgDAAgHIAAAAIgBAAQgEAFgIAAQgIAAgFgEQgGgEgDgHQgBgFAAgIQAAgIACgFQACgHAGgEQAFgEAHAAQAIAAAFAFIABABIAAgBIAAgEIABAAIANAAIABAAIAAACIAAAwQABAPgJAGQgJAGgNAAgALwgMIgDAFQgCAEAAAEQAAAGACACQABAEACACQADABADAAQADAAACgBIAEgFIABgJIgBgIQgBgDgDgCQgCgCgDABQgDgBgDACgArEAzQgBgBAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIABgLQAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBABAAIAGACQAHAAAFgEQADgDAAgHIAAAAIAAAAQgFAFgHAAQgIAAgGgEQgGgEgDgHQgBgFAAgIQAAgIACgFQACgHAGgEQAFgEAIAAQAIAAAFAFIAAABIAAgBIAAgEIABAAIAOAAIABAAIAAACIAAAwQAAAPgIAGQgJAGgNAAgAq+gMIgDAFQgCAEABAEQgBAGACACQABAEACACQADABAEAAQADAAACgBIAEgFIAAgJIAAgIQgCgDgCgCQgCgCgEABQgDgBgDACgACgAyIgBAAIAAgBIAAhJIAAgCIABAAIAOAAIABAAIAAAFIAAABIABgBQAEgGAIAAQAHAAAGAFQAGADACAIQACAFAAAIQAAAHgCAGQgCAHgGAEQgFAFgJAAQgHgBgEgFIgBgBIAAABIAAAZIgBAAgACxgJQgCAEAAAGQAAAHACAFQADAEAFAAQAFAAADgEQACgEAAgIQAAgGgCgEQgDgFgFABQgFgBgDAFgANRApQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIADgZIACgCIALAAQABAAAAAAQAAAAAAAAQAAABAAAAQABAAAAABIgHAZIgCACgAPIAYQgHgHAAgLIAAgcQAAgMAHgGQAHgIAMABQANgBAGAIQAIAGAAAMIAAAcQAAALgIAHQgGAGgNABQgMgBgHgGgAPTgfQgCADAAAFIAAAdQAAAFACAEQADACAFAAQAFAAADgCQADgEAAgFIAAgdQAAgFgDgDQgDgDgFAAQgFAAgDADgAMkAcQgFgCgDgDQgDgEgBgFIAAgCIACAAIAMAAIABAAIAAABQAAADADABQADABADAAIAHgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAIgHgDIgIgCQgGgDgFgDQgEgCAAgHQAAgIAGgFQAHgFAKAAQAHAAAFADQAGABACAFQAEAEAAAFIgBABIgBAAIgMAAIgBAAIAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgDgBgEAAIgGABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABIAHACIAEABIADABQAHACAFADQAEADABAHQgBAIgGAEQgHAGgKAAQgHgBgGgCgAHXAaQgFgEgBgIQAAgIAHgGQAFgDAMAAIALAAIABAAIAAgDQgBgDgCgCQgCgCgFAAIgFABQgBAAAAAAQgBABAAAAQAAABgBAAQAAABAAAAIgBABIgOgCIgBgBQAAgEAEgEQADgEAGgCQAEgCAHAAQAHAAAGADQAGACADAEQADAEAAAGIAAAkIAAABIgBABIgOAAIAAgBIAAgBIAAgEIgBAAIAAAAQgFAHgKAAQgIgBgGgEgAHkAHQgDACABAEQAAAAAAABQAAABAAAAQAAABABAAQAAABAAAAQACACAEAAQAFAAADgDQADgCABgEIAAgEIgBAAIgIAAQgFAAgDABgAEgAaQgGgFgDgHQgBgFgBgIQABgHABgFQADgIAGgDQAHgFAIAAQAKAAAGAFQAHAEACAHIABADIAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAIgNACIgCgBIAAgCQAAgDgDgBQgDgCgEAAQgDgBgDACQgCACgBADIgBAIIABAJQABADACACQADACADAAQAEAAADgCQACgBABgDIAAgCIAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIANACIABACIgBADQgCAHgHAEQgGAEgKABQgIgBgHgEgADfAaQgGgEABgIQAAgIAFgGQAHgDAKAAIAMAAIAAAAIAAgDQAAgDgCgCQgCgCgFAAIgFABQgBAAAAAAQgBABAAAAQAAABgBAAQAAABAAAAIgCABIgMgCIgCgBQAAgEADgEQAEgEAFgCQAFgCAHAAQAIAAAFADQAGACADAEQADAEAAAGIAAAkIgBABIgBABIgMAAIgBgBIgBgBIAAgEIAAAAIgBAAQgEAHgKAAQgIgBgGgEgADsAHQgDACAAAEQAAAAABABQAAABAAAAQAAABABAAQAAABABAAQABACAEAAQAFAAADgDQADgCAAgEIAAgEIAAAAIgIAAQgFAAgDABgAheAZQgGgFgDgHQgBgGAAgGQAAgFABgGQADgHAGgFQAGgFAKAAQAJAAAGAFQAHAEACAIQACAGAAAFQAAAGgCAFQgCAJgHAEQgGAGgJAAQgJAAgHgGgAhUgLQgDABgBAFIgBAGIAAAIIAFAGQACACAEAAQAEAAACgCQADgDABgDIABgIIgBgGQgCgFgDgBQgCgCgDAAQgEAAgCACgAjkAaQgGgEAAgIQAAgIAGgGQAGgDALAAIALAAIABAAIAAgDQAAgDgCgCQgCgCgFAAIgFABQgBAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAIgBABIgNgCIgCgBQABgEADgEQAEgEAFgCQAFgCAHAAQAHAAAGADQAFACAEAEQADAEAAAGIAAAkIgBABIgBABIgNAAIgBgBIAAgBIAAgEIgBAAIAAAAQgFAHgKAAQgIgBgFgEgAjYAHQgCACAAAEQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAQACACAEAAQAFAAADgDQADgCAAgEIAAgEIgBAAIgIAAQgEAAgEABgAkYAaQgHgFgDgHQgBgFAAgIQAAgHABgFQADgIAHgDQAHgFAIAAQAJAAAHAFQAGAEADAHIABADIAAABQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgNACIgBgBIAAgCQgBgDgDgBQgCgCgEAAQgDgBgDACQgDACAAADIgBAIIABAJQAAADADACQADACADAAQAEAAACgCQACgBACgDIAAgCIAAAAQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIANACIABACIAAADQgDAHgGAEQgHAEgJABQgIgBgHgEgAlYAZQgFgFgBgJIAAglIACAAIANAAIAAAAIAAAhQABAFACADQADACADAAQAEAAADgCQACgDAAgDIAAghIABgCIABAAIANAAIABAAIAAA3IgBABIgNAAIgBgBIgBgBIAAgEIAAAAQgFAHgIAAQgJgBgFgFgAmTAaQgFgEgCgHQgCgGgBgIQABgHACgFQACgHAGgFQAFgEAIAAQAIAAAEAGIAAAAIABAAIAAgZIABgBIANAAIABABIAAABIAABJIAAABIgBABIgNAAIgBgBIAAgFIgBAAIAAAAQgEAHgIAAQgIgBgGgEgAmKgKQgCAFgBAHQAAAGACAFQADAEAGAAQAFAAACgEQACgFAAgHQAAgGgCgFQgCgDgFAAQgGAAgCADgApNAaQgGgEgDgIQgCgFAAgJQAAgFABgFQACgIAHgEQAHgFAIAAQALAAAGAHQAIAFABAMIAAAIQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgiAAQgBAAAAAAIABAFQAEAGAIAAQAIAAAEgFIAAgBIABAAIAIAIIAAABIAAABQgEAFgFACQgGACgHABQgJgBgHgEgApIgHIgBAEIABAAIATAAIABAAIgCgDQgBgEgCgCQgCgCgEABQgHAAgCAGgAt0AcQgGgCgDgDQgDgEAAgFIAAgCIABAAIAMAAIABAAIAAABQAAADAEABQACABAEAAIAGgBQABAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBAAIgGgDIgIgCQgHgDgFgDQgDgCAAgHQgBgIAHgFQAGgFAKAAQAIAAAFADQAFABADAFQADAEAAAFIAAABIgBAAIgMAAIgBAAIgBgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQgDgBgEAAIgFABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABIAHACIADABIADABQAIACAFADQAEADAAAHQAAAIgHAEQgGAGgLAAQgHgBgFgCgAuwAaQgHgEgCgIQgCgFgBgJQABgFABgFQACgIAHgEQAHgFAIAAQALAAAHAHQAGAFACAMIAAAIQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgiAAQgBAAABAAIAAAFQADAGAJAAQAHAAAFgFIABgBIAAAAIAIAIIABABIgBABQgDAFgGACQgGACgHABQgJgBgHgEgAurgHIgBAEIABAAIATAAIAAAAIAAgDQgBgEgCgCQgDgCgEABQgHAAgCAGgAFcAbQgFgDAAgJIAAgcIgBAAIgGAAIgBgBIAAgBIAAgJIAAgCIABAAIAGAAIABgBIAAgNIABgBIAMAAIABABIAAANIABABIALAAIABAAIAAAMIgBABIgLAAIgBAAIAAAWQABAEABACQACABADAAIADAAIABABIABAAIAAALQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABgBAAIgGAAQgJAAgEgDgAijAbQgFgDABgJIAAgcIgBAAIgGAAIgBgBIgBgBIAAgJIABgCIABAAIAGAAIABgBIAAgNIABgBIAMAAIABABIAAANIABABIALAAIABAAIAAAMIgBABIgLAAIgBAAIAAAWQAAAEABACQACABAEAAIADAAIABABIABAAIAAALQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIgGAAQgKAAgEgDgARhAeIgBgBIAAgSIgBgCIgjAAIAAgBIAAgIIAAgBIAUgtIABgBIAOAAIABABIAAABIgSAqIAAAAIARAAIABAAIAAgPIABgBIAMAAIABABIABABIAAAOIABAAIAEAAIABABIAAAAIAAAKIAAABIgFAAIgBACIAAARIgBABIgBABgAQBAeIgBgBIgBgBIAAgKIABgCIAZgZQAKgLAAgGQgBgDgCgCQgDgDgEAAQgFAAgDADQgCACAAAEIAAAEIgBAAIgOAAIgBAAIAAgBIAAgGQABgFADgFQADgFAGgCQAFgCAIAAQAHgBAGADQAGAEADAEQADAGAAAFQAAAFgCAFIgHALIgTATIgCABIAAABIAfAAIAAAAIABABIAAALIgBABIAAABgAOFAeIgBgBIgBgBIAAgKIABgCIAYgZQALgLgBgGQAAgDgCgCQgDgDgFAAQgEAAgDADQgDACAAAEIAAAEIAAAAIgOAAIgBAAIAAgBIAAgGQABgFADgFQADgFAGgCQAGgCAGAAQAJgBAFADQAGAEADAEQADAGAAAFQAAAFgCAFIgHALIgTATIgCABIAAABIAfAAIAAAAIAAABIAAALIAAABIAAABgALEAeIgBgBIAAggQAAgFgCgDQgDgDgEABQgEgBgDADQgDADABAFIAAAgIgBABIgOAAIgBgBIAAgBIAAg0IAAgCIABAAIAOAAIABAAIAAAFIAAABIABAAQAEgHAIAAQAJAAAGAGQAGAFAAAJIAAAjIgBABIgBABgAKHAeIgBgBIgBgBIAAg1IABgBIAPAAIAAA3IgBABgAJvAeIgCgBIgLgaIAAAAIgBAAIgHAJIAAAAIAAARIgBABIgNAAIgBgBIAAgBIAAhJIAAgBIABgBIANAAIABABIAAAmIAAAAIABAAIAPgSIABAAIAPAAIABAAIAAACIgOASIAAAAIAQAiIAAABQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAgAIyAeIgBgBIAAggQAAgFgDgDQgDgDgEABQgEgBgCADQgDADAAAFIAAAgIgBABIgNAAIgBgBIAAgBIAAg0IAAgCIABAAIANAAIABAAIAAAFIABABIAAAAQAFgHAIAAQAJAAAGAGQAFAFAAAJIAAAjIgBABIgBABgAG9AeIgCgBIgOgeIAAgBIgKAAIgBABIAAAeIgBABIgOAAIgBgBIAAgBIAAhJIAAgBIABgBIAgAAQAHAAAFADQAFADAEAFQACAGAAAHQABAHgEAFQgEAGgGACIgBABIAPAeIAAABIgBABgAGiggIAAASIABABIANAAQAGgBACgCQADgDAAgEQAAgEgDgDQgCgDgGAAIgNAAIgBABgACGAeIgBgBIgBgBIAAggQAAgEgBgDQgDgDgEABQgEgBgCADQgCADgBAEIAAAgIAAABIgBABIgMAAIgBgBIgBgBIAAggQAAgEgDgDQgBgDgEABQgEAAgCACQgDABAAAFIAAAiIgCABIgMAAIgBgBIgBgBIAAg0IABgCIABAAIAMAAIACAAIAAAGIAAAAIABAAQAEgHAJAAQAGAAAEADQAEABADAFIAAAAQACgFAFgBQAEgDAFAAQAJAAAEAFQAFAGAAAJIAAAkIgBABgAApAeIgBgBIAAgBIAAhJIAAgBIABgBIANAAIABABIAABLIgBABgAgIAeIgBgBIAAggQAAgFgCgDQgDgDgEABQgEgBgCADQgDADAAAFIAAAgIgBABIgNAAIgBgBIAAgBIAAg0IAAgCIABAAIANAAIABAAIAAAFIAAABIABAAQAFgHAIAAQAJAAAEAGQAGAFAAAJIAAAjIAAABIgBABgAiBAeIgBgBIgBgBIAAg1IABgBIAOAAIAAA3IgBABgAnZAeIgBgBIAAgBIAAhJIAAgBIABgBIAzAAIABABIAAANIgBAAIgkAAIgBABIAAARIABAAIAYAAIAAABIAAAMIAAAAIgYAAIgBABIAAAQIABABIAkAAIABAAIAAANIgBABgAoaAeIgBgBIgBgBIAAg0IABgCIABAAIANAAIABAAIAAAGIAAAAIABAAQAEgHAIAAQAEAAACABIABADIgCAMQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAgBIgEAAIgDAAQgDAAgDADQgDADAAAEIAAAeIgBABgApwAeIgBgBIAAggQgBgFgCgDQgCgDgFABQgEgBgCADQgDADAAAFIAAAgIgBABIgNAAIgBgBIAAgBIAAhJIAAgBIABgBIANAAIABABIAAAZIABABIAAAAQAFgHAIAAQAJAAAGAGQAFAFAAAJIAAAjIgBABIgBABgArrAeIgBgBIAAgBIAAg1IAAgBIAQAAIAAA3IgBABgAsGAeIgBgBIgBgBIAAgdIAAgBIgYAAIgBABIAAAeIgBABIgNAAIgBgBIAAgBIAAhJIAAgBIABgBIANAAIABABIAAAfIABAAIAYAAIAAAAIAAgeIABgBIABgBIANAAIABABIAAABIAABJIAAABIgBABgAvTAeIgBgBIgBgBIAAggQAAgEgCgDQgCgDgEABQgDgBgDADQgDADAAAEIAAAgIAAABIgBABIgMAAIgBgBIgBgBIAAggQAAgEgDgDQgCgDgDABQgEAAgDACQgCABAAAFIAAAiIgBABIgOAAIgBgBIAAgBIAAg0IAAgCIABAAIAOAAIABAAIAAAGIAAAAIABAAQAEgHAJAAQAGAAAEADQAEABACAFIABAAQADgFADgBQAFgDAFAAQAIAAAGAFQAEAGAAAJIAAAkIgBABgAwwAeIgBgBIgBgBIAAg1IABgBIAPAAIAAA3IgBABgAxeAeIgBgBIAAgBIAAg8IgBgBIgTAAIgBAAIAAgCIAAgKIAAgBIABgBIA4AAIAAABIAAANIAAAAIgUAAIgBABIAAA8IAAABIgBABgAKHgjQgCgDAAgDQAAgEACgCQACgDAFAAQADAAADADQACACABAEQgBADgCADQgDADgDAAQgEAAgDgDgAiBgjQgCgDAAgDQAAgEACgCQACgDAEAAQAEAAACADQADACAAAEQAAADgDADQgCADgEAAQgDAAgDgDgArqgjQgCgDgBgDQABgEACgCQACgDAEAAQAEAAADADQACACAAAEQAAADgCADQgDADgEAAQgEAAgCgDgAwwgjQgCgDAAgDQAAgEACgCQADgDAEAAQADAAADADQACACABAEQgBADgCADQgDADgDAAQgEAAgDgDg");
	this.shape_2.setTransform(425.6,52.55);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(85,-1.2,457.29999999999995,58.900000000000006);


(lib.g_txt01AD2New = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANfFiIAAk9ICRAAIAABCIhLAAIAAA5IBHAAIAABCIhHAAIAAA+IBNAAIAABCgALFFiIgokIIAAg1IBCAAIAUDjIAFAAIATjjIBCAAIAAA1IgoEIgAIrFiIAAhCIAOAAIAAi5IgOAAIAAhCIBhAAIAABCIgNAAIAAC5IANAAIAABCgAHhFiIgoh8IgIAAIAAB8IhGAAIAAk9ICJAAQAiANAAAoIAABDQAAAmgdANIAmBlIAAAtgAGxCtIAbAAIAEgFIAAhFIgEgFIgbAAgAEOFiIAAh8IgeAAIAAB8IhHAAIAAk9IBHAAIAAB/IAeAAIAAh/IBHAAIAAE9gAAjFiIAAj7IgyAAIAAhCICrAAIAABCIgzAAIAAD7gANhgjIAAk+ICRAAIAABDIhLAAIAAA9IBHAAIAABDIhHAAIAAB7gALDgjIAAk+IBGAAIAAD7IBJAAIAABDgAIagjIAAk+ICRAAIAABDIhLAAIAAA5IBHAAIAABCIhHAAIAAA9IBNAAIAABDgAF9gjQgigNAAgoIAAg/IBGAAIAAA2IAEAEIAWAAIAFgEIAAgxIgEgFIhJghQgPgHgFgMQgEgJAAgUIAAhEQAAgoAigNIBnAAQAiANAAAoIAAA8IhGAAIAAgzIgFgEIgWAAIgEAEIAAAuIAGAHIBHAdQAPAGAFANQAEAKAAAUIAABIQAAAogiANgAETgjIgph7IgHAAIAAB7IhHAAIAAk+ICJAAQAjANAAAoIAABEQAAAmgeANIAmBlIAAAtgADjjYIAaAAIAEgFIAAhGIgEgEIgaAAgAACgjQgigNAAgoIAAkJIBGAAIAAEAIAEAEIASAAIAEgEIAAkAIBGAAIAAEJQAAAogiANgAi/gjQgigNAAgoIAAjUQAAgoAigNIBnAAQAiANAAAoIAADUQAAAogiANgAibkjIAADCIAEAEIAXAAIAEgEIAAjCIgEgEIgXAAgAlugjIAAh9Ig1iLIAAg2IBCAAIAUBtIAFAAIAThtIBCAAIAAA2Ig0CLIAAB9gAqJgjIAAk+ICRAAIAABDIhLAAIAAA5IBHAAIAABCIhHAAIAAA9IBNAAIAABDgAsygjIAAk+ICRAAIAABDIhLAAIAAA5IBHAAIAABCIhHAAIAAA9IBNAAIAABDgAvPgjQgigNAAgoIAAg/IBGAAIAAA2IAEAEIAWAAIAFgEIAAgxIgEgFIhJghQgPgHgFgMQgEgJAAgUIAAhEQAAgoAigNIBnAAQAiANAAAoIAAA8IhGAAIAAgzIgFgEIgWAAIgEAEIAAAuIAGAHIBHAdQAPAGAFANQAEAKAAAUIAABIQAAAogiANg");
	this.shape.setTransform(-104.075,15.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-205.1,-19.5,202.1,70.7);


(lib.g_SFULogo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// icon
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiWBIQgLgCgNgGQAEgIACgNQAIAHAHADQAKAFAMAAQANAAAHgGQAIgHAAgLQAAgKgLgIQgFgEgOgGQgOgGgGgDQgOgKAAgTQAAgRALgLQAMgMAVAAQAJAAAMADIANAEIgDAIIgDALQgKgHgJgCQgHgDgHAAQgJAAgGAGQgGAFAAAJQAAAKAIAHIAbAPQATAIAGAJQAFAIAAAKQAAAOgKAMQgNASgdAAgABMA/QgIgGgFgHQgDgGgBgFIgBgVIgChYIANABIAMgBIgCATIgBA/IABAWQABAFADAEQAJANAZAAQAQAAAKgGIAIgHQAEgEAAgHIABgYIAAggIgBgeIgBgQIALABIAKgBIgBBPQAAAZgDALQgEAKgLAIQgOAJgaAAQgbAAgNgJgAgqBGIgLABIACgUIgBh5IA8ABIAQgBIgBAKIAAAKIgJgBIgsgBIAAAqIAZAAQANAAALgCIgBALIABAJIgxgCIAAASQAAAcABATg");
	this.shape.setTransform(72.8903,36.9128,1.5385,1.5402);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#992932").s().p("AlRCpIAAlRIKjAAIAAFRg");
	this.shape_1.setTransform(52.0052,26.0157,1.5385,1.5402);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,104,52.1);


(lib.g_arrow = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C92539").s().p("ABAC+IAAj+Ij9AAIAAh9IF7AAIAAF7g");
	this.shape.setTransform(19,19);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,38,38);


(lib.btn_CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgXA7QgLgEgGgJQgFgIAAgMIAAgDIAAgCIACgBIAUAAIACABIAAACIAAACQAAAHAHAFQAGAFALAAQAJAAAFgEQAEgEAAgGQAAgEgDgDQgCgDgFgCIgPgGQgMgEgIgFQgIgDgGgHQgGgIAAgKQAAgLAGgIQAFgIAKgFQAKgEANAAQAMAAALAFQALAFAGAIQAFAJAAALIAAADIAAACIgCAAIgUAAIgCAAIAAgCIAAgBQAAgIgGgFQgHgFgJAAQgJAAgEADQgFAEAAAGQAAAFADADQACADAGACIAQAHIAUAIQAHACAGAHQAFAHAAAMQAAAQgMAKQgMAKgVAAQgNAAgLgFg");
	this.shape.setTransform(199.175,21.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AAeA+IgCAAIAAgCIAAhNIgBgBIgBAAIgSAdQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgJAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBAAIgTgdIAAAAIgBABIAABNIAAACIgCAAIgVAAIgBAAIgBgCIAAh3IABgCIABAAIAVAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIAaAqQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAbgqQAAAAABAAQAAgBAAAAQABAAAAAAQAAAAABAAIAVAAIABAAIABACIAAB3IgBACIgBAAg");
	this.shape_1.setTransform(187.575,21.575);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AAeA+QAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgFgSIgBgBIgrAAIgBABIgFASQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgXAAIgCAAIAAgCIAnh4QAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAbAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAnB4IAAABQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAgAAAgeIgPA0QAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAfAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIgQg0IAAgBg");
	this.shape_2.setTransform(175.275,21.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AAWA+QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgVgyIgCAAIgQAAIgBAAIAAAxIgBACIgBAAIgVAAIgBAAIgBgCIAAh3IABgCIABAAIAyAAQAMAAAIAEQAJAFAEAIQAFAJAAALQAAAMgGAJQgGAIgLADIgBABIAZAzIAAABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAgUgnIAAAfIABAAIAWAAQAHAAAGgEQAEgFAAgHQAAgHgEgEQgGgFgHAAIgWAAIgBABg");
	this.shape_3.setTransform(164.1,21.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("AgXA6QgKgFgHgKQgFgKAAgNIAAgnQAAgNAFgKQAHgKAKgFQALgGAMAAQAOAAAKAGQAKAFAHAJQAFAJAAALIAAACIAAABIgCABIgVAAIgBgBIgBgBIAAgBQAAgIgGgGQgFgFgKAAQgIAAgGAGQgGAGAAAJIAAApQAAAJAGAGQAGAGAJAAQAJAAAGgFQAFgFABgIIAAgIIgBgBIgUAAIgBgBIgBgBIAAgQIABgBIABgBIArAAIACABIAAABIAAAXQAAANgFAKQgHAKgKAFQgKAGgOAAQgMAAgLgGg");
	this.shape_4.setTransform(153,21.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AgYA7QgKgGgGgLQgGgKAAgNIAAgmQAAgMAGgKQAGgLAKgGQALgFANAAQAOAAALAFQAKAGAGALQAGAKAAAMIAAAmQAAANgGAKQgGALgKAGQgLAFgOAAQgNAAgLgFgAgPgjQgGAGAAAKIAAAnQAAAKAGAGQAGAGAJAAQAKAAAGgGQAGgGAAgKIAAgnQAAgKgGgGQgGgGgKAAQgJAAgGAGg");
	this.shape_5.setTransform(142.025,21.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AAWA+QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgWgyIgBAAIgQAAIgBAAIAAAxIAAACIgCAAIgVAAIgCAAIAAgCIAAh3IAAgCIACAAIAyAAQAMAAAIAEQAJAFAFAIQAEAJAAALQAAAMgGAJQgGAIgLADIAAABIAXAzIABABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgAgUgnIAAAfIABAAIAWAAQAIAAAEgEQAFgFAAgHQAAgHgFgEQgEgFgIAAIgWAAIgBABg");
	this.shape_6.setTransform(131.3,21.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AgrA/IgBgBIgBgBIAAh4IABgCIABAAIAyAAQALgBAJAGQAJAEAFAJQAFAJAAALQAAALgFAJQgFAIgJAEQgKAFgLAAIgZAAIgBABIAAAuIAAABIgCABgAgUgmIAAAgIABABIAWAAQAIAAAFgFQAFgFAAgHQAAgIgFgFQgFgEgIgBIgWAAIgBACg");
	this.shape_7.setTransform(120.575,21.55);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgoA+IgCAAIAAgCIAAh3IAAgCIACAAIBRAAIABAAIABACIAAARIgBACIgBAAIg5AAIgBABIAAAcIABABIAlAAIABAAIABACIAAAQIgBABIgBABIglAAIgBABIAAAdIABABIA5AAIABAAIABACIAAARIgBACIgBAAg");
	this.shape_8.setTransform(106.525,21.575);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAWA+QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAIgUgyIgBAAIgRAAIgBAAIAAAxIAAACIgCAAIgVAAIgCAAIAAgCIAAh3IAAgCIACAAIAyAAQALAAAJAEQAIAFAGAIQAEAJAAALQAAAMgGAJQgGAIgLADIgBABIAYAzIABABQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAgAgUgnIAAAfIABAAIAWAAQAHAAAGgEQAEgFAAgHQAAgHgEgEQgGgFgHAAIgWAAIgBABg");
	this.shape_9.setTransform(95.9,21.575);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AgYA7QgKgGgGgLQgGgKAAgNIAAgmQAAgMAGgKQAGgLAKgGQALgFANAAQAOAAALAFQAKAGAGALQAGAKAAAMIAAAmQAAANgGAKQgGALgKAGQgLAFgOAAQgNAAgLgFgAgPgjQgGAGAAAKIAAAnQAAAKAGAGQAGAGAJAAQAKAAAGgGQAGgGAAgKIAAgnQAAgKgGgGQgGgGgKAAQgJAAgGAGg");
	this.shape_10.setTransform(84.675,21.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AgoA+IgCAAIAAgCIAAh3IAAgCIACAAIAVAAIABAAIABACIAABjIABABIA5AAIACAAIAAACIAAARIAAACIgCAAg");
	this.shape_11.setTransform(74.4,21.575);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("AgrA/IgBgBIgBgBIAAh4IABgCIABAAIAyAAQALgBAJAGQAJAEAFAJQAFAJAAALQAAALgFAJQgFAIgJAEQgKAFgLAAIgZAAIgBABIAAAuIAAABIgCABgAgUgmIAAAgIABABIAWAAQAIAAAFgFQAFgFAAgHQAAgIgFgFQgFgEgIgBIgWAAIgBACg");
	this.shape_12.setTransform(63.975,21.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AAaA+QAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgXgpQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIgXApQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgWAAIgCAAIAAgCIAjg8IAAAAIgjg7IAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAXAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAXApQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIAXgpQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAXAAIACAAIgBACIgiA7IAAAAIAiA8IABABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_13.setTransform(52.8208,21.575);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AgoA+IgCAAIAAgCIAAh3IAAgCIACAAIBRAAIABAAIABACIAAARIgBACIgBAAIg5AAIgBABIAAAcIABABIAlAAIABAAIABACIAAAQIgBABIgBABIglAAIgBABIAAAdIABABIA5AAIABAAIABACIAAARIgBACIgBAAg");
	this.shape_14.setTransform(42.275,21.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AhFBiIBghiIhghhIAVgVIB2B2Ih2B3g");
	this.shape_15.setTransform(20.45,20.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhFBiIBhhiIhhhhIAVgVIB2B2Ih2B3g");
	this.shape_16.setTransform(20.45,20.475);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AC7A7QgLgGgFgLQgGgKAAgNIAAgmQAAgMAGgKQAFgLALgGQALgFANAAQAPAAAKAFQALAGAGALQAFAKAAAMIAAAmQAAANgFAKQgGALgLAGQgKAFgPAAQgNAAgLgFgADEgjQgGAGAAAKIAAAnQAAAKAGAGQAGAGAJAAQAKAAAGgGQAGgGAAgKIAAgnQAAgKgGgGQgGgGgKAAQgJAAgGAGgAmCA7QgKgGgGgLQgGgKAAgNIAAgmQAAgMAGgKQAGgLAKgGQALgFAOAAQAOAAALAFQAKAGAGALQAGAKAAAMIAAAmQAAANgGAKQgGALgKAGQgLAFgOAAQgOAAgLgFgAl5gjQgGAGAAAKIAAAnQAAAKAGAGQAGAGAKAAQAKAAAGgGQAGgGAAgKIAAgnQAAgKgGgGQgGgGgKAAQgKAAgGAGgAL3A7QgLgFgGgIQgFgJAAgLIAAgDIAAgCIACgBIAUAAIACABIAAACIAAACQAAAHAHAFQAGAFAMAAQAJAAAFgEQAEgEAAgGQAAgEgDgDQgCgDgFgDIgQgFQgMgFgIgEQgIgDgGgIQgGgHAAgLQAAgKAGgJQAFgHAKgFQAKgEANAAQANAAALAFQALAFAGAIQAFAJAAALIAAADIAAABIgCABIgUAAIgCgBIAAgBIAAgBQAAgIgGgGQgHgEgKAAQgJgBgEAEQgFADAAAHQAAAEADADQACADAGADIARAGIAUAIQAHADAGAHQAFAHAAAMQAAAQgMAJQgMALgVAAQgOAAgLgFgAEpA6QgKgFgGgLQgGgKAAgMIAAgnQAAgNAGgKQAGgKAKgGQALgFANAAQAOAAAKAFQALAFAGAKQAFAJAAALIAAACIAAABIgCAAIgVAAIgBAAIgBgBIAAgBQAAgIgFgGQgGgGgKABQgJAAgGAFQgGAHAAAJIAAApQAAAJAGAGQAHAGAJAAQAKAAAFgFQAGgFAAgJIAAgIIgBgBIgUAAIgCAAIAAgBIAAgQIAAgBIACgBIArAAIACABIAAABIAAAXQAAANgFAKQgGAKgLAFQgKAGgOAAQgNAAgLgGgAK5A+IgCgBIAAgBIAAhOIgBgBIgBABIgSAdQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgTgdIAAgBIgBABIAABOIAAABIgCABIgVAAIgBgBIgBgBIAAh3IABgCIABAAIAVAAQABAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAIAaApQAAABAAAAQABAAAAAAQAAAAAAAAQAAAAAAgBIAbgpQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAABAAIAVAAIABAAIABACIAAB3IgBABIgBABgAI+A+QAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgFgRIgBgBIgsAAIgBABIgFARQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXAAIgCgBIAAgCIAnh3QAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAcAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAnB3IAAABQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAgAIfgeIgPA0QAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAgAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAIgQg0IAAgBgAHGA+QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgWgxIgBAAIgRAAIgBAAIAAAxIAAABIgCABIgVAAIgBgBIgBgBIAAh3IABgCIABAAIAzAAQAMgBAIAFQAJAEAFAJQAEAJAAALQAAAMgGAIQgGAJgLADIAAABIAYAyIAAABQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAGbgnIAAAeIABABIAXAAQAIAAAFgFQAEgEAAgHQAAgHgEgFQgFgEgIAAIgXAAIgBABgAB+A+QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgWgxIgBAAIgRAAIgBAAIAAAxIAAABIgCABIgVAAIgBgBIgBgBIAAh3IABgCIABAAIAzAAQAMgBAIAFQAJAEAFAJQAEAJAAALQAAAMgGAIQgGAJgLADIAAABIAYAyIAAABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgABTgnIAAAeIABABIAXAAQAIAAAFgFQAEgEAAgHQAAgHgEgFQgFgEgIAAIgXAAIgBABgAguA+IgBgBIgBgBIAAh3IABgCIABgBIAyAAQALAAAJAFQAJAFAFAJQAFAIAAAMQAAALgFAIQgFAIgJAFQgKAEgLABIgZAAIgBAAIAAAuIAAABIgCABgAgXgnIAAAhIABABIAWAAQAIAAAFgGQAFgEAAgHQAAgJgFgEQgFgFgIAAIgWAAIgBABgAi4A+IgBgBIgBgBIAAh3IABgCIABAAIBTAAIABAAIABACIAAARIgBACIgBAAIg7AAIgBABIAAAbIABABIAmAAIACABIABABIAAAQIgBACIgCABIgmAAIgBABIAAAdIABABIA7AAIABAAIABABIAAASIgBABIgBABgAjjA+QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgWgxIgBAAIgRAAIgBAAIAAAxIAAABIgCABIgVAAIgBgBIgBgBIAAh3IABgCIABAAIAzAAQAMgBAIAFQAJAEAFAJQAEAJAAALQAAAMgGAIQgGAJgLADIAAABIAYAyIAAABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAkOgnIAAAeIABABIAXAAQAIAAAFgFQAEgEAAgHQAAgHgEgFQgFgEgIAAIgXAAIgBABgAn5A+IgBgBIgBgBIAAh3IABgCIABAAIAVAAIACAAIAAACIAABjIABABIA6AAIACAAIAAABIAAASIAAABIgCABgApkA+IgBgBIgBgBIAAh3IABgCIABgBIAzAAQALAAAJAFQAJAFAFAJQAFAIAAAMQAAALgFAIQgFAIgJAFQgKAEgLABIgaAAIgBAAIAAAuIAAABIgCABgApNgnIAAAhIABABIAXAAQAIAAAFgGQAFgEAAgHQAAgJgFgEQgFgFgIAAIgXAAIgBABgAqNA+QgBAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgXgoQAAAAAAAAQAAgBgBAAQAAAAAAABQAAAAAAAAIgXAoQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgWAAIgCgBIAAgCIAig7IAAAAIgig7IAAgBQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAWAAQABAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAIAXAoQAAABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBIAXgoQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAABAAIAWAAIACAAIAAACIgjA7IAAAAIAjA8QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAs6A+IgCgBIAAgBIAAh3IAAgCIACAAIBSAAIABAAIABACIAAARIgBACIgBAAIg6AAIgBABIAAAbIABABIAmAAIABABIABABIAAAQIgBACIgBABIgmAAIgBABIAAAdIABABIA6AAIABAAIABABIAAASIgBABIgBABg");
	this.shape_17.setTransform(120.875,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Bg
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AueDNIAAmZIc9AAIAAGZg");
	this.shape_18.setTransform(109.9829,20.475,1.1866,1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FFFFFF").ss(1,1,1).p("ARMDNMgiXAAAIAAmZMAiXAAAg");
	this.shape_19.setTransform(110,20.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18}]}).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_18}]},1).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,222,43);


(lib.gpic4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Arrow
	this.instance = new lib.g_arrow("synched",0);
	this.instance.setTransform(600.1,13,1,1,180,0,0,26,26);

	this.instance_1 = new lib.g_arrow("synched",0);
	this.instance_1.setTransform(461.1,78.1,1,1,0,0,0,26,26);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Red
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BE272E").s().p("EggBAHCIAAuDMBADAAAIAAODg");
	this.shape.setTransform(205,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Photo
	this.instance_2 = new lib.Pic4();
	this.instance_2.setTransform(410,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,90.1);


// stage content:
(lib.banner_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Logo
	this.instance = new lib.g_SFULogo("synched",0);
	this.instance.setTransform(-79.9,10.8,0.7692,0.7685,0,0,0,0.1,0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).to({x:0.1},21,cjs.Ease.get(1)).wait(48).to({startPosition:0},0).to({y:16.85},11,cjs.Ease.get(1)).wait(263));

	// Red_Bg_as_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_79 = new cjs.Graphics().p("AgxHCIAAuDIBjAAIAAODg");
	var mask_graphics_80 = new cjs.Graphics().p("AliHCIAAuDILFAAIAAODg");
	var mask_graphics_81 = new cjs.Graphics().p("AqGHCIAAuDIUNAAIAAODg");
	var mask_graphics_82 = new cjs.Graphics().p("AucHCIAAuDIc5AAIAAODg");
	var mask_graphics_83 = new cjs.Graphics().p("AylHCIAAuDMAlLAAAIAAODg");
	var mask_graphics_84 = new cjs.Graphics().p("A2gHCIAAuDMAtBAAAIAAODg");
	var mask_graphics_85 = new cjs.Graphics().p("A6OHCIAAuDMA0cAAAIAAODg");
	var mask_graphics_86 = new cjs.Graphics().p("A9uHCIAAuDMA7dAAAIAAODg");
	var mask_graphics_87 = new cjs.Graphics().p("EghAAHCIAAuDMBCBAAAIAAODg");
	var mask_graphics_88 = new cjs.Graphics().p("EgkFAHCIAAuDMBILAAAIAAODg");
	var mask_graphics_89 = new cjs.Graphics().p("Egm8AHCIAAuDMBN5AAAIAAODg");
	var mask_graphics_90 = new cjs.Graphics().p("EgpmAHCIAAuDMBTNAAAIAAODg");
	var mask_graphics_91 = new cjs.Graphics().p("EgsCAHCIAAuDMBYFAAAIAAODg");
	var mask_graphics_92 = new cjs.Graphics().p("EguQAHCIAAuDMBciAAAIAAODg");
	var mask_graphics_93 = new cjs.Graphics().p("EgwSAHCIAAuDMBgkAAAIAAODg");
	var mask_graphics_94 = new cjs.Graphics().p("EgyEAHCIAAuDMBkJAAAIAAODg");
	var mask_graphics_95 = new cjs.Graphics().p("EgzrAHCIAAuDMBnWAAAIAAODg");
	var mask_graphics_96 = new cjs.Graphics().p("Eg1DAHCIAAuDMBqHAAAIAAODg");
	var mask_graphics_97 = new cjs.Graphics().p("Eg2NAHCIAAuDMBsbAAAIAAODg");
	var mask_graphics_98 = new cjs.Graphics().p("Eg3LAHCIAAuDMBuWAAAIAAODg");
	var mask_graphics_99 = new cjs.Graphics().p("Eg36AHCIAAuDMBv1AAAIAAODg");
	var mask_graphics_100 = new cjs.Graphics().p("Eg4cAHCIAAuDMBw5AAAIAAODg");
	var mask_graphics_101 = new cjs.Graphics().p("Eg4wAHCIAAuDMBxhAAAIAAODg");
	var mask_graphics_102 = new cjs.Graphics().p("Eg43AHCIAAuDMBxvAAAIAAODg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(79).to({graphics:mask_graphics_79,x:733,y:45}).wait(1).to({graphics:mask_graphics_80,x:701.625,y:45}).wait(1).to({graphics:mask_graphics_81,x:671.625,y:45}).wait(1).to({graphics:mask_graphics_82,x:643.025,y:45}).wait(1).to({graphics:mask_graphics_83,x:615.8,y:45}).wait(1).to({graphics:mask_graphics_84,x:590,y:45}).wait(1).to({graphics:mask_graphics_85,x:565.6,y:45}).wait(1).to({graphics:mask_graphics_86,x:542.575,y:45}).wait(1).to({graphics:mask_graphics_87,x:520.95,y:45}).wait(1).to({graphics:mask_graphics_88,x:500.7,y:45}).wait(1).to({graphics:mask_graphics_89,x:481.9,y:45}).wait(1).to({graphics:mask_graphics_90,x:464.425,y:45}).wait(1).to({graphics:mask_graphics_91,x:448.4,y:45}).wait(1).to({graphics:mask_graphics_92,x:433.75,y:45}).wait(1).to({graphics:mask_graphics_93,x:420.5,y:45}).wait(1).to({graphics:mask_graphics_94,x:408.65,y:45}).wait(1).to({graphics:mask_graphics_95,x:398.2,y:45}).wait(1).to({graphics:mask_graphics_96,x:389.125,y:45}).wait(1).to({graphics:mask_graphics_97,x:381.425,y:45}).wait(1).to({graphics:mask_graphics_98,x:375.15,y:45}).wait(1).to({graphics:mask_graphics_99,x:370.275,y:45}).wait(1).to({graphics:mask_graphics_100,x:366.8,y:45}).wait(1).to({graphics:mask_graphics_101,x:364.7,y:45}).wait(1).to({graphics:mask_graphics_102,x:364,y:45}).wait(252));

	// Btn
	this.instance_1 = new lib.btn_CTA();
	this.instance_1.setTransform(503.55,49.3,1,1,0,0,0,83,25.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn_CTA(), 3);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(258).to({_off:false},0).to({x:513.55,alpha:1},22,cjs.Ease.get(0.9)).wait(74));

	// text_03_AD_123
	this.instance_2 = new lib.g_txt03AD123("synched",0);
	this.instance_2.setTransform(163.75,30.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(210).to({_off:false},0).to({alpha:1},28,cjs.Ease.get(1)).wait(116));

	// text_02__Ad02
	this.instance_3 = new lib.g_txt02AD2new("synched",0);
	this.instance_3.setTransform(-614.4,46,1,1,0,0,0,-66.5,28);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(79).to({_off:false},0).to({x:64.5},25,cjs.Ease.get(1)).wait(79).to({startPosition:0},0).to({x:-614.4},21,cjs.Ease.get(1)).to({_off:true},3).wait(147));

	// Red_Bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC0633").s().p("AgxHCIAAuDIBjAAIAAODg");
	this.shape.setTransform(733,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC0633").s().p("AliHCIAAuDILFAAIAAODg");
	this.shape_1.setTransform(701.625,45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CC0633").s().p("AqGHCIAAuDIUNAAIAAODg");
	this.shape_2.setTransform(671.625,45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC0633").s().p("AucHCIAAuDIc5AAIAAODg");
	this.shape_3.setTransform(643.025,45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC0633").s().p("AylHCIAAuDMAlLAAAIAAODg");
	this.shape_4.setTransform(615.8,45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC0633").s().p("A2gHCIAAuDMAtBAAAIAAODg");
	this.shape_5.setTransform(590,45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CC0633").s().p("A6OHCIAAuDMA0cAAAIAAODg");
	this.shape_6.setTransform(565.6,45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC0633").s().p("A9uHCIAAuDMA7dAAAIAAODg");
	this.shape_7.setTransform(542.575,45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CC0633").s().p("EghAAHCIAAuDMBCBAAAIAAODg");
	this.shape_8.setTransform(520.95,45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CC0633").s().p("EgkFAHCIAAuDMBILAAAIAAODg");
	this.shape_9.setTransform(500.7,45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#CC0633").s().p("Egm8AHCIAAuDMBN5AAAIAAODg");
	this.shape_10.setTransform(481.9,45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CC0633").s().p("EgpmAHCIAAuDMBTNAAAIAAODg");
	this.shape_11.setTransform(464.425,45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CC0633").s().p("EgsCAHCIAAuDMBYFAAAIAAODg");
	this.shape_12.setTransform(448.4,45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#CC0633").s().p("EguQAHCIAAuDMBciAAAIAAODg");
	this.shape_13.setTransform(433.75,45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#CC0633").s().p("EgwSAHCIAAuDMBgkAAAIAAODg");
	this.shape_14.setTransform(420.5,45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#CC0633").s().p("EgyEAHCIAAuDMBkJAAAIAAODg");
	this.shape_15.setTransform(408.65,45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#CC0633").s().p("EgzrAHCIAAuDMBnWAAAIAAODg");
	this.shape_16.setTransform(398.2,45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#CC0633").s().p("Eg1DAHCIAAuDMBqHAAAIAAODg");
	this.shape_17.setTransform(389.125,45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#CC0633").s().p("Eg2NAHCIAAuDMBsbAAAIAAODg");
	this.shape_18.setTransform(381.425,45);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#CC0633").s().p("Eg3LAHCIAAuDMBuWAAAIAAODg");
	this.shape_19.setTransform(375.15,45);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#CC0633").s().p("Eg36AHCIAAuDMBv1AAAIAAODg");
	this.shape_20.setTransform(370.275,45);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#CC0633").s().p("Eg4cAHCIAAuDMBw5AAAIAAODg");
	this.shape_21.setTransform(366.8,45);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#CC0633").s().p("Eg4wAHCIAAuDMBxhAAAIAAODg");
	this.shape_22.setTransform(364.7,45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#CC0633").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_23.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},79).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).wait(252));

	// Red (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EggBAHCIAAuDMBADAAAIAAODg");
	mask_1.setTransform(205,45);

	// Text_01___AD_2
	this.instance_4 = new lib.g_txt01AD2New("synched",0);
	this.instance_4.setTransform(797.45,58.75,1,1,0,0,0,-66.5,28);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(11).to({_off:false},0).to({x:333.5},21,cjs.Ease.get(1)).to({_off:true},72).wait(250));

	// Photo_AD2_old4
	this.instance_5 = new lib.gpic4("single",0);
	var instance_5Filter_1 = new cjs.ColorFilter(1,1,1,1,255,255,255,0);
	this.instance_5.filters = [instance_5Filter_1];
	this.instance_5.cache(-2,-2,732,94);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({startPosition:0},18,cjs.Ease.get(1)).to({_off:true},86).wait(250));
	this.timeline.addTween(cjs.Tween.get(instance_5Filter_1).to(new cjs.ColorFilter(1,1,1,1,0,0,0,0), 18,cjs.Ease.get(1)).wait(250));

	this.filterCacheList = [];
	this.filterCacheList.push({instance: this.instance_5, startFrame:1, endFrame:18, x:-2, y:-2, w:732, h:94});
	this.filterCacheList.push({instance: this.instance_5, startFrame:0, endFrame:0, x:-2, y:-2, w:732, h:94});
	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(284,45,454,45.099999999999994);
// library properties:
lib.properties = {
	id: 'C38F8E925B074A239B4A15BB5DD6BAC8',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C38F8E925B074A239B4A15BB5DD6BAC8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;